/**
 * Wisconsin State Fair — official 2026 new foods & beverages.
 * Sources:
 *   https://wistatefair.com/fair/new-foods/
 *   https://wistatefair.com/fair/wp-content/uploads/2026/07/2026_New_Foods_List_FINAL_V5.pdf
 *   https://wistatefair.com/fair/food-finder/ (WordPress food CPT)
 *
 * Descriptions are original Stadium Slop paraphrases — not copied promotional copy.
 */

import type { FairRawMenuItem } from "../types";

export const WISCONSIN_2026_NEW_FOODS: FairRawMenuItem[] = [
  {
    name: 'Al Pastor Pizza',
    vendor: 'Charlie\'s Pizza',
    location: 'Second Street 166',
    description: 'Pizza with marinated al pastor pork, mozzarella, pineapple, cilantro, white onion, lime, and special sauce',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-finalist'],
  },
  {
    name: 'Bayou Crunch Cup',
    vendor: 'Exotic Meat Grill',
    location: 'South Grandstand Avenue 55',
    description: 'Sidewinder fries topped with Cajun slaw, alligator nuggets, crawfish bites, comeback sauce, pickled okra, and a whole crawfish garnish',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-finalist'],
  },
  {
    name: 'Big Pat’s Pit Stop Punch',
    vendor: 'Leadfoots Race Bar & Grill',
    description: 'Pineapple juice, lemon-lime soda, and rainbow sherbet punch.',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Birria Flamin’ Bombs',
    vendor: 'Fiesta Grill & Cantina',
    description: 'Crispy bombs filled with beef birria, cilantro, onion, and mozzarella; served with consommé and chipotle aioli',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-finalist'],
  },
  {
    name: 'Biscoff Hot Fudge Cup',
    vendor: 'Ultimate Confections',
    location: 'Exposition Center, Wisconsin Building',
    description: 'Biscoff Hot Fudge Cup is a premium milk chocolate cup filled with smooth Biscoff cookie butter and rich hot fudge',
    fare: 'Desserts',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Bloody Mary Mac Daddy',
    vendor: 'Pop\'s Paradise',
    location: 'Second Street',
    description: 'The Bloody Mary Mac Daddy was born from one simple idea, what if you could take everything people love about a Wisconsin Bloody Mary and turn it into a meal? This dish spotlights c reamy mac and cheese infused with Pop\'s',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Blue Ribbon Watermelon Mint Julep',
    vendor: 'Flying Solo Bar & Grill',
    location: 'Wetley Way & Second Street',
    description: 'Blue Ribbon Watermelon Mint Julep sweet and tangy pink lemonade, fresh watermelon puree flavor, cool mint syrup and lightly sweetened with bourbon-flavor',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Bourbon Deep-Fried Pecan Pie',
    vendor: 'Minneapple Pie',
    location: 'Back Forty 117',
    description: 'Bourbon Deep – Fried Pecan Pie fea tures Bo urbon infused Pecan filling in a homemade flakey crust that is f ried th at\'s dusted with brown sugar and s erved with a scoop of vanilla or cinnamon ice cream',
    fare: 'Desserts',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Bugged Out Frozen Cheesecake On-a-Stick',
    vendor: 'All Things Jerky',
    location: 'South Grandstand Avenue 56',
    description: 'Bugged Out Frozen Cheesecake On- a -Stick is a , creepy-crawly dessert adventure. Creamy cheesecake with a center of caramel and ants, dipped in chocolate, then loaded with crunchy crickets and worms',
    fare: 'Desserts',
    extraTags: ['new-2026', 'sporkies-contestant', 'on-a-stick'],
  },
  {
    name: 'Bunzel’s Hungarian Sausage Sandwich',
    vendor: 'Leff’s Miller Lite Sports Bar & Grill',
    description: 'Bunzel’s Hungarian Sausage Sandwich (Mild or Hot)',
    fare: 'Meals',
    extraTags: ['new-2026'],
  },
  {
    name: 'Candied Bacon Cheese Curds',
    vendor: 'Leff’s Miller Lite Sports Bar & Grill',
    location: 'Grandstand Avenue & Second Street',
    description: 'Candied Bacon Cheese Curds with ranch dressing',
    fare: 'Snacks',
    extraTags: ['new-2026'],
  },
  {
    name: 'Caramel Apple Cheese Curd Tacos',
    vendor: 'Richie\'s Cheese Curd Tacos',
    location: 'Wetley Way 106',
    description: 'Caramel Apple Cheese Curd Tacos takes sweet and cheesy to the next level',
    fare: 'Desserts',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Cevapcici – Croatian Sausage Sandwich',
    vendor: 'Robert’s',
    location: 'Grandstand Avenue',
    description: 'Croatian Sausage on a bun',
    fare: 'Meals',
    extraTags: ['new-2026'],
  },
  {
    name: 'Cheddar Garlic Longanisa Lumpia with Banana Ketchup',
    vendor: 'Lumpia City',
    location: 'Grandstand Avenue 51',
    description: 'Cheddar Garlic Longanisa Lumpia with Banana Ketchup spotlight s a Lumpia with a deep – fried thin, crispy shell filled with a traditional sweet and garlicky Filipino sausage, c herished Wisconsin staple of fresh Door Cou',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Chicken Cordon Bleu Sausage',
    vendor: 'WurstBar',
    location: 'Central Avenue & Second Street',
    description: 'Chicken Cordon Bleu Sausage!',
    fare: 'Meals',
    extraTags: ['new-2026'],
  },
  {
    name: 'Chimi-Brat-Changa',
    vendor: 'Leff\'s Miller Lite Sports Bar & Grill',
    location: 'Grandstand Avenue & Second Street',
    description: 'The Chimi-Brat-Changa is a combination of Bunzel\'s homemade bratwurst, refried beans , and cheddar cheese wrapped in a flour tortilla and fried to a golden brown',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Chocolate Covered Strawberry Sipper',
    vendor: 'Olympia Granola',
    location: 'Wisconsin Building',
    description: 'Strawberry oat milk, chocolate, and Wisconsin honey over ice with an Olympia Granola strawberry chocolate granola bar dipper. Gluten-free and dairy-free per fair listing',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    dietaryTags: ['Gluten Free'],
    extraTags: ['new-2026'],
  },
  {
    name: 'Churro Dog',
    vendor: 'Badger Bites',
    location: 'Central Avenue & Second Street',
    description: 'A family favorite mashup of a churro and glazed long john! The Churro Dog is a caramel churro nestled in a freshly glazed Grebes donut topped with vanilla ice cream, whipped cream, chocolate sauce, caramel sauce, and ras',
    fare: 'Desserts',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Circus Peanut Spritz',
    vendor: 'Leff\'s Lite Lounge',
    location: 'South Grandstand Avenue 67',
    description: 'The Circus Peanut Spritz is',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Cold Foam Berry Blast',
    vendor: 'Krautland',
    location: 'Central Avenue',
    description: 'Cold Foam Berry Blast is a crisp iced lemonade layered with strawberry puree and topped with freshly whipped blueberry cold foam',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Color-Changing Swamp Juice',
    vendor: 'All Things Jerky',
    location: 'South Grandstand Avenue 56',
    description: 'Blue raspberry lemonade with a color-changing swamp potion, gummy gators, candy frogs, and a Pop Rocks rim. Shellfish allergy notice for bug toppings on related booth items',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-finalist'],
  },
  {
    name: 'Cookie Butter Coffee Float',
    vendor: 'Fluffy\'s Hand Cut Donuts',
    location: 'South Grandstand Avenue 74',
    description: 'Vanilla ice cream with cookie butter iced coffee, Biscoff crumble rim, cookie butter drizzle, and a Biscoff cookie',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-finalist'],
  },
  {
    name: 'Cosmic Funnel Cake',
    vendor: 'Rick’s Elephant Ears',
    location: 'Main Street 81',
    description: 'A hot, golden funnel cake dusted with powdered sugar, topped with sweet purple drizzle icing and crunchy freeze dried Skittles for a fruity burst in every bite',
    fare: 'Desserts',
    extraTags: ['new-2026'],
  },
  {
    name: 'Cranberry Dream Bar',
    vendor: 'Wisconsin State Cranberry Growers',
    location: 'Wisconsin Building',
    description: 'Blonde brownie, premium Wisconsin cranberries, white chocolate pieces, creamy frosting and dried cranberries',
    fare: 'Desserts',
    extraTags: ['new-2026'],
  },
  {
    name: 'Cream City Cone',
    vendor: 'WurstBar',
    location: 'Central Avenue & Second Street',
    description: 'Pretzel cone dipped in dill pickle mustard, filled with bratwurst, sautéed onions and mushrooms, melted cheddar, and a breaded white cheddar curd',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-finalist'],
  },
  {
    name: 'Cuban Fries',
    vendor: 'Tropics',
    location: 'Wetley Way & First Street',
    description: 'Cuban Fries were inspired by the bold, flavors of the classic Cuban sandwich , one of the most iconic and beloved foods in tropical and coastal communities',
    fare: 'Snacks',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Deep-Fried Horchata Balls',
    vendor: 'Badger Bites',
    location: 'Central Avenue & Second Street',
    description: 'Fried bites dusted in cinnamon sugar with dulce de leche, chocolate sauce, mini chocolate chips, toasted coconut, and fried plantain chips',
    fare: 'Desserts',
    extraTags: ['new-2026', 'sporkies-finalist'],
  },
  {
    name: 'Deep-Fried Ranch',
    vendor: 'All Family Concessions',
    location: 'Back Forty 118',
    description: 'Deep-Fried Ranch features a creamy filling made with ranch seasoning, cream cheese and buttermilk. Coated in a crispy panko shell and deep fried until golden perfection',
    fare: 'Snacks',
    extraTags: ['new-2026'],
  },
  {
    name: 'Deep-Fried Top The Tater',
    vendor: 'All Family Concessions',
    location: 'Back Forty 118',
    description: 'Midwest Legendary Dip inside a potato chip crusted shell and deep-fried to golden perfection. Options include the original Top the Tater (chive and onion) or Zesty Buffalo Top the Tater',
    fare: 'Snacks',
    extraTags: ['new-2026'],
  },
  {
    name: 'Dill-icious Pickles – Bloody Mary Pickles',
    vendor: 'Starla’s Seasonings, Dips & Mixes',
    location: 'Wisconsin Building',
    description: 'Gourmet jumbo refrigerator pickles seasoned with tomato, horseradish, onion, parsley and dill',
    fare: 'Snacks',
    extraTags: ['new-2026'],
  },
  {
    name: 'Dill-uxe Pickle Fries',
    vendor: 'Deep-Fried Mashed Potatoes On-a-Stick',
    location: 'Center Street & Badger Avenue 152',
    description: 'Dill- uxe Pickle Fries Dig into the Dill- uxe Pickle Fries! Find c rispy golden fries tossed in a signature dill pickle dry rub seasoning, topped with Wisconsin cheese curds, Doritos-crusted fried pickle chunks, and fini',
    fare: 'Snacks',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Egg Roll A-La-Mode',
    vendor: 'Camp Bar',
    location: 'Central Avenue',
    description: 'Th e Egg Roll A-La-Mode blends sweet and savory elements with iconic Wisconsin custard! This crispy deep-fried egg roll is stuffed with scrambled eggs, sausage, hash browns, and dipped in rich Wisconsin frozen custard',
    fare: 'Desserts',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Ellsworth Fresh Cheese Curds',
    vendor: 'Brad & Harry’s Cheese Curds',
    location: 'Central Avenue',
    description: 'Fresh Ellsworth cheddar curds in Original, Garlic, Pizza, Jalapeño, and Dill Pickle flavors',
    fare: 'Snacks',
    extraTags: ['new-2026'],
  },
  {
    name: 'Freedom Brat',
    vendor: 'Leadfoots Race Bar & Grill',
    location: 'Grandstand Avenue',
    description: 'Brat that is blended with dried cranberry, mozzarella cheese, and dried blueberry inside',
    fare: 'Meals',
    extraTags: ['new-2026'],
  },
  {
    name: 'Freeze Dried Cheese Curds',
    vendor: 'Everlasting Eats',
    location: 'Exposition Center',
    description: 'Fresh cheese curds freeze dried for a crunchy, crave-able snack that you can take with you',
    fare: 'Snacks',
    extraTags: ['new-2026'],
  },
  {
    name: 'French Onion Cheese Pull',
    vendor: 'Attavio\'s Concessions',
    location: 'Second Street & Badger Avenue 170',
    description: 'French Onion Cheese Pull is i nspired by the flavor of classic French onion soup but even cheesier',
    fare: 'Snacks',
    extraTags: ['new-2026', 'sporkies-contestant', 'on-a-stick'],
  },
  {
    name: 'Fruit Roll-Up Remix',
    vendor: 'Buzzy Badger',
    location: 'Main Street & Dairy Lane',
    description: 'Fruit Roll-Up Remix is yo ur favorite childhood candy in liquid form ! Sip on lem onade infused with strawberry syrup, lavender syrup, and finished with strawberry cotton candy cold foam with a Fruit Roll-up wrapped stra',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Gluten-Free Chimichurri Cheese Curds',
    vendor: 'Keys Gluten-Free Fair Foods',
    location: 'North Grandstand Avenue 8',
    description: 'Gluten-free fried Wisconsin cheese curds with chimichurri flavoring',
    fare: 'Snacks',
    dietaryTags: ['Gluten Free'],
    extraTags: ['new-2026'],
  },
  {
    name: 'Guac This Way Tots',
    vendor: 'Knucklehead',
    location: 'Central Avenue',
    description: 'Guac This Way T ots A fter refining the balance of flavors and textures, were born',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Hawaiian Pizza Slush',
    vendor: 'Exotic Meat Grill',
    location: 'South Grandstand Avenue 55',
    description: 'Hawaiian Pizza Slush delivers a playful punch of sweet pineapple and savory pizza sauce in an icy, refreshing blend',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Hot Honey Bacon Corn Dog',
    vendor: 'Charlie’s Great Food',
    location: 'Badger Avenue 148',
    description: 'The hot dog is dipped in the perfect amount of our secret homemade batter, made',
    fare: 'Meals',
    extraTags: ['new-2026', 'on-a-stick'],
  },
  {
    name: 'Hot Honey Chicken Lemonade',
    vendor: 'Deep-Fried Mashed Potatoes On-a-Stick',
    location: 'Center Street & Badger Avenue 152',
    description: 'Fresh lemonade sweetened with hot honey, garnished with hot-honey chicken nuggets and honey popping pearls',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-finalist', 'on-a-stick'],
  },
  {
    name: 'Hot Honey Heatwave Fries',
    vendor: 'Fresh Cut Fries',
    location: 'Grandstand Avenue 41',
    description: 'Hot Honey Heatwave Fries are c rispy fresh-cut fries tossed in bold chili garlic crunch and finished with a drizzle of sweet hot honey and chives',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Ice Cream Nachos',
    vendor: 'Buzzy Badger',
    location: 'Main Street & Dairy Lane',
    description: 'Waffle-cone chips and ice cream with Cookies and Cream, Loaded Campfire, or Peanut Butter Cup toppings',
    fare: 'Desserts',
    extraTags: ['new-2026'],
  },
  {
    name: 'Lemon-Lime Spritz',
    vendor: 'Knucklehead',
    location: 'Central Avenue & Center Street',
    description: 'Lemon-Lime Spritz drink',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026'],
  },
  {
    name: 'Little Smokies Campfire Meal',
    vendor: 'Campsite 107',
    location: 'Grandstand Avenue',
    description: 'Little smokies, potato wedges, half corn, BBQ sauce, shredded cheddar cheese',
    fare: 'Meals',
    extraTags: ['new-2026'],
  },
  {
    name: 'Monkey Bread',
    vendor: 'Buzzy Badger',
    location: 'Main Street & Dairy Lane',
    description: 'Mon key Bread Mon key Bread is a cup full of i ce-cold Mr. Pibb swirled with butterscotch syrup, cinnamon bun syrup , sweet cream , and piled high with whipped cream and a dusting of cinnamon',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Monster Blue Hawaiian Dirty Soda',
    vendor: 'Badger Bites',
    location: 'Central Avenue & Second Street',
    description: 'Blue Hawaiian Monster, blue raspberry syrup, coconut syrup, and sweet cream creamer – !',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026'],
  },
  {
    name: 'Nitro Cheesy Puffs',
    vendor: 'Dragon’s Breath',
    location: 'Exposition Center',
    description: 'Airy cheesy puffs dipped in liquid nitrogen, instantly freezing them to create a crisp, melt-away bite. turning each handful into a playful “dragon’s breath” experience',
    fare: 'Snacks',
    extraTags: ['new-2026'],
  },
  {
    name: 'Orange Creamsicle Lemonade',
    vendor: 'Badger Bites',
    location: 'Central Avenue & Second Street',
    description: 'Lemonade with candied orange and french vanilla syrup',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026'],
  },
  {
    name: 'Pasty',
    vendor: 'Sheboygan Pasty Company',
    location: 'Wisconsin Building',
    description: 'Sheboygan Pasty Company pasties including new Southwestern Chorizo, plus Blueberry Peach Dessert, Sheboygan Bratwurst, Traditional Beef, and Breakfast',
    fare: 'Meals',
    extraTags: ['new-2026'],
  },
  {
    name: 'Patriotic Punch',
    vendor: 'Leff’s Miller Lite Sports Bar & Grill',
    location: 'Grandstand Avenue & Second Street',
    description: 'Patriotic Punch is a tribute to our country’s semi quincentennial . It is a blended and layered refreshing lemonade drink with layers of cherry, sweet cream, and blue raspberry, garnished with an American flag',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Peach Beary Boba',
    vendor: 'Tri Boba Tea',
    location: 'Exposition Center',
    description: 'A refreshing peach green tea bursting with juicy peach popping boba with a gummy bear that sits inside a peach ring floating on top, finished with a tiny umbrella for a fun, whimsical touch',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026'],
  },
  {
    name: 'Peaches n’ Cream Whipped Frozen Lemonade',
    vendor: 'Gertrude\'s Pretzels',
    description: 'Peaches n\' Cream Whipped Frozen Lemonade is This house made frozen whipped lemonade is blended with freestone peaches, topped with whipped cream and a slice of peach',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Peachy Keen Cooler',
    vendor: 'Knucklehead',
    location: 'Central Avenue & Center Street',
    description: 'Peachy Keen Cooler blends freshly squeezed lemon and lime with peach nectar and lemonade for a bright, refreshing burst of summer',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Pineapple Pop Paradise',
    vendor: 'Saz’s Bavarian Pretzel',
    location: 'Badger Avenue & Second Street',
    description: 'Pineapple Pop Paradise starts with fresh chunks of fresh pineapple along with pineapple juice and yuzu marmalade syrup to br ing in a subtle citrus sharpness t o cut through the sweetness',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Pop’s Kettle Me Squeeze',
    vendor: 'Pop\'s Paradise',
    description: 'Pop\'s Kettle Me Squeeze came to life combining Pop\'s Original Kettle Corn and the classic, cold lemonade you get at Wisconsin State Fair! Not only is it topped with a handful of classic Kettle Corn but this drink also fe',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: "Pork 'N' Pine Brat Burger",
    vendor: 'Flying Solo Bar & Grill',
    location: 'Wetley Way & Second Street',
    description:
      'Johnsonville bratwurst patty topped with a caramelized pineapple ring in house teriyaki sauce, served on a bun with lettuce, tomato, onion, and jalapeño cheese',
    fare: 'Meals',
    extraTags: ['new-2026'],
  },
  {
    name: 'Porky Puff',
    vendor: 'Bud Pavilion',
    location: 'Central Avenue',
    description: 'Puff pastry with pulled pork, peach filling, and garlic-herb cheese; finished with hot honey and mustard seeds',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-finalist'],
  },
  {
    name: 'Potato Chip Sundae',
    vendor: 'Kora & Mila\'s Cookie Dough',
    location: 'Main Street | Second Street 171',
    description: 'Potato Chip Sundae features s weet , salty, and seriously addictive-salted caramel ice cream, hot gooey deep – fried cookie dough, rich salted caramel chocolate sauce, and crispy ruffled potato chip s for a crunch in eve',
    fare: 'Desserts',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Puggets',
    vendor: 'Dale Z’s On Tour',
    location: 'Grandstand Avenue & Second Street',
    description: 'Chicken breaded in pork-rind dust and fried; plain or pickle seasoning. BBQ, ranch, or hot sauce on request. Listed gluten-free and low carb',
    fare: 'Snacks',
    dietaryTags: ['Gluten Free'],
    extraTags: ['new-2026'],
  },
  {
    name: 'Ranch BLT Dog',
    vendor: 'Craft Haute Dog at Blue Moon Tavern at the Park',
    location: 'Grandstand Avenue & Main Street',
    description: 'Gourmet Haute Dog topped with bacon, lettuce, tomato, and ranch dressing',
    fare: 'Meals',
    extraTags: ['new-2026'],
  },
  {
    name: 'Red, White & Berry',
    vendor: 'Caribbean Smoothies',
    location: 'First Street 129 | Second Street 167',
    description: 'Inspired by America\'s 250th anniversary, Red, White & Berry brings the classic colors of celebration to life with a tropical twist by layering strawberry, piña colada, and mixed berry into a bold, refreshing smoothie tha',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Redneck Brat',
    vendor: 'Doc’s Smokehouse',
    location: 'First Street 128',
    description: 'Usinger’s Cajun Brat loaded with slow-smoked pulled pork and crisp creamy coleslaw, finished with a drizzle of tangy Carolina Gold BBQ sauce',
    fare: 'Meals',
    extraTags: ['new-2026'],
  },
  {
    name: 'Smoked Pork Pierogi Sliders',
    vendor: 'Charlie\'s Turkey Leg',
    location: 'Center Street & Badger Avenue 147',
    description: 'Smoked Pork Pierogi Sliders flip the script by usin g buttery pierogi as the bun, stuffed with tend er, slow-smoked pork and cheddar cheese and t opped with crisp, sweet coleslaw, rich BBQ sauce, and a punchy pickle to c',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Soft Serve Beer',
    vendor: 'Bud Pavilion',
    location: 'Central Avenue',
    description: 'New Glarus Raspberry Tart beer spun with Wisconsin dairy into a soft-serve swirl',
    allowBeverage: true,
    beverageCategory: 'Alcoholic Drink',
    extraTags: ['new-2026'],
  },
  {
    name: 'Spam Jerky Spampler',
    vendor: 'All Things Jerky',
    location: 'South Grandstand Avenue 56',
    description: 'The Spam Jerky Spampler features a bold trio of jerky crafted from Spam in three flavors: smoked, brown sugar, and cracked pepper & garlic',
    fare: 'Snacks',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Star-Spangled Bomb Pop',
    vendor: 'Rock & Roll Beer Garden',
    location: 'Wetley Way',
    description: 'Inspired by the classic Bomb Pop, Star-Spangled Bomb Pop is a bold, colorful, ice-cold throwback with a modern twist',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Sweet Lemon Berry Cheese Curds',
    vendor: 'Saz\'s BBQ',
    location: 'Badger Avenue & Second Street',
    description: 'Fried Ellsworth white cheddar curds tossed in cinnamon sugar with raspberry sauce and sweet lemon zest cream whip',
    fare: 'Desserts',
    extraTags: ['new-2026', 'sporkies-finalist'],
  },
  {
    name: 'Tanghulu',
    vendor: 'Lulu Tanghulu',
    location: 'Exposition Center',
    description: 'Fresh fruit dipped in a sugary candy coating',
    fare: 'Desserts',
    dietaryTags: ['Vegetarian'],
    extraTags: ['new-2026', 'on-a-stick'],
  },
  {
    name: 'The Blue Moo Lagoon',
    vendor: 'Bubble Tea & Waffles',
    location: 'North Grandstand Avenue 15',
    description: 'The Blue Moo Lagoon delivers a wave of tropical vibes with splashes of pin eapple juice , a swirl of coconut cream , blue curaçao , and passion fruit boba',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'The Dirty Dog',
    vendor: 'Pop’s Paradise',
    location: 'Second Street & Central Avenue',
    description: 'A smoked brisket burnt-end sausage with a kick on a pretzel bun topped with brisket chili and cheddar jack cheese',
    fare: 'Meals',
    extraTags: ['new-2026'],
  },
  {
    name: 'The Wisconsinite Slush',
    vendor: 'Pickle Barrel',
    location: 'Exposition Center, Dairy Building',
    description: 'The Wisconsinite Slush transforms Pickle Barrel\'s beloved real kosher dill pickle juice into an icy, slushie, swirled it with zesty Tajin, and topped with Wisconsin staples of two baby dill pickles, a Klement\'s beef stic',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Tilt-a-Spritz',
    vendor: 'Old Fashioned Sipper Club',
    location: 'Central Avenue & First Street',
    description: 'Ruby grapefruit and key lime with ginger beer; presented with hickory smoke and torched rosemary',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-finalist'],
  },
  {
    name: 'Tinga Tango Chicharrones',
    vendor: 'Blue Moon Tavern at the Park',
    location: 'Grandstand Avenue & Main Street',
    description: 'Honey-habanero pork rinds topped with chicken tinga, pickled red onions, queso fresco, cotija, candied jalapeños, cilantro-lime crema, and salsa verde',
    fare: 'Meals',
    extraTags: ['new-2026', 'sporkies-finalist'],
  },
  {
    name: 'Toffee Tumble',
    vendor: 'Prairie Junction Co',
    location: 'Wisconsin Building',
    description: 'The Toffee Tumbl e is your new favorite snack leveled up – chocolatey, crunchy bites with a hidden toffee twist and a sweet sugar shake Gluten-free and nut free !',
    fare: 'Desserts',
    dietaryTags: ['Gluten Free'],
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Triple Chocolate Mini Donuts',
    vendor: 'Mini Donuts',
    location: 'Center Street 153',
    description: 'Triple Chocolate Mini Donuts – enough said!',
    fare: 'Desserts',
    extraTags: ['new-2026'],
  },
  {
    name: 'Tropical Tide',
    vendor: 'Tropics',
    location: 'Wetley Way & First Street',
    description: 'Tropical Tide b lends vibrant blue raspberry and fresh lemonade over ice, then tops it with a smooth, cloud-like sweet cream cold foam that gently drifts into the drink',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Vegan Cheesesteak Eggrolls',
    vendor: 'Twisted Plants',
    location: 'Back Forty 101',
    description: 'Egg rolls with plant-based steak, sautéed peppers and onions, and vegan cheese',
    fare: 'Meals',
    dietaryTags: ['Vegan'],
    extraTags: ['new-2026'],
  },
  {
    name: 'Waffle Cone S’mores',
    vendor: 'Campsite 107',
    description: 'All the flavors of a s’more in a crispy waffle cone with graham cereal, marshmallows, and chocolate chips',
    fare: 'Desserts',
    extraTags: ['new-2026'],
  },
  {
    name: 'Why Not Tots',
    vendor: 'Knucklehead',
    location: 'Central Avenue & Center Street',
    description: 'Inspired by the spirit of State Fair, Why Not Tots bring a smile to your face as it turns the unexpected into something',
    fare: 'Desserts',
    extraTags: ['new-2026', 'sporkies-contestant'],
  },
  {
    name: 'Wild Grape Dirty Soda',
    vendor: 'Attavio\'s Concessions',
    location: 'Second Street & Badger Avenue 170',
    description: 'Wild Grape Dirty Soda is a bold, refreshing mix of crisp grape soda, smooth vanilla cream, and a splash of fresh lime for balance',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  },
  {
    name: 'Wisco Short Rib Corn Dog',
    vendor: 'Expo Concession Stand # 2',
    location: 'Exposition Center',
    description: 'The Wisco Short Rib Corn Dog features the best from Wisconsin Farmers! This corn dog features a b raised short rib and raw milk gouda skewer , hand battered in New Glarus beer corn bread mix and crunchy breadcrumbs, then',
    fare: 'Meals',
    extraTags: ['new-2026', 'on-a-stick'],
  },
  {
    name: 'Wisconsin Chocolate Barnyard Float',
    vendor: 'Root Beer MKE',
    location: 'Central Marketplace 141',
    description: 'Celebrate Wisconsin\'s Dairyland with every sip of this Wisconsin Chocolate Barnyard Float! This drink is a root beer float brimming with chocolate ice cream and c rowned atop this dessert experience is " Floata Belle," a',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['new-2026', 'drinkies-contestant'],
  }
];
