/**
 * Wisconsin State Fair — verified returning / classic Food Finder items (2026 season).
 * Source: https://wistatefair.com/fair/food-finder/
 *
 * Includes State Fair favorites, Wisconsin staples, and returning past Sporkies/Drinkies
 * entries with verified vendor names. Multi-vendor staples list a primary vendor only.
 * Items marked NOT RETURNING 2026 are excluded.
 */

import type { FairRawMenuItem } from "../types";

export const WISCONSIN_2026_CORE_CATALOG: FairRawMenuItem[] = [
  {
    name: 'Original Cream Puff',
    vendor: 'Original Cream Puff Bakery',
    description: 'Wisconsin State Fair cream puff — sold individually or in packs at Original Cream Puff Bakery and To-Go stands.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite', 'wisconsin-staple'],
  },
  {
    name: 'Cheese Curds',
    vendor: 'Brad & Harry\'s Cheese Curds',
    description: 'Deep-fried cheese curds, a Wisconsin State Fair staple.',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Corn Dog',
    vendor: '3B Corn Dogs',
    description: 'Classic fair corn dog on a stick.',
    fare: 'Meals',
    extraTags: ['core-catalog', 'state-fair-favorite', 'on-a-stick'],
  },
  {
    name: 'Funnel Cake',
    vendor: 'Funnel Cakes',
    description: 'Deep-fried funnel cake dusted with powdered sugar.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Elephant Ears',
    vendor: 'Rick\'s Elephant Ears',
    description: 'Fried dough elephant ear.',
    fare: 'Desserts',
    extraTags: ['core-catalog'],
  },
  {
    name: 'Turkey Leg',
    vendor: 'Charcoal Grill Roadhouse',
    description: 'Roasted turkey leg.',
    fare: 'Meals',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Mini Donuts',
    vendor: 'L&M Concessions',
    description: 'Fresh mini donuts.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Roasted Corn on the Cob',
    vendor: 'Adeline\'s Corn',
    description: 'Roasted corn on the cob.',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite', 'wisconsin-staple'],
  },
  {
    name: 'Roasted Corn in a Cup',
    vendor: 'Adeline\'s Corn',
    description: 'Roasted corn served in a cup.',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite', 'wisconsin-staple'],
  },
  {
    name: 'Sheboygan Brat',
    vendor: 'Sheboygan Brat Haus',
    description: 'Sheboygan-style bratwurst.',
    fare: 'Meals',
    extraTags: ['core-catalog', 'wisconsin-staple'],
  },
  {
    name: 'Pork Chop On-a-Stick',
    vendor: 'Charlie\'s Turkey Leg',
    description: 'Grilled pork chop served on a stick.',
    fare: 'Meals',
    extraTags: ['core-catalog', 'state-fair-favorite', 'wisconsin-staple', 'on-a-stick'],
  },
  {
    name: 'Italian Sausage Sandwich',
    vendor: 'Charlie\'s Great Food',
    description: 'Italian sausage sandwich.',
    fare: 'Meals',
    extraTags: ['core-catalog', 'state-fair-favorite', 'wisconsin-staple'],
  },
  {
    name: 'Ice Cream Cone',
    vendor: 'Cedar Crest Ice Cream',
    description: 'Ice cream cone.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Baked Potato',
    vendor: 'Derynda\'s Dairy Lane',
    description: 'Baked potato.',
    fare: 'Snacks',
    extraTags: ['core-catalog', 'state-fair-favorite', 'wisconsin-staple'],
  },
  {
    name: 'Walking Taco',
    vendor: 'Fiesta Grill',
    description: 'Walking taco.',
    fare: 'Meals',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Nachos',
    vendor: '3B Corn Dogs',
    description: 'Fair nachos.',
    fare: 'Meals',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Kettle Corn',
    vendor: 'Kettle Corn',
    description: 'Kettle corn.',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Blooming Onion',
    vendor: 'The Big Cheese',
    description: 'Deep-fried blooming onion.',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Fried Pickles',
    vendor: 'Leadfoots Race Bar & Grill',
    description: 'Fried pickle chips or spears.',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Beignet',
    vendor: 'Piche’s Beignets',
    description: 'French-style beignet.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Lemon Chill',
    vendor: 'Gourmet Pretzel & Chill',
    description: 'Frozen lemon chill.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Cinnamon Rolls',
    vendor: 'Cinnamon Rolls',
    description: 'Fairground cinnamon rolls.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Fresh Cheese Curds',
    vendor: 'Fresh Squeaky Curds!',
    description: 'Fresh squeaky Wisconsin cheese curds.',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'wisconsin-staple'],
  },
  {
    name: 'Ellsworth Creamery White Cheddar Cheese Curds',
    vendor: 'Saz’s BBQ',
    description: 'Ellsworth Creamery white cheddar cheese curds.',
    fare: 'Snacks',
    extraTags: ['core-catalog', 'wisconsin-staple'],
  },
  {
    name: 'Mexican Style Corn on the Cob',
    vendor: 'El Jefe Roasted Corn',
    description: 'Roasted corn is topped with mayo, Mexican cheese, and chili powder – the amount of chili powder is up to you!',
    fare: 'Meals',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Mexican Style Corn in a Cup',
    vendor: 'El Jefe Roasted Corn',
    description: 'Roasted corn is topped with mayo, Mexican cheese, and chili powder – the amount of chili powder is up to you! All served in a cup with a fork',
    fare: 'Meals',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Smoked Polish Sausage',
    vendor: 'Charlie\'s Great Food',
    description: 'A Wisconsin favorite – whether you are tailgating or strolling around the State Fair',
    fare: 'Meals',
    extraTags: ['core-catalog', 'wisconsin-staple'],
  },
  {
    name: 'Pork Burger',
    vendor: 'Pork Schoppe',
    description: 'A porky spin on an American classic',
    fare: 'Meals',
    extraTags: ['core-catalog', 'wisconsin-staple'],
  },
  {
    name: 'Ribeye Steak Sandwich',
    vendor: 'Wisconsin Cattlemen’s Association',
    description: 'Seasoned and grilled ribeye sandwich served with onions',
    fare: 'Meals',
    extraTags: ['core-catalog', 'wisconsin-staple'],
  },
  {
    name: 'Potato Pancakes',
    vendor: 'Cracovia',
    description: 'Visit either of these vendors for their version of this European pancake with its various toppings such as applesauce, sour cream, or Polish sausage',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'wisconsin-staple'],
  },
  {
    name: 'Grilled Cheddar Cheese Sandwich',
    vendor: 'Real Wisconsin Cheese Grill',
    description: 'It’s the sandwich that started it all, the original grilled cheese',
    fare: 'Meals',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'wisconsin-staple'],
  },
  {
    name: 'Deep-Fried Oreos',
    vendor: 'Funnel Cakes & Corn Dogs',
    description: 'You might think Oreos are already great, but believe it or not, they are made even better when battered, deep-fried, and sprinkled with powdered sugar. Sure to be a favorite you go back for each year',
    fare: 'Desserts',
    extraTags: ['core-catalog'],
  },
  {
    name: 'Cookie Dough On-a-Stick',
    vendor: 'Kora & Mila’s Cookie Dough',
    description: 'Assemble your very own cookie dough on-a-stick by choosing from the following cookie dough, coating, and topping options. Dough Choice: chocolate chip, peanut butter, monster cookie, sugar.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite', 'on-a-stick'],
  },
  {
    name: 'Chocolate-Covered Cheesecake On-a-Stick',
    vendor: 'Hand Dipped Ice Cream',
    description: 'Chocolate Covered Cheesecake On-a-Stick Fair calories don’t really count, right?',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite', 'on-a-stick'],
  },
  {
    name: 'Chocolate-Dipped Frozen Banana On-a-Stick',
    vendor: 'Candy Factory',
    description: 'Enjoy your chocolate banana either plain or rolled in nuts and sprinkles. Served on a stick',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite', 'on-a-stick'],
  },
  {
    name: 'Candy Apple',
    vendor: 'Big Daddy\'s Candy Monster',
    description: 'Whole apples covered in a toffee or a sugar candy coating. Served on a stick',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite', 'on-a-stick'],
  },
  {
    name: 'Caramel Apple',
    vendor: 'Big Daddy\'s Candy Monster',
    description: 'Tangy apples covered in sweet caramel are the perfect way to enjoy the State Fair',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite', 'on-a-stick'],
  },
  {
    name: 'Fried Dough',
    vendor: 'Jack’s French Fries',
    description: 'Similar to elephant ears, this Fair treat is made by deep-frying a portion of risen yeast dough and then sprinkled with a variety of toppings',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Dough Nuggets',
    vendor: 'Tootsie’s Fried Dough',
    description: 'Soft pillows of fried dough – consider adding chocolate, apples or strawberries for extra deliciousness',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Sour Cream & Chive Fries',
    vendor: 'Saz’s Miller High Life Pavilion',
    description: 'Festival Famous Sour Cream and Chive Fries are served in a basket with a side of Saz’s Original Creamy Parmesan Dressing!',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'wisconsin-staple'],
  },
  {
    name: 'Mozzarella Marinara',
    vendor: 'Saz’s BBQ',
    description: 'Your choice of 2 or 4 sticks. Served with marinara sauce',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Jalapeño White Cheddar Cheese Basket',
    vendor: 'Hot Wisconsin Cheese',
    description: 'Jalapeño Pepper Cheese Basket Jalapeño cheddar cheese is battered and deep-fried to make this culinary dish. Served with your choice in dipping sauce',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Special of the Day Blue-Ribbon Cheese Sandwich',
    vendor: 'Real Wisconsin Cheese Grill',
    description: 'This sandwich will feature a blue-ribbon winning cheese from the 2022 Wisconsin State Fair Dairy Products Contest',
    fare: 'Meals',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'state-fair-favorite', 'wisconsin-staple'],
  },
  {
    name: 'Frozen Custard Sundae',
    vendor: 'Camp Bar',
    description: 'Choose from vanilla or chocolate custard and various toppings to build your own frozen custard sundae!',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Ice Cream Sundae',
    vendor: 'Cedar Crest Ice Cream',
    description: 'Traditional and adventurous toppings for your delight! Each location has various specialty sundaes',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite', 'wisconsin-staple'],
  },
  {
    name: 'Hawaiian Shaved Ice',
    vendor: 'Candy Factory',
    description: 'Available in flavors such as cherry, lemon lime, blue raspberry, grape, watermelon, tiger blood, banana, strawberry, Hawaiian sunrise, kiwi, blueberry, and pina colada',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Snow Cones',
    vendor: 'Big Daddy\'s Candy Monster',
    description: 'An ice dessert served in a cone and topped with your choice of flavored sugar syrup',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Heavenly Roasted Nuts',
    vendor: 'Freese’s Candy Shoppe',
    description: 'You can’t resist the heavenly aroma of roasting Almonds, Pecans and Cashews',
    fare: 'Snacks',
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Apple Cider Donut',
    vendor: 'Wisconsin Apple Growers Association',
    description: 'These donuts, made with Wisconsin apple cider, bring a taste of fall to the Best 11 Days of Summer',
    fare: 'Snacks',
    extraTags: ['core-catalog', 'wisconsin-staple'],
  },
  {
    name: 'Apple Pie',
    vendor: 'Wisconsin Apple Growers Association',
    description: 'Flaky, crispy crust filled with apples and cinnamon. Double-Crust or “Baked in a Bag” varieties',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'wisconsin-staple'],
  },
  {
    name: 'Honey Ice Cream On-a-Stick',
    vendor: 'Wisconsin Honey Producers Association',
    description: 'Grab your honey ice cream on-a-stick with nuts, chocolate, or butterscotch',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'wisconsin-staple', 'on-a-stick'],
  },
  {
    name: 'Maple Cotton Candy',
    vendor: 'Wisconsin Pure Maple Syrup',
    description: 'Fluffy, spun, maple-flavored sugar by the bag',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'wisconsin-staple', 'on-a-stick'],
  },
  {
    name: 'Gluten-Free Deep-Fried Cheese Curds',
    vendor: 'Keys Gluten-Free Fair Foods',
    description: 'Cheesy goodness comes in the form of certified gluten-free deep-fried cheese curds',
    fare: 'Snacks',
    dietaryTags: ['Gluten Free'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Gluten-Free Deep-Fried Corn Dog',
    vendor: 'Keys Gluten-Free Fair Foods',
    description: 'Bite into a certified gluten-free corn dog at State Fair!',
    fare: 'Meals',
    dietaryTags: ['Gluten Free'],
    extraTags: ['core-catalog', 'state-fair-favorite', 'on-a-stick'],
  },
  {
    name: 'Gluten-Free Original Funnel Cake',
    vendor: 'Keys Gluten-Free Fair Foods',
    description: 'Enjoy a , certified gluten-free deep-fried funnel cake',
    fare: 'Desserts',
    dietaryTags: ['Gluten Free'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Gluten-Free Deep-Fried Oreos',
    vendor: 'Keys Gluten-Free Fair Foods',
    description: 'Certified gluten-free deep-fried Oreos!',
    fare: 'Desserts',
    dietaryTags: ['Gluten Free'],
    extraTags: ['core-catalog', 'state-fair-favorite'],
  },
  {
    name: 'Corn Brat On-a-Stick',
    vendor: 'Adeline’s Corn',
    description: 'Brat dipped in corn dog battered, deep-fried and served on-a-stick',
    fare: 'Meals',
    extraTags: ['core-catalog', 'on-a-stick'],
  },
  {
    name: 'Bavarian-Style Soft Pretzel',
    vendor: 'Gourmet Pretzel & Chill',
    description: 'Slightly crunchy on the outside and soft in the middle',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog'],
  },
  {
    name: 'A Hunk A Hunk Fat Elvis Donut Ice Cream Sandwich',
    vendor: 'Badger Bites',
    description: 'A Hunk A Hunk Fat Elvis Donut Ice Cream Sandwich is a sweet and savory donut ice cream sandwich that would make The King proud.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Brandy Old Fashioned S’more On-a-Stick',
    vendor: 'Freese’s Candy Shoppe',
    description: 'This Freese’s Candy Shoppe classic treat has a grand twist! The Brandy Old Fashioned S’more On-a-Stick upgrades the classic whipped cream bar by infusing the flavors of the Wisconsin brandy old fashioned.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'past-sporkies', 'on-a-stick'],
  },
  {
    name: 'Buffalo Cheese Curd and Chicken Taco',
    vendor: 'Richie’s Cheese Curd Tacos',
    description: 'Buffalo flavored cheese curds from Ellsworth, WI paired with slices of grilled chicken in a fried flour tortilla. Topped with bleu cheese slaw',
    fare: 'Meals',
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Carnival Cooler',
    vendor: 'Tropics',
    description: 'The Carnival Cooler is a bright pink drink that tickles the tastebuds with a mix of watermelon, pickle juice, and lemonade.',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['core-catalog', 'past-drinkies'],
  },
  {
    name: 'Cool Ranch Doritos Pickle',
    vendor: 'Deep-Fried Mashed Potatoes On-a-Stick',
    description: 'Bite into the Cool Ranch Doritos Pickle! This large dill pickle is spiral-cut on-a-stick, rolled into crushed up Cool Ranch Doritos, and you guessed it, deep-fried.',
    fare: 'Snacks',
    extraTags: ['core-catalog', 'past-sporkies', 'on-a-stick'],
  },
  {
    name: 'Cotton Candy Lemonade',
    vendor: 'Saz’s Miller High Life Pavilion',
    description: 'Lemonade drizzled with blue cotton candy syrup and topped with a fluffy piece of blue cotton candy!',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['core-catalog', 'past-drinkies'],
  },
  {
    name: 'Dirty Pancakes',
    vendor: 'Buzzy Badger',
    description: 'The Dirty Pancakes is a playful take on a dirty soda that tastes like breakfast in a cup! Root beer is mixed with vanilla creamer and maple pancake syrup, brown sugar popping boba, and then topped with whipped cream.',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['core-catalog', 'past-drinkies'],
  },
  {
    name: 'Dubai Chocolate Strawberry Smoothie',
    vendor: 'Caribbean Smoothees',
    description: 'The Dubai Chocolate Strawberry Smoothie is a decadent blend of fruity, nutty, and rich dessert flavors in one strikingly beautiful drink.',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['core-catalog', 'past-drinkies'],
  },
  {
    name: 'Elote Corn Ribs',
    vendor: 'Tropics',
    description: 'Take the Midwest staple of corn on the cob, but add a little spice! The Elote Corn Ribs are made from corn on the cob with the cob acting as the “bone” of the corn “rib,” tossed in hickory smoked batter, and deep-fried.',
    fare: 'Meals',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Fairway Fusion',
    vendor: 'Old Fashioned Sipper Club',
    description: 'The Fairway Fusion takes a refreshing twist on a summer classic – the Arnold Palmer.',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['core-catalog', 'past-drinkies'],
  },
  {
    name: 'The Ferris Mule',
    vendor: 'Old Fashioned Sipper Club',
    description: 'The Ferris Mule is a non-alcoholic mule crafted with fresh blackberries, ginger beer, freshly squeezed lime juice, and agave nectar – all of which is hand shaken and poured over ice.',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['core-catalog', 'past-drinkies'],
  },
  {
    name: 'Fried Pickle Cheese Curd Tacos',
    vendor: 'Richie’s Cheese Curd Tacos',
    description: 'Who doesn’t love fried pickles? Would you say it is going too far to combine them with Cheese Curd Tacos? We think not! The Fried Pickle Cheese Curd Tacos is completely deep-fried with pickles sandwiched together with cr',
    fare: 'Meals',
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Glazed Donut Coffee Float',
    vendor: 'Fluffy’s Hand Cut Donuts',
    description: 'The Glazed Donut Coffee Float features rich glazed donut-infused iced coffee over creamy vanilla ice cream, topped with a golden glazed donut hole, and delicate glazed donut crumbles.',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['core-catalog', 'past-drinkies'],
  },
  {
    name: 'Gochujang Smashburger with Kimchi Bacon Jam',
    vendor: 'Blue Moon Tavern at the Park',
    description: 'Gochujang Smashburger with Kimchi Bacon Jam is a mouthwatering Korean-inspired burger bursting with heat, umami, and crunch.',
    fare: 'Meals',
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Island Slaw',
    vendor: 'Island Noodles',
    description: 'Best Tasting Award Winner at the 2013 Sporkies. Island coleslaw with pineapple, mandarin oranges, teriyaki chicken in a light Sriracha glaze topped with crushed Macadamia nuts',
    fare: 'Meals',
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Jalapeño Popper Hot Dog',
    vendor: 'Wild Dog Saloon',
    description: 'An all-beef hot dog wrapped in bacon and deep fried. Topped with cream cheese, cheddar cheese, and spicy jalapeños for a little kick. Drizzled with a sweet raspberry glaze',
    fare: 'Meals',
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Mexican Street Corn Pizza',
    vendor: 'Charlie’s Pizza',
    description: 'M exican Street Corn Pizza is a flavor fiesta inspired by the beloved flavors of elote .',
    fare: 'Meals',
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Purple Rain Refresher',
    vendor: 'Rock & Roll Beer Garden',
    description: 'I nspired by the glam and grit of rock legends, the Purple Rain Refresher is a show-stopping drink that captures the magic of a live show.',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['core-catalog', 'past-drinkies'],
  },
  {
    name: 'S’mores Churro Fries',
    vendor: 'Saz’s BBQ',
    description: 'S’mores Churro Fries turn your favorite campfire treat into a crispy, shareable dessert. Cinnamon-sugar churro fries are topped with gooey marshmallow cr e me, rich chocolate sauce, and crushed graham crackers.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Tropical Sunset',
    vendor: 'Deep-Fried Mashed Potatoes On-a-Stick',
    description: 'The Tropical Sunset is a sparkly twist on a favorite refreshing drink! This drink consists of jasmine green tea infused with strawberry, mango, and pineapple juice with 100% edible, FDA approved glitter.',
    allowBeverage: true,
    beverageCategory: 'Non-Alcoholic Drink',
    extraTags: ['core-catalog', 'past-drinkies'],
  },
  {
    name: 'Tropics Street Corn Nachos',
    vendor: 'Tropics',
    description: 'All of the flavors of the Mexican-style street corn in nacho form: grilled corn, mayo, cotija cheese, cilantro, cayenne and lime juice along with nacho chips and a creamy melted queso cheese',
    fare: 'Snacks',
    dietaryTags: ['Vegetarian'],
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Ube Butter Banana French Toast Lumpia',
    vendor: 'Lumpia City',
    description: 'Ube Butter Banana French Toast Lumpia puts a twist on a traditional favorite sweet lumpia flavor called Turon .',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Wisconsin Quesadilla',
    vendor: 'Mexican Grill',
    description: 'The Wisconsin Quesadilla is truly filled with the best of Wisconsin! Stuffed full of cheese curds, chunks of brats, grilled onions and peppers, and shredded cheese, this quesadilla is cooked to golden brown perfection an',
    fare: 'Meals',
    extraTags: ['core-catalog', 'past-sporkies'],
  },
  {
    name: 'Glickles',
    vendor: 'Pickle Barrel',
    description: 'Glitter-coated pickles.',
    fare: 'Snacks',
    extraTags: ['core-catalog', 'returning-listing'],
  },
  {
    name: 'Dill Dawg Dorito Bombs',
    vendor: 'Deep-Fried Mashed Potatoes On-a-Stick',
    description: 'Dill pickle and Doritos-inspired fried bombs.',
    fare: 'Snacks',
    extraTags: ['core-catalog', 'returning-listing'],
  },
  {
    name: 'Dubai Funnel Cake',
    vendor: 'Sweet Factory',
    description: 'Funnel cake with Dubai-chocolate-style toppings.',
    fare: 'Desserts',
    extraTags: ['core-catalog', 'returning-listing'],
  }
];
