import { bpItem, bpVendor } from "./ballpark-menu-builders";
import type { FoodItem, Vendor } from "./sample-data";

const TF = "tropicana-field";
const TFT = "Tropicana Field";
const BR = "truist-park";
const BRT = "Truist Park";
const GR = "guaranteed-rate-field";
const GRT = "Guaranteed Rate Field";
const OR = "oriole-park-at-camden-yards";
const ORT = "Oriole Park at Camden Yards";
const CP = "comerica-park";
const CPT = "Comerica Park";
const BS = "busch-stadium";
const BST = "Busch Stadium";

const alc = {
  itemType: "Alcoholic Drink" as const,
  alcoholic: true,
  ageRestricted: true
};

/** Wave 3 MLB concessions — Tropicana Field, Truist Park, Guaranteed Rate Field, Camden Yards, Comerica Park, Busch Stadium. */
export const wave3BallparkVendors: Vendor[] = [
  bpVendor(TF, "trop-epic-milkshakes", "Epic Milkshakes", "Field", "Section 107"),
  bpVendor(TF, "trop-twisted", "Twisted", "Outfield", "Budweiser Porch"),
  bpVendor(TF, "trop-budweiser-porch", "Budweiser Porch", "Outfield", "Center field"),
  bpVendor(TF, "trop-cubanos", "Cubanos", "Concourse", "1B Food Hall"),
  bpVendor(TF, "trop-maintenx-skydeck", "MaintenX SkyDeck", "Outfield", "Left field"),
  bpVendor(TF, "trop-melted", "Melted", "Outfield", "Budweiser Porch"),
  bpVendor(TF, "trop-colony-grill", "Colony Grill", "Concourse", "1B and 3B Food Halls"),
  bpVendor(TF, "trop-crabbeys-beachside", "Crabby’s Beachside Bites", "Field", "Section 144"),
  bpVendor(TF, "trop-bird-batter", "Bird & Batter", "Concourse", "1B and 3B Food Halls"),
  bpVendor(TF, "trop-pacific-counter", "Pacific Counter", "Outfield", "Center field"),
  bpVendor(TF, "trop-speakeasy-dex-club", "Speakeasy at DEX Home Plate Club", "Club", "Home plate club level"),
  bpVendor(TF, "trop-coppertail-brewing", "Coppertail Brewing Co.", "Concourse", "Multiple sections"),
  bpVendor(TF, "trop-ballpark-spirits", "Ballpark Spirits", "Field", "Section 117"),
  bpVendor(TF, "trop-shortstop-markets", "ShortStop Markets", "Upper / porch", "Upper level; Budweiser Porch"),
  bpVendor(TF, "trop-family-favorites", "Family Favorites", "Outfield", "Center field"),
  bpVendor(TF, "trop-gluten-free-stand", "Gluten-Free Stand", "Field", "Section 146"),

  bpVendor(BR, "braves-1871-grille", "1871 Grille", "Field", "Section 113"),
  bpVendor(BR, "braves-blooperito-stand", "Blooperito Stand", "Upper", "Sections 215, 239"),
  bpVendor(BR, "braves-coop-championship-chicken", "Coop’s Championship Chicken", "Field / upper", "Sections 138, 320"),
  bpVendor(BR, "braves-blue-moon-beer-garden", "Blue Moon Beer Garden", "Outfield", "Beer garden"),
  bpVendor(BR, "braves-tacos-mejor", "Tacos Mejor", "Field", "Section 152"),
  bpVendor(BR, "braves-freds-meat-bread", "Fred’s Meat & Bread", "Gate", "Chop House Gate"),
  bpVendor(BR, "braves-antico-pizza", "Antico Pizza", "Plaza", "The Battery and concourse"),
  bpVendor(BR, "braves-bell-street-burritos", "Bell Street Burritos", "Market", "Outfield Market"),
  bpVendor(BR, "braves-hf-burger", "H&F Burger", "Field", "Section 155"),
  bpVendor(BR, "braves-giving-kitchen", "Giving Kitchen", "Market", "Outfield Market", "Rotating chef stall; initial 2026 rotation starts with Bovino After Dark."),
  bpVendor(BR, "braves-chop-house", "The Chop House", "Outfield", "Right field"),
  bpVendor(BR, "braves-broadside-lager", "Broadside Lager", "Concourse", "Multiple locations"),
  bpVendor(BR, "braves-blue-run-spirits", "Blue Run Spirits", "Premium", "Premium clubs"),
  bpVendor(BR, "braves-dirty-sodas-mocktails", "Dirty Sodas & Mocktails", "Field / upper", "Sections 129, 313"),
  bpVendor(BR, "braves-superica", "Superica", "District", "The Battery Atlanta"),
  bpVendor(BR, "braves-garden-gun-club", "Garden & Gun Club", "District", "The Battery Atlanta"),
  bpVendor(BR, "braves-fat-tuesday", "Fat Tuesday", "District", "The Battery Atlanta"),

  bpVendor(GR, "gsox-chicago-bites", "Chicago Bites", "Upper", "Sections 320, 344"),
  bpVendor(GR, "gsox-campfire-milkshake", "Campfire Milkshake", "Field", "Section 159"),
  bpVendor(GR, "gsox-machete", "Machete", "Field", "Section 111"),
  bpVendor(GR, "gsox-gourmet-burgers", "Gourmet Burgers", "Field", "Section 126"),
  bpVendor(GR, "gsox-luckys", "Lucky’s", "Field", "Section 154"),
  bpVendor(GR, "gsox-beggars-pizza", "Beggars Pizza", "Concourse", "Multiple sections"),
  bpVendor(GR, "gsox-jibaritos", "Jibaritos", "Field", "Section 104"),
  bpVendor(GR, "gsox-la-esquinita-boricua", "La Esquinita Boricua", "Field", "Section 155"),
  bpVendor(GR, "gsox-buona-beef", "Buona Beef", "Concourse", "Multiple sections"),
  bpVendor(GR, "gsox-fusion", "Fusion", "Field", "Section 152"),
  bpVendor(GR, "gsox-coffee-cream", "Coffee & Cream", "Field", "Section 105"),
  bpVendor(GR, "gsox-leinenkugels-craft-lodge", "Leinenkugel’s Craft Lodge", "Field", "Section 107"),
  bpVendor(GR, "gsox-topo-chico-cantina", "Topo Chico Hard Seltzer Cantina", "Field", "Section 159"),
  bpVendor(GR, "gsox-miller-high-life-sky-lounge", "Miller High Life Sky Lounge", "Upper", "Sky lounge"),
  bpVendor(GR, "gsox-new-2026-brews", "New 2026 Brews", "Concourse", "Rotating taps"),
  bpVendor(GR, "gsox-canned-cocktail-locations", "Canned Cocktail Locations", "Concourse", "Various locations"),

  bpVendor(OR, "orioles-baltimore-seafood-house", "Baltimore Seafood House", "Field", "Section 120"),
  bpVendor(OR, "orioles-bleacher-grill", "Bleacher Grill", "Street", "Eutaw Street"),
  bpVendor(OR, "orioles-eutaw-street-butchery", "Eutaw Street Butchery", "Street", "Eutaw Street"),
  bpVendor(OR, "orioles-all-star-kitchen", "All-Star Kitchen", "Upper", "Sections 214, 256"),
  bpVendor(OR, "orioles-baltimore-chop", "Baltimore Chop", "Upper", "Section 226"),
  bpVendor(OR, "orioles-boogs-bbq", "Boog’s BBQ", "Street", "Eutaw Street"),
  bpVendor(OR, "orioles-jimmys-famous-seafood", "Jimmy’s Famous Seafood", "Field", "Section 120"),
  bpVendor(OR, "orioles-ekiben", "Ekiben", "Street", "Eutaw Street"),
  bpVendor(OR, "orioles-stuggys-gourmet-hot-dogs", "Stuggy’s Gourmet Hot Dogs", "Field", "Section 105"),
  bpVendor(OR, "orioles-sweet-graffiti-desserts", "Sweet Graffiti Desserts", "Upper", "Section 234"),
  bpVendor(OR, "orioles-charm-city-chicken-shacks", "Charm City Chicken Shacks", "Concourse", "Location varies"),
  bpVendor(OR, "orioles-deddles-mini-donuts", "Deddle’s Mini Donuts", "Street", "Eutaw Street"),
  bpVendor(OR, "orioles-birdland-kosher", "Birdland Kosher", "Field", "Section 83", "Star-K certified; closed Fridays and Saturdays."),
  bpVendor(OR, "orioles-amazon-just-walk-out", "Amazon Just Walk Out Markets", "Street / field", "Eutaw Street; Sections 17, 23, 35, 64"),
  bpVendor(OR, "orioles-roof-deck-bar", "Roof Deck Bar", "Outfield", "Center field"),
  bpVendor(OR, "orioles-camden-franks", "Camden Franks", "Concourse", "Value stands (multiple)"),

  bpVendor(CP, "tigers-big-cat-court", "Big Cat Court", "Concourse", "Big Cat Court"),
  bpVendor(CP, "tigers-hamtramck", "Hamtramck", "Field", "Section 122"),
  bpVendor(CP, "tigers-dessert-stands", "Dessert Stands", "Field / upper", "Sections 132, 340"),
  bpVendor(CP, "tigers-short-rib-stand", "Short Rib Stand", "Upper", "Section 328"),
  bpVendor(CP, "tigers-slows-bbq", "Slow’s BBQ", "Field", "Section 149"),
  bpVendor(CP, "tigers-berts-bbq", "Bert’s BBQ", "Field", "Section 133"),
  bpVendor(CP, "tigers-taqueria-el-rey", "Taqueria El Rey", "Field / concourse", "Section 119; Big Cat Court"),
  bpVendor(CP, "tigers-breadless", "Breadless", "Field", "Section 140"),
  bpVendor(CP, "tigers-fairway", "Fairway", "Field", "Section 151"),
  bpVendor(CP, "tigers-little-caesars", "Little Caesars", "Concourse", "Multiple sections"),
  bpVendor(CP, "tigers-guernsey", "Guernsey", "Field", "Section 119"),
  bpVendor(CP, "tigers-tiger-claws", "Tiger Claws", "Field", "Section 108"),
  bpVendor(CP, "tigers-flamin-hot-nachos", "Flamin’ Hot Nachos", "Field", "Sections 105, 129"),
  bpVendor(CP, "tigers-press-club", "The Press Club", "Club", "Press club level"),
  bpVendor(CP, "tigers-comerica-landing", "Comerica Landing", "Outfield", "Right field"),
  bpVendor(CP, "tigers-blue-moon-bistro", "Blue Moon Bistro", "Field", "Section 151"),
  bpVendor(CP, "tigers-chevrolet-pavilion", "Chevrolet Pavilion", "Concourse", "Pavilion"),
  bpVendor(CP, "tigers-michigan-craft-beer-package", "Michigan Craft Beer Package", "Concourse", "Retail / stands (varies)"),
  bpVendor(CP, "tigers-premium-bars", "Premium Bars", "Premium", "Club bars"),
  bpVendor(CP, "tigers-big-league-grills", "Big League Grills", "Field / upper", "Sections 108, 130, 213"),
  bpVendor(CP, "tigers-healthy-vegan", "Healthy & Vegan", "Field / upper", "Sections 119, 327"),

  bpVendor(BS, "cards-gashouse-grill", "Gashouse Grill", "Field", "Section 150"),
  bpVendor(BS, "cards-intentional-wok", "Intentional Wok", "Field", "Section 103"),
  bpVendor(BS, "cards-broadway-bbq", "Broadway BBQ", "Field", "Section 109"),
  bpVendor(BS, "cards-big-chicken", "Big Chicken", "Field / upper", "Sections 135, 358"),
  bpVendor(BS, "cards-dulce-pop", "Dulce Pop", "Concourse", "Sections 108, 152, 240, 446"),
  bpVendor(BS, "cards-made-in-the-lou", "Made in the Lou", "Field", "Section 146", "Rotating local lineup by date."),
  bpVendor(BS, "cards-mayo-ketchup-plantain-girl", "Mayo Ketchup by Plantain Girl", "Field", "Section 169"),
  bpVendor(BS, "cards-crumbl-cookies", "Crumbl Cookies", "Premium", "Section 136 and suites"),
  bpVendor(BS, "cards-freddys-frozen-custard", "Freddy’s Frozen Custard", "Upper", "Section 432"),
  bpVendor(BS, "cards-kohns-portable", "Kohn’s Portable", "Field", "Section 147"),
  bpVendor(BS, "cards-pop-fly-bar", "Pop Fly Bar", "Gate", "Gate 1", "Pop-up bar theme changes throughout season."),
  bpVendor(BS, "cards-budweiser-terrace", "Budweiser Terrace", "Outfield", "Right field"),
  bpVendor(BS, "cards-1764-craft-bar", "1764 Craft Bar", "Field", "Section 141"),
  bpVendor(BS, "cards-back-stop-bar", "Back Stop Bar", "Field", "Section 150"),
  bpVendor(BS, "cards-value-menu-stands", "Value Menu Stands", "Field / upper", "Sections 132, 162, 233, 446"),
  bpVendor(BS, "cards-coca-cola-unlimited", "Coca-Cola Unlimited", "Concourse", "Big Mac Land; Sections 271, 272")
];

export const wave3BallparkFoodItems: FoodItem[] = [
  bpItem(TF, TFT, "trop-epic-milkshakes", "trop-oreo-brownie-milkshake", "Oreo Brownie Milkshake", "DESSERT", "Chocolate soft-serve shake with crushed Oreo rim, brownie wedge, mini ice cream cone.", { location: "Section 107", sections: ["107"] }),
  bpItem(TF, TFT, "trop-twisted", "trop-sweet-pretzel-bites", "Sweet Pretzel Bites", "DESSERT", "Cinnamon sugar pretzel bites in souvenir baseball glove bowl with caramel and vanilla icing.", { location: "Budweiser Porch" }),
  bpItem(TF, TFT, "trop-budweiser-porch", "trop-98-pretzel-dog", "98 Pretzel Dog", "HOT_DOG", "Limited Nathan’s dog wrapped in pretzel dough with key lime pineapple mustard.", { location: "Center field" }),
  bpItem(TF, TFT, "trop-budweiser-porch", "trop-bud-porch-beer", "Beer", "DRINK", "Draft and packaged beer.", { ...alc, beverageStyle: "Beer", location: "Center field" }),
  bpItem(TF, TFT, "trop-cubanos", "trop-cubano-dog", "Cubano Dog", "HOT_DOG", "Hot dog with mojo pork, Swiss, pickles, mustard, pressed Cuban-style.", { location: "1B Food Hall" }),
  bpItem(TF, TFT, "trop-maintenx-skydeck", "trop-skyway-slider-trio", "Skyway Slider Trio", "SANDWICH", "Brisket, pulled pork, and hot chicken sliders.", { location: "Left field" }),
  bpItem(TF, TFT, "trop-maintenx-skydeck", "trop-all-inclusive-fare", "All-Inclusive Ballpark Fare", "OTHER", "SkyDeck inclusive food service (access rules vary).", { location: "Left field", tags: [TFT, "TODO: Confirm ticket / access for SkyDeck"] }),
  bpItem(TF, TFT, "trop-maintenx-skydeck", "trop-skydeck-beer-wine-soda", "Beer, Wine and Soda", "DRINK", "Inclusive beverage service on SkyDeck.", { ...alc, beverageStyle: "Other", location: "Left field" }),
  bpItem(TF, TFT, "trop-melted", "trop-short-rib-grilled-cheese", "Short Rib Grilled Cheese", "SANDWICH", "Short rib grilled cheese with cheddar, Swiss, Havarti, horseradish cream.", { location: "Budweiser Porch" }),
  bpItem(TF, TFT, "trop-colony-grill", "trop-hot-oil-pizza", "Hot Oil Pizza", "PIZZA", "Colony Grill hot oil thin-crust pizza.", { location: "1B and 3B Food Halls" }),
  bpItem(TF, TFT, "trop-crabbeys-beachside", "trop-gator-bites", "Gator Bites", "SEAFOOD", "Fried gator nuggets.", { location: "Section 144", sections: ["144"] }),
  bpItem(TF, TFT, "trop-crabbeys-beachside", "trop-coconut-shrimp", "Coconut Shrimp", "SEAFOOD", "Coconut-crusted shrimp.", { location: "Section 144", sections: ["144"] }),
  bpItem(TF, TFT, "trop-crabbeys-beachside", "trop-fried-grouper-sandwich", "Fried Grouper Sandwich", "SEAFOOD", "Fried grouper sandwich.", { location: "Section 144", sections: ["144"] }),
  bpItem(TF, TFT, "trop-bird-batter", "trop-korean-chicken-sandwich", "Korean Chicken Sandwich", "CHICKEN", "Korean-style fried chicken sandwich.", { location: "1B and 3B Food Halls" }),
  bpItem(TF, TFT, "trop-bird-batter", "trop-bird-batter-tenders", "Chicken Tenders", "CHICKEN", "Crispy chicken tenders.", { location: "1B and 3B Food Halls" }),
  bpItem(TF, TFT, "trop-pacific-counter", "trop-poke-bowl", "Poke Bowl", "SEAFOOD", "Build-your-own poke bowl.", { location: "Center field" }),
  bpItem(TF, TFT, "trop-pacific-counter", "trop-sushi-burrito", "Sushi Burrito", "SEAFOOD", "Sushi burrito wrap.", { location: "Center field" }),
  bpItem(TF, TFT, "trop-speakeasy-dex-club", "trop-speakeasy-premium-cocktails", "Premium Craft Cocktails", "DRINK", "DEX Home Plate Club craft cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Home plate club" }),
  bpItem(TF, TFT, "trop-speakeasy-dex-club", "trop-speakeasy-specialty-candy", "Specialty Candy Room", "DESSERT", "Premium candy selection.", { location: "Home plate club" }),
  bpItem(TF, TFT, "trop-coppertail-brewing", "trop-coppertail-beer-bat", "Beer Bat", "DRINK", "Beer served in souvenir bat vessel.", { ...alc, beverageStyle: "Beer", location: "Multiple sections" }),
  bpItem(TF, TFT, "trop-coppertail-brewing", "trop-free-dive-ipa", "Free Dive IPA", "DRINK", "Coppertail Free Dive IPA.", { ...alc, beverageStyle: "Beer", location: "Multiple sections" }),
  bpItem(TF, TFT, "trop-coppertail-brewing", "trop-night-swim-porter", "Night Swim Porter", "DRINK", "Coppertail Night Swim Porter.", { ...alc, beverageStyle: "Beer", location: "Multiple sections" }),
  bpItem(TF, TFT, "trop-ballpark-spirits", "trop-boozy-slushies", "Boozy Slushies", "DRINK", "Frozen cocktail slushies.", { ...alc, beverageStyle: "Cocktail", location: "Section 117", sections: ["117"] }),
  bpItem(TF, TFT, "trop-ballpark-spirits", "trop-spicy-mango-margarita", "Spicy Mango Margarita", "DRINK", "Spicy mango margarita.", { ...alc, beverageStyle: "Cocktail", location: "Section 117", sections: ["117"] }),
  bpItem(TF, TFT, "trop-shortstop-markets", "trop-shortstop-grab-drinks", "Grab-and-Go Drinks", "DRINK", "Bottles, cans, and cold cases.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Upper level; Budweiser Porch" }),
  bpItem(TF, TFT, "trop-shortstop-markets", "trop-shortstop-peanuts-snacks", "Peanuts and Snacks", "SNACK", "Grab-and-go peanuts and snacks.", { location: "Upper level; Budweiser Porch" }),
  bpItem(TF, TFT, "trop-family-favorites", "trop-value-hot-dog", "Value Hot Dog", "HOT_DOG", "Family value hot dog.", { location: "Center field" }),
  bpItem(TF, TFT, "trop-family-favorites", "trop-value-popcorn", "Value Popcorn", "SNACK", "Value popcorn.", { location: "Center field" }),
  bpItem(TF, TFT, "trop-family-favorites", "trop-value-soda", "Value Soda", "DRINK", "Value fountain soda.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Center field" }),
  bpItem(TF, TFT, "trop-gluten-free-stand", "trop-gf-chicken-tenders", "Gluten-Free Chicken Tenders", "GLUTEN_FREE", "Breaded GF tenders (verify prep).", { location: "Section 146", sections: ["146"], tags: [TFT, "TODO: Confirm dedicated fryer"] }),
  bpItem(TF, TFT, "trop-gluten-free-stand", "trop-gf-hot-dog", "Gluten-Free Hot Dog", "GLUTEN_FREE", "GF bun hot dog.", { location: "Section 146", sections: ["146"] }),
  bpItem(TF, TFT, "trop-gluten-free-stand", "trop-gf-snacks", "Gluten-Free Snacks", "GLUTEN_FREE", "Packaged GF snacks.", { location: "Section 146", sections: ["146"] }),

  bpItem(BR, BRT, "braves-1871-grille", "braves-the-bat-flip", "The Bat Flip", "BURGER", "Massive burger with four patties, short rib, pork belly, cheese, fried egg.", { location: "Section 113", sections: ["113"] }),
  bpItem(BR, BRT, "braves-1871-grille", "braves-the-baffle", "The Baffle", "SANDWICH", "Waffle-pressed bun with smoked brisket and truffle cheese sauce.", { location: "Section 113", sections: ["113"] }),
  bpItem(BR, BRT, "braves-blooperito-stand", "braves-blooperito", "Blooperito", "TACOS", "Deep-fried burrito with chipotle beef, cotija, pico.", { location: "Sections 215, 239", sections: ["215", "239"] }),
  bpItem(BR, BRT, "braves-coop-championship-chicken", "braves-peach-dingers", "Peach Dingers", "DESSERT", "Peach cobbler egg rolls with caramel drizzle.", { location: "Sections 138, 320", sections: ["138", "320"] }),
  bpItem(BR, BRT, "braves-blue-moon-beer-garden", "braves-the-walk-off", "The Walk-Off", "SANDWICH", "Puff pastry pocket with marinara, pork meatballs, mozzarella.", { location: "Beer garden" }),
  bpItem(BR, BRT, "braves-blue-moon-beer-garden", "braves-blue-moon-beer", "Blue Moon Beer", "DRINK", "Blue Moon draft and bottles.", { ...alc, beverageStyle: "Beer", location: "Beer garden" }),
  bpItem(BR, BRT, "braves-blue-moon-beer-garden", "braves-fox-bros-bbq", "Fox Bros. Bar-B-Q", "BBQ", "Fox Bros. BBQ plates and sandwiches (beer garden).", { location: "Beer garden" }),
  bpItem(BR, BRT, "braves-tacos-mejor", "braves-al-pastor-taco", "Al Pastor Taco", "TACOS", "Al pastor street taco.", { location: "Section 152", sections: ["152"] }),
  bpItem(BR, BRT, "braves-tacos-mejor", "braves-ribeye-taco", "Ribeye Taco", "TACOS", "Ribeye taco.", { location: "Section 152", sections: ["152"] }),
  bpItem(BR, BRT, "braves-freds-meat-bread", "braves-freds-ribeye-cheesesteak", "Ribeye Cheesesteak", "SANDWICH", "Fred’s ribeye cheesesteak.", { location: "Chop House Gate" }),
  bpItem(BR, BRT, "braves-freds-meat-bread", "braves-freds-garlic-fries", "Garlic Fries", "SNACK", "Garlic fries side.", { location: "Chop House Gate" }),
  bpItem(BR, BRT, "braves-antico-pizza", "braves-antico-neapolitan", "Neapolitan Pizza", "PIZZA", "Wood-fired Neapolitan pizza.", { location: "The Battery and concourse" }),
  bpItem(BR, BRT, "braves-bell-street-burritos", "braves-bell-street-burrito", "Burrito", "TACOS", "Build-your-own burrito.", { location: "Outfield Market" }),
  bpItem(BR, BRT, "braves-bell-street-burritos", "braves-bell-street-quesadilla", "Quesadilla", "TACOS", "Grilled quesadilla.", { location: "Outfield Market" }),
  bpItem(BR, BRT, "braves-hf-burger", "braves-hf-burger-item", "H&F Burger", "BURGER", "Holeman & Finch double-stack burger.", { location: "Section 155", sections: ["155"] }),
  bpItem(BR, BRT, "braves-giving-kitchen", "braves-giving-spicy-korean-sausage", "Spicy Korean Sausage", "HOT_DOG", "Rotating chef stall sausage (2026 opens with Bovino After Dark per park notes).", { location: "Outfield Market", tags: [BRT, "Rotating vendor"] }),
  bpItem(BR, BRT, "braves-chop-house", "braves-skyline-slugger-cocktail", "Skyline Slugger Cocktail", "DRINK", "Chop House signature cocktail.", { ...alc, beverageStyle: "Cocktail", location: "Right field" }),
  bpItem(BR, BRT, "braves-broadside-lager", "braves-austin-riley-broadside-lager", "Austin Riley’s Broadside Lager", "DRINK", "Braves player tie-in lager.", { ...alc, beverageStyle: "Beer", location: "Multiple" }),
  bpItem(BR, BRT, "braves-blue-run-spirits", "braves-blue-run-premium-whiskey", "Premium Whiskey", "DRINK", "Premium whiskey pours.", { ...alc, beverageStyle: "Other", location: "Premium clubs" }),
  bpItem(BR, BRT, "braves-dirty-sodas-mocktails", "braves-dirty-soda", "Dirty Soda", "DRINK", "Custom dirty soda build.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Sections 129, 313", sections: ["129", "313"] }),
  bpItem(BR, BRT, "braves-dirty-sodas-mocktails", "braves-mocktail", "Mocktail", "DRINK", "Non-alcoholic mocktail.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Sections 129, 313", sections: ["129", "313"] }),
  bpItem(BR, BRT, "braves-superica", "braves-superica-tex-mex", "Tex-Mex", "TACOS", "Superica Tex-Mex plates.", { location: "The Battery Atlanta" }),
  bpItem(BR, BRT, "braves-garden-gun-club", "braves-garden-gun-southern-menu", "Southern Lounge Menu", "OTHER", "Garden & Gun lounge plates.", { location: "The Battery Atlanta" }),
  bpItem(BR, BRT, "braves-garden-gun-club", "braves-garden-gun-cocktails", "Cocktails", "DRINK", "Lounge cocktails.", { ...alc, beverageStyle: "Cocktail", location: "The Battery Atlanta" }),
  bpItem(BR, BRT, "braves-fat-tuesday", "braves-fat-tuesday-daiquiri", "Frozen Daiquiri", "DRINK", "Fat Tuesday frozen daiquiri.", { ...alc, beverageStyle: "Cocktail", location: "The Battery Atlanta" }),

  bpItem(GR, GRT, "gsox-chicago-bites", "gsox-all-star-chicago-lineup", "All-Star Chicago Lineup", "HOT_DOG", "Sampler with Chicago dog, kielbasa, Italian beef, popcorn.", { location: "Sections 320, 344", sections: ["320", "344"] }),
  bpItem(GR, GRT, "gsox-chicago-bites", "gsox-mushroom-al-pastor-taco", "Mushroom Al Pastor Street Taco", "VEGAN", "Vegan mushroom al pastor street taco.", { location: "Sections 320, 344", sections: ["320", "344"] }),
  bpItem(GR, GRT, "gsox-chicago-bites", "gsox-elote", "Elote", "SNACK", "Street corn cup.", { location: "Sections 320, 344", sections: ["320", "344"] }),
  bpItem(GR, GRT, "gsox-campfire-milkshake", "gsox-campfire-milkshake-2", "Campfire Milkshake 2.0", "DESSERT", "Shareable marshmallow, graham, chocolate milkshake.", { location: "Section 159", sections: ["159"] }),
  bpItem(GR, GRT, "gsox-machete", "gsox-the-machete", "The Machete", "TACOS", "Foot-long quesadilla with chicken chorizo, Oaxaca cheese, orange salsa.", { location: "Section 111", sections: ["111"] }),
  bpItem(GR, GRT, "gsox-machete", "gsox-vegetarian-machete", "Vegetarian Machete", "VEGAN", "Plant-based machete build.", { location: "Section 111", sections: ["111"] }),
  bpItem(GR, GRT, "gsox-gourmet-burgers", "gsox-two-bagger-smash", "Two Bagger Smash Burger", "BURGER", "Beef patty with Vienna Beef sausage, guacamole, jalapeños, poblano slaw.", { location: "Section 126", sections: ["126"] }),
  bpItem(GR, GRT, "gsox-luckys", "gsox-rainbow-bubble-waffle", "Rainbow Bubble Waffle", "DESSERT", "Bubble waffle dessert.", { location: "Section 154", sections: ["154"] }),
  bpItem(GR, GRT, "gsox-luckys", "gsox-tonkatsu-dog", "Tonkatsu Dog", "HOT_DOG", "Japanese-style tonkatsu dog.", { location: "Section 154", sections: ["154"] }),
  bpItem(GR, GRT, "gsox-luckys", "gsox-papas-freedom-korean-dog", "Papas Freedom Korean Dog", "HOT_DOG", "Korean-style loaded dog.", { location: "Section 154", sections: ["154"] }),
  bpItem(GR, GRT, "gsox-luckys", "gsox-soba-noodle-stir-fry", "Soba Noodle Stir Fry", "OTHER", "Soba noodle stir fry bowl.", { location: "Section 154", sections: ["154"] }),
  bpItem(GR, GRT, "gsox-beggars-pizza", "gsox-southside-supreme", "Southside Supreme Pizza", "PIZZA", "Southside supreme pie.", { location: "Multiple sections" }),
  bpItem(GR, GRT, "gsox-jibaritos", "gsox-steak-jibarito", "Steak Jibarito", "SANDWICH", "Steak jibarito on plantain buns.", { location: "Section 104", sections: ["104"] }),
  bpItem(GR, GRT, "gsox-la-esquinita-boricua", "gsox-puerto-rican-rice-bowl", "Puerto Rican Rice Bowl", "OTHER", "Rice bowl with island sides.", { location: "Section 155", sections: ["155"] }),
  bpItem(GR, GRT, "gsox-buona-beef", "gsox-buona-italian-beef", "Italian Beef Sandwich", "SANDWICH", "Chicago Italian beef dipped.", { location: "Multiple sections" }),
  bpItem(GR, GRT, "gsox-fusion", "gsox-arepa-burger", "Arepa Burger", "BURGER", "Arepa-shell burger fusion.", { location: "Section 152", sections: ["152"] }),
  bpItem(GR, GRT, "gsox-coffee-cream", "gsox-soft-serve", "Soft Serve", "DESSERT", "Soft serve cone or cup.", { location: "Section 105", sections: ["105"] }),
  bpItem(GR, GRT, "gsox-coffee-cream", "gsox-blended-coffee", "Blended Coffee", "DRINK", "Frozen blended coffee.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Section 105", sections: ["105"] }),
  bpItem(GR, GRT, "gsox-coffee-cream", "gsox-gourmet-hot-drinks", "Gourmet Hot Drinks", "DRINK", "Hot chocolate, coffee, seasonal drinks.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Section 105", sections: ["105"] }),
  bpItem(GR, GRT, "gsox-leinenkugels-craft-lodge", "gsox-going-yard-souvenir-cup", "Going Yard Souvenir Cup", "DRINK", "Beer in souvenir cup.", { ...alc, beverageStyle: "Beer", location: "Section 107", sections: ["107"] }),
  bpItem(GR, GRT, "gsox-topo-chico-cantina", "gsox-topo-hard-seltzer", "Hard Seltzer", "DRINK", "Topo Chico Hard Seltzer lineup.", { ...alc, beverageStyle: "Seltzer", location: "Section 159", sections: ["159"] }),
  bpItem(GR, GRT, "gsox-miller-high-life-sky-lounge", "gsox-miller-high-life-beer", "Miller High Life Beer", "DRINK", "Miller High Life draft and bottles.", { ...alc, beverageStyle: "Beer", location: "Sky lounge" }),
  bpItem(GR, GRT, "gsox-new-2026-brews", "gsox-cruz-blanca-beer", "Cruz Blanca Beer", "DRINK", "Local craft beer.", { ...alc, beverageStyle: "Beer", location: "Rotating taps" }),
  bpItem(GR, GRT, "gsox-new-2026-brews", "gsox-brutalist-brewing-beer", "Brutalist Brewing Beer", "DRINK", "Local craft beer.", { ...alc, beverageStyle: "Beer", location: "Rotating taps" }),
  bpItem(GR, GRT, "gsox-new-2026-brews", "gsox-homewood-brewing-beer", "Homewood Brewing Beer", "DRINK", "Local craft beer.", { ...alc, beverageStyle: "Beer", location: "Rotating taps" }),
  bpItem(GR, GRT, "gsox-canned-cocktail-locations", "gsox-surfside-vodka-iced-tea", "Surfside Vodka Iced Tea", "DRINK", "Canned RTD cocktail.", { ...alc, beverageStyle: "Cocktail", location: "Various locations" }),
  bpItem(GR, GRT, "gsox-canned-cocktail-locations", "gsox-minute-maid-spiked", "Minute Maid Spiked Drink", "DRINK", "Spiked lemonade / tea RTD.", { ...alc, beverageStyle: "Cocktail", location: "Various locations" }),

  bpItem(OR, ORT, "orioles-baltimore-seafood-house", "orioles-crab-smash-tacos", "Crab Smash Tacos", "SEAFOOD", "Crab cake tacos grilled with crab consommé and cilantro lime crema.", { location: "Section 120", sections: ["120"] }),
  bpItem(OR, ORT, "orioles-bleacher-grill", "orioles-big-scrap-burger", "Big Scrap Burger", "BURGER", "Smashed patties with crispy scrapple, cheese, Brick Sauce.", { location: "Eutaw Street" }),
  bpItem(OR, ORT, "orioles-eutaw-street-butchery", "orioles-bmore-yak", "B’MORE Yak", "OTHER", "Udon, grilled shrimp, onions, hot dogs, soy-dashi gravy, egg.", { location: "Eutaw Street" }),
  bpItem(OR, ORT, "orioles-all-star-kitchen", "orioles-kats-japanese-cheesesteak", "Kat’s Japanese Cheesesteak", "SANDWICH", "Japanese-style cheesesteak.", { location: "Sections 214, 256", sections: ["214", "256"] }),
  bpItem(OR, ORT, "orioles-baltimore-chop", "orioles-rotating-carved-sandwich", "Rotating Carved Sandwich", "SANDWICH", "Carved sandwich of the day.", { location: "Section 226", sections: ["226"] }),
  bpItem(OR, ORT, "orioles-boogs-bbq", "orioles-boogs-pit-beef", "Pit Beef Sandwich", "BBQ", "Sliced pit beef sandwich.", { location: "Eutaw Street" }),
  bpItem(OR, ORT, "orioles-boogs-bbq", "orioles-boogs-smoked-turkey", "Smoked Turkey Sandwich", "BBQ", "Smoked turkey sandwich.", { location: "Eutaw Street" }),
  bpItem(OR, ORT, "orioles-boogs-bbq", "orioles-boogs-pulled-pork", "Pulled Pork Sandwich", "BBQ", "Pulled pork sandwich.", { location: "Eutaw Street" }),
  bpItem(OR, ORT, "orioles-jimmys-famous-seafood", "orioles-true-blue-crab-cake-sando", "True Blue Crab Cake Sando", "SEAFOOD", "Jumbo lump crab cake sandwich.", { location: "Section 120", sections: ["120"] }),
  bpItem(OR, ORT, "orioles-jimmys-famous-seafood", "orioles-crab-dip-fries", "Crab Dip Fries", "SEAFOOD", "Crab dip over fries.", { location: "Section 120", sections: ["120"] }),
  bpItem(OR, ORT, "orioles-ekiben", "orioles-ekiben-neighborhood-bird", "Neighborhood Bird", "CHICKEN", "Ekiben fried chicken sandwich.", { location: "Eutaw Street" }),
  bpItem(OR, ORT, "orioles-stuggys-gourmet-hot-dogs", "orioles-stuggys-crab-mac-dog", "Crab Mac Dog", "HOT_DOG", "Hot dog topped with crab mac.", { location: "Section 105", sections: ["105"] }),
  bpItem(OR, ORT, "orioles-sweet-graffiti-desserts", "orioles-mini-dubai-chocolate-bars", "Mini Dubai Chocolate Bars", "DESSERT", "Trending Dubai-style chocolate bars.", { location: "Section 234", sections: ["234"] }),
  bpItem(OR, ORT, "orioles-sweet-graffiti-desserts", "orioles-baltimore-fudge-cookies", "Baltimore Fudge Cookies", "DESSERT", "Fudge-stuffed cookies.", { location: "Section 234", sections: ["234"] }),
  bpItem(OR, ORT, "orioles-sweet-graffiti-desserts", "orioles-dulce-whoopie-pies", "Dulce de Leche Whoopie Pies", "DESSERT", "Whoopie pies with dulce de leche.", { location: "Section 234", sections: ["234"] }),
  bpItem(OR, ORT, "orioles-charm-city-chicken-shacks", "orioles-baltimore-banana-pudding", "Baltimore Banana Pudding", "DESSERT", "Banana pudding cup.", { location: "Concourse", tags: [ORT, "TODO: Map exact shack sections when published"] }),
  bpItem(OR, ORT, "orioles-deddles-mini-donuts", "orioles-mini-donut-bucket", "Mini Donut Bucket", "DESSERT", "Warm mini donuts in bucket.", { location: "Eutaw Street" }),
  bpItem(OR, ORT, "orioles-birdland-kosher", "orioles-kosher-hot-pastrami", "Hot Pastrami on Rye", "SANDWICH", "Hot pastrami sandwich.", { location: "Section 83", sections: ["83"] }),
  bpItem(OR, ORT, "orioles-birdland-kosher", "orioles-kosher-knish", "Potato Knish", "OTHER", "Potato knish.", { location: "Section 83", sections: ["83"] }),
  bpItem(OR, ORT, "orioles-birdland-kosher", "orioles-kosher-chicken-nuggets", "Chicken Nuggets", "CHICKEN", "Kosher chicken nuggets.", { location: "Section 83", sections: ["83"] }),
  bpItem(OR, ORT, "orioles-amazon-just-walk-out", "orioles-jwo-grab-drinks", "Grab-and-Go Drinks", "DRINK", "Self-checkout cold drinks.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Eutaw Street; Sections 17, 23, 35, 64", sections: ["17", "23", "35", "64"] }),
  bpItem(OR, ORT, "orioles-amazon-just-walk-out", "orioles-natty-boh", "Natty Boh", "DRINK", "National Bohemian beer.", { ...alc, beverageStyle: "Beer", location: "Eutaw Street; Sections 17, 23, 35, 64", sections: ["17", "23", "35", "64"] }),
  bpItem(OR, ORT, "orioles-amazon-just-walk-out", "orioles-heavy-seas-loose-cannon", "Heavy Seas Loose Cannon", "DRINK", "Heavy Seas IPA.", { ...alc, beverageStyle: "Beer", location: "Eutaw Street; Sections 17, 23, 35, 64", sections: ["17", "23", "35", "64"] }),
  bpItem(OR, ORT, "orioles-roof-deck-bar", "orioles-roof-craft-cocktails", "Craft Cocktails", "DRINK", "Roof deck cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Center field" }),
  bpItem(OR, ORT, "orioles-roof-deck-bar", "orioles-roof-beer-bats", "Beer Bats", "DRINK", "Beer served in souvenir bat.", { ...alc, beverageStyle: "Beer", location: "Center field" }),
  bpItem(OR, ORT, "orioles-camden-franks", "orioles-birdland-value-hot-dog", "Birdland Value Hot Dog", "HOT_DOG", "Value hot dog.", { location: "Value stands" }),
  bpItem(OR, ORT, "orioles-camden-franks", "orioles-birdland-value-popcorn", "Birdland Value Popcorn", "SNACK", "Value popcorn.", { location: "Value stands" }),
  bpItem(OR, ORT, "orioles-camden-franks", "orioles-birdland-value-beer", "Birdland Value Beer", "DRINK", "Value beer pour.", { ...alc, beverageStyle: "Beer", location: "Value stands" }),

  bpItem(CP, CPT, "tigers-big-cat-court", "tigers-tiger-tail", "Tiger Tail", "HOT_DOG", "Footlong corn dog with cheese powder, Coney chili, orange mustard, onions.", { location: "Big Cat Court" }),
  bpItem(CP, CPT, "tigers-big-cat-court", "tigers-grilled-cheese-sonoran-dog", "Grilled Cheese Sonoran Dog", "HOT_DOG", "Sonoran-style dog with grilled cheese components.", { location: "Big Cat Court" }),
  bpItem(CP, CPT, "tigers-hamtramck", "tigers-pierogi-nacho", "Pierogi Nacho", "OTHER", "Pierogies with queso, kielbasa, onions, sauerkraut.", { location: "Section 122", sections: ["122"] }),
  bpItem(CP, CPT, "tigers-dessert-stands", "tigers-dubai-chocolate-strawberries", "Dubai Chocolate Strawberries", "DESSERT", "Strawberries with Dubai-style chocolate and toppings.", { location: "Sections 132, 340", sections: ["132", "340"] }),
  bpItem(CP, CPT, "tigers-short-rib-stand", "tigers-smoked-bone-in-short-rib-sandwich", "Smoked Bone-In Short Rib Sandwich", "BBQ", "Bone-in short rib sandwich.", { location: "Section 328", sections: ["328"] }),
  bpItem(CP, CPT, "tigers-slows-bbq", "tigers-orange-terror-sausage", "Orange Terror Sausage", "HOT_DOG", "Slow’s smoked sausage.", { location: "Section 149", sections: ["149"] }),
  bpItem(CP, CPT, "tigers-berts-bbq", "tigers-mac-cheetos", "Mac & Cheetos", "OTHER", "Mac and cheese with Cheetos crunch.", { location: "Section 133", sections: ["133"] }),
  bpItem(CP, CPT, "tigers-berts-bbq", "tigers-smoked-turkey-leg", "Smoked Turkey Leg", "BBQ", "Smoked turkey leg.", { location: "Section 133", sections: ["133"] }),
  bpItem(CP, CPT, "tigers-taqueria-el-rey", "tigers-el-rey-street-tacos", "Street Tacos", "TACOS", "Street taco platter.", { location: "Section 119; Big Cat Court", sections: ["119"] }),
  bpItem(CP, CPT, "tigers-taqueria-el-rey", "tigers-el-rey-sonoran-dog", "Sonoran Dog", "HOT_DOG", "Bacon-wrapped Sonoran dog build.", { location: "Section 119; Big Cat Court", sections: ["119"] }),
  bpItem(CP, CPT, "tigers-breadless", "tigers-sweet-heat-chicken-wrap", "Sweet Heat Chicken Ranch Wrap", "VEGAN", "Breadless wrap; verify ingredients seasonally.", { location: "Section 140", sections: ["140"] }),
  bpItem(CP, CPT, "tigers-fairway", "tigers-steak-frites", "Steak Frites", "SANDWICH", "Steak frites plate.", { location: "Section 151", sections: ["151"] }),
  bpItem(CP, CPT, "tigers-fairway", "tigers-legacy-steak-sandwich", "Legacy Steak Sandwich", "SANDWICH", "Legacy steak sandwich.", { location: "Section 151", sections: ["151"] }),
  bpItem(CP, CPT, "tigers-little-caesars", "tigers-little-caesars-deep-dish-slice", "Deep-Dish Super Slice", "PIZZA", "Detroit-style deep-dish slice.", { location: "Multiple sections" }),
  bpItem(CP, CPT, "tigers-guernsey", "tigers-orange-sherbet", "Orange Sherbet", "DESSERT", "Orange sherbet scoop.", { location: "Section 119", sections: ["119"] }),
  bpItem(CP, CPT, "tigers-tiger-claws", "tigers-tiger-claws-snack", "Tiger Claws", "SNACK", "Seasoned snack mix.", { location: "Section 108", sections: ["108"] }),
  bpItem(CP, CPT, "tigers-flamin-hot-nachos", "tigers-flamin-hot-nachos-item", "Flamin’ Hot Nachos", "TACOS", "Flamin’ Hot Cheetos loaded nachos.", { location: "Sections 105, 129", sections: ["105", "129"] }),
  bpItem(CP, CPT, "tigers-press-club", "tigers-press-club-detroit-buffet", "Detroit-Centric Buffet", "OTHER", "Press Club buffet (ticketed).", { location: "Press club", tags: [CPT, "TODO: Confirm club access"] }),
  bpItem(CP, CPT, "tigers-press-club", "tigers-press-club-cocktails", "Craft Cocktails", "DRINK", "Press Club cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Press club" }),
  bpItem(CP, CPT, "tigers-comerica-landing", "tigers-bases-loaded-beast", "Bases Loaded Beast", "HOT_DOG", "Loaded footlong specialty dog.", { location: "Right field" }),
  bpItem(CP, CPT, "tigers-blue-moon-bistro", "tigers-bmb-miller-lite-happy-hour", "Miller Lite Happy Hour Beer", "DRINK", "Happy hour Miller Lite.", { ...alc, beverageStyle: "Beer", location: "Section 151", sections: ["151"] }),
  bpItem(CP, CPT, "tigers-blue-moon-bistro", "tigers-bmb-happy-hour-hot-dog", "Happy Hour Hot Dog", "HOT_DOG", "Happy hour hot dog.", { location: "Section 151", sections: ["151"] }),
  bpItem(CP, CPT, "tigers-chevrolet-pavilion", "tigers-chev-happy-hour-beer", "Happy Hour Beer", "DRINK", "Pavilion happy hour beer.", { ...alc, beverageStyle: "Beer", location: "Pavilion" }),
  bpItem(CP, CPT, "tigers-chevrolet-pavilion", "tigers-chev-happy-hour-hot-dog", "Happy Hour Hot Dog", "HOT_DOG", "Pavilion happy hour dog.", { location: "Pavilion" }),
  bpItem(CP, CPT, "tigers-michigan-craft-beer-package", "tigers-bells-two-hearted", "Bell’s Two Hearted Ale", "DRINK", "Bell’s Two Hearted.", { ...alc, beverageStyle: "Beer", location: "Retail / stands" }),
  bpItem(CP, CPT, "tigers-michigan-craft-beer-package", "tigers-founders-all-day", "Founders All Day IPA", "DRINK", "Founders All Day IPA.", { ...alc, beverageStyle: "Beer", location: "Retail / stands" }),
  bpItem(CP, CPT, "tigers-michigan-craft-beer-package", "tigers-bells-oberon", "Bell’s Oberon", "DRINK", "Bell’s Oberon wheat ale.", { ...alc, beverageStyle: "Beer", location: "Retail / stands" }),
  bpItem(CP, CPT, "tigers-premium-bars", "tigers-patron-reposado", "Patrón Reposado", "DRINK", "Premium tequila pour.", { ...alc, beverageStyle: "Other", location: "Premium bars" }),
  bpItem(CP, CPT, "tigers-premium-bars", "tigers-angels-envy", "Angel’s Envy", "DRINK", "Premium bourbon pour.", { ...alc, beverageStyle: "Other", location: "Premium bars" }),
  bpItem(CP, CPT, "tigers-big-league-grills", "tigers-313-tuesday-hot-dog", "313 Tuesday Hot Dog", "HOT_DOG", "Tuesday value dog.", { location: "Sections 108, 130, 213", sections: ["108", "130", "213"] }),
  bpItem(CP, CPT, "tigers-big-league-grills", "tigers-313-tuesday-water", "313 Tuesday Water", "DRINK", "Tuesday value bottled water.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Sections 108, 130, 213", sections: ["108", "130", "213"] }),
  bpItem(CP, CPT, "tigers-big-league-grills", "tigers-313-tuesday-soda", "313 Tuesday Soda", "DRINK", "Tuesday value soda.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Sections 108, 130, 213", sections: ["108", "130", "213"] }),
  bpItem(CP, CPT, "tigers-big-league-grills", "tigers-313-tuesday-chips", "313 Tuesday Chips", "SNACK", "Tuesday value chips.", { location: "Sections 108, 130, 213", sections: ["108", "130", "213"] }),
  bpItem(CP, CPT, "tigers-big-league-grills", "tigers-313-value-meal", "Value Meal", "OTHER", "Bundled value meal.", { location: "Sections 108, 130, 213", sections: ["108", "130", "213"] }),
  bpItem(CP, CPT, "tigers-healthy-vegan", "tigers-impossible-burger", "Impossible Burger", "VEGAN", "Plant-based Impossible patty.", { location: "Sections 119, 327", sections: ["119", "327"] }),
  bpItem(CP, CPT, "tigers-healthy-vegan", "tigers-veggie-dog", "Veggie Dog", "VEGAN", "Plant-based veggie dog.", { location: "Sections 119, 327", sections: ["119", "327"] }),

  bpItem(BS, BST, "cards-gashouse-grill", "cards-fried-gooey-butter-cake", "Fried Gooey Butter Cake", "DESSERT", "St. Louis-style fried gooey butter cake.", { location: "Section 150", sections: ["150"] }),
  bpItem(BS, BST, "cards-intentional-wok", "cards-birria-ramen-bowl", "Birria Ramen Bowl", "OTHER", "Birria consommé ramen bowl.", { location: "Section 103", sections: ["103"] }),
  bpItem(BS, BST, "cards-broadway-bbq", "cards-hot-dog-burnt-ends", "Hot Dog Burnt Ends", "BBQ", "Smoked hot dog burnt ends.", { location: "Section 109", sections: ["109"] }),
  bpItem(BS, BST, "cards-broadway-bbq", "cards-broadway-brisket-sandwich", "Brisket Sandwich", "BBQ", "Sliced brisket sandwich.", { location: "Section 109", sections: ["109"] }),
  bpItem(BS, BST, "cards-broadway-bbq", "cards-broadway-pulled-pork", "Pulled Pork Sandwich", "BBQ", "Pulled pork sandwich.", { location: "Section 109", sections: ["109"] }),
  bpItem(BS, BST, "cards-big-chicken", "cards-big-chicken-waffles", "Big Chicken & Waffles", "CHICKEN", "Shaquille O’Neal’s Big Chicken with waffles.", { location: "Sections 135, 358", sections: ["135", "358"] }),
  bpItem(BS, BST, "cards-dulce-pop", "cards-fruit-popsicle", "Fruit Popsicle", "DESSERT", "Fruit ice pop.", { location: "Sections 108, 152, 240, 446", sections: ["108", "152", "240", "446"] }),
  bpItem(BS, BST, "cards-dulce-pop", "cards-cream-popsicle", "Cream Popsicle", "DESSERT", "Cream-based popsicle.", { location: "Sections 108, 152, 240, 446", sections: ["108", "152", "240", "446"] }),
  bpItem(BS, BST, "cards-made-in-the-lou", "cards-made-kanoa-hawaiian", "Kanoa’s Hawaiian Grill Item", "OTHER", "Rotating Hawaiian plate (menu by date).", { location: "Section 146", sections: ["146"], tags: [BST, "Rotating vendor"] }),
  bpItem(BS, BST, "cards-made-in-the-lou", "cards-made-kbop-korean", "Kbop Korean Comfort Food", "OTHER", "Rotating Korean comfort bowl.", { location: "Section 146", sections: ["146"], tags: [BST, "Rotating vendor"] }),
  bpItem(BS, BST, "cards-made-in-the-lou", "cards-made-fattened-caf-filipino", "Fattened Caf Filipino BBQ", "BBQ", "Rotating Filipino BBQ plate.", { location: "Section 146", sections: ["146"], tags: [BST, "Rotating vendor"] }),
  bpItem(BS, BST, "cards-made-in-the-lou", "cards-made-taste-d-burger-stl", "Taste-D-Burger STL", "BURGER", "Rotating STL smash burger.", { location: "Section 146", sections: ["146"], tags: [BST, "Rotating vendor"] }),
  bpItem(BS, BST, "cards-made-in-the-lou", "cards-made-gulf-shores-seafood", "Gulf Shores Seafood", "SEAFOOD", "Rotating Gulf seafood special.", { location: "Section 146", sections: ["146"], tags: [BST, "Rotating vendor"] }),
  bpItem(BS, BST, "cards-mayo-ketchup-plantain-girl", "cards-mayo-ketchup-cubano", "Cubano Sandwich", "SANDWICH", "Pressed Cubano.", { location: "Section 169", sections: ["169"] }),
  bpItem(BS, BST, "cards-mayo-ketchup-plantain-girl", "cards-mayo-ketchup-empanadas", "Empanadas", "SNACK", "Baked empanadas.", { location: "Section 169", sections: ["169"] }),
  bpItem(BS, BST, "cards-mayo-ketchup-plantain-girl", "cards-mayo-ketchup-maduros", "Maduros", "SNACK", "Sweet fried plantains.", { location: "Section 169", sections: ["169"] }),
  bpItem(BS, BST, "cards-crumbl-cookies", "cards-crumbl-stadium-only-cookie", "Stadium-Only Cookie", "DESSERT", "Rotating Crumbl stadium-exclusive cookie.", { location: "Section 136 and suites", sections: ["136"] }),
  bpItem(BS, BST, "cards-freddys-frozen-custard", "cards-freddys-steakburger", "Steakburger", "BURGER", "Freddy’s steakburger.", { location: "Section 432", sections: ["432"] }),
  bpItem(BS, BST, "cards-freddys-frozen-custard", "cards-freddys-turtle-concrete", "Signature Turtle Concrete", "DESSERT", "Turtle concrete with custard.", { location: "Section 432", sections: ["432"] }),
  bpItem(BS, BST, "cards-kohns-portable", "cards-kohns-killer-pastrami", "Killer Pastrami Sandwich", "SANDWICH", "Kohn’s pastrami sandwich.", { location: "Section 147", sections: ["147"] }),
  bpItem(BS, BST, "cards-kohns-portable", "cards-kohns-kosher-hot-dog", "Kosher Hot Dog", "HOT_DOG", "Kosher beef hot dog.", { location: "Section 147", sections: ["147"] }),
  bpItem(BS, BST, "cards-pop-fly-bar", "cards-pop-fly-themed-cocktails", "Themed Cocktails", "DRINK", "Seasonal themed cocktails (theme rotates).", { ...alc, beverageStyle: "Cocktail", location: "Gate 1", tags: [BST, "TODO: Align cocktail names with current theme"] }),
  bpItem(BS, BST, "cards-budweiser-terrace", "cards-bud-terrace-beer", "Beer", "DRINK", "Terrace draft beer.", { ...alc, beverageStyle: "Beer", location: "Right field" }),
  bpItem(BS, BST, "cards-1764-craft-bar", "cards-1764-urban-chestnut", "Urban Chestnut Beer", "DRINK", "Urban Chestnut draft.", { ...alc, beverageStyle: "Beer", location: "Section 141", sections: ["141"] }),
  bpItem(BS, BST, "cards-1764-craft-bar", "cards-1764-4-hands", "4 Hands Beer", "DRINK", "4 Hands Brewing draft.", { ...alc, beverageStyle: "Beer", location: "Section 141", sections: ["141"] }),
  bpItem(BS, BST, "cards-1764-craft-bar", "cards-1764-schlafly", "Schlafly Beer", "DRINK", "Schlafly draft.", { ...alc, beverageStyle: "Beer", location: "Section 141", sections: ["141"] }),
  bpItem(BS, BST, "cards-back-stop-bar", "cards-cardinals-punch-carafe", "Cardinals Punch Carafe", "DRINK", "Large-format punch carafe.", { ...alc, beverageStyle: "Cocktail", location: "Section 150", sections: ["150"] }),
  bpItem(BS, BST, "cards-back-stop-bar", "cards-back-stop-domestic-beer", "Domestic Beer", "DRINK", "Domestic draft and cans.", { ...alc, beverageStyle: "Beer", location: "Section 150", sections: ["150"] }),
  bpItem(BS, BST, "cards-value-menu-stands", "cards-value-hot-dog", "Value Hot Dog", "HOT_DOG", "Value hot dog.", { location: "Sections 132, 162, 233, 446", sections: ["132", "162", "233", "446"] }),
  bpItem(BS, BST, "cards-value-menu-stands", "cards-value-soda", "Value Soda", "DRINK", "Value fountain soda.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Sections 132, 162, 233, 446", sections: ["132", "162", "233", "446"] }),
  bpItem(BS, BST, "cards-value-menu-stands", "cards-value-popcorn", "Value Popcorn", "SNACK", "Value popcorn.", { location: "Sections 132, 162, 233, 446", sections: ["132", "162", "233", "446"] }),
  bpItem(BS, BST, "cards-value-menu-stands", "cards-value-nachos", "Value Nachos", "SNACK", "Value nachos.", { location: "Sections 132, 162, 233, 446", sections: ["132", "162", "233", "446"] }),
  bpItem(BS, BST, "cards-value-menu-stands", "cards-value-water", "Value Water", "DRINK", "Value bottled water.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Sections 132, 162, 233, 446", sections: ["132", "162", "233", "446"] }),
  bpItem(BS, BST, "cards-coca-cola-unlimited", "cards-coke-unlimited-hot-dogs", "Unlimited Hot Dogs", "HOT_DOG", "All-you-can-eat hot dogs (ticketed sections).", { location: "Big Mac Land; Sections 271, 272", sections: ["271", "272"], tags: [BST, "TODO: Confirm ticket / section access"] }),
  bpItem(BS, BST, "cards-coca-cola-unlimited", "cards-coke-unlimited-nachos", "Unlimited Nachos", "SNACK", "All-you-can-eat nachos (ticketed sections).", { location: "Big Mac Land; Sections 271, 272", sections: ["271", "272"], tags: [BST, "TODO: Confirm ticket / section access"] }),
  bpItem(BS, BST, "cards-coca-cola-unlimited", "cards-coke-unlimited-tenders", "Unlimited Chicken Tenders", "CHICKEN", "All-you-can-eat tenders (ticketed sections).", { location: "Big Mac Land; Sections 271, 272", sections: ["271", "272"], tags: [BST, "TODO: Confirm ticket / section access"] }),
  bpItem(BS, BST, "cards-coca-cola-unlimited", "cards-coke-unlimited-fountain", "Unlimited Coca-Cola Products", "DRINK", "Fountain refills on Coca-Cola products (ticketed sections).", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Big Mac Land; Sections 271, 272", sections: ["271", "272"], tags: [BST, "TODO: Confirm ticket / section access"] })
];
