import { bpItem, bpVendor } from "./ballpark-menu-builders";
import type { FoodItem, Vendor } from "./sample-data";

const PNC = "pnc-park";
const PNCT = "PNC Park";
const DAI = "daikin-park";
const DAIT = "Daikin Park";
const GLF = "globe-life-field";
const GLFT = "Globe Life Field";
const TMP = "t-mobile-park";
const TMPT = "T-Mobile Park";
const AMF = "american-family-field";
const AMFT = "American Family Field";

const alc = {
  itemType: "Alcoholic Drink" as const,
  alcoholic: true,
  ageRestricted: true
};

/** Wave 4 MLB concessions — PNC Park, Daikin Park, Globe Life Field, T-Mobile Park, American Family Field. */
export const wave4BallparkVendors: Vendor[] = [
  bpVendor(PNC, "pnc-cannonball", "Cannonball", "Field", "Section 146"),
  bpVendor(PNC, "pnc-deli-dogs", "Deli Dogs", "Field", "Section 135"),
  bpVendor(PNC, "pnc-chicken-on-the-hill", "Chicken on the Hill", "Field", "Section 144"),
  bpVendor(PNC, "pnc-homeplate-market", "Homeplate Market", "Field", "Section 118"),
  bpVendor(PNC, "pnc-primanti-bros", "Primanti Bros.", "Field", "Section 110"),
  bpVendor(PNC, "pnc-mannys-bbq", "Manny’s BBQ", "Outfield", "Center field Riverwalk"),
  bpVendor(PNC, "pnc-chickies-and-petes", "Chickie’s & Pete’s", "Concourse", "Sections 115, 132, 310"),
  bpVendor(PNC, "pnc-caliente-pizza-draft-house", "Caliente Pizza & Draft House", "Concourse", "Multiple sections"),
  bpVendor(PNC, "pnc-nutella-beignets", "Nutella Beignets", "Field", "Sections 144, 146"),
  bpVendor(PNC, "pnc-frozen-spoon", "Frozen Spoon", "Concourse", "Sections 107, 119, 144"),
  bpVendor(PNC, "pnc-miller-lite-beer-bat-stands", "Miller Lite Beer Bat Stands", "Concourse", "Multiple locations", "TODO: Map exact stand sections when published."),
  bpVendor(PNC, "pnc-fastball-souvenir-cup-stands", "Fastball Souvenir Cup Stands", "Concourse", "Multiple locations", "TODO: Confirm cup program (draft vs fountain) by location."),
  bpVendor(PNC, "pnc-fat-heads-bullpen-bar", "Fat Head’s Bullpen Bar", "Outfield", "Center field"),
  bpVendor(PNC, "pnc-cinderlands-corner-bar", "Cinderlands Corner Bar", "Gate / rotunda", "Left field rotunda"),
  bpVendor(PNC, "pnc-miller-lite-landing", "Miller Lite Landing", "Outfield", "Center field"),
  bpVendor(PNC, "pnc-surfside-skull-bar", "Surfside Skull Bar", "Lounge", "Left field lounge"),
  bpVendor(PNC, "pnc-walk-thru-brew", "Walk-Thru Brew", "Field", "Section 130"),
  bpVendor(PNC, "pnc-empanadas", "Empanadas", "Field", "Section 136"),
  bpVendor(PNC, "pnc-market-stands", "Market Stands", "Concourse", "Multiple locations", "TODO: Confirm which market stands carry plant-based burger."),

  bpVendor(DAI, "daikin-brisket-donuts", "Brisket Donuts", "Field / upper", "Sections 134, 409"),
  bpVendor(DAI, "daikin-banh-mi-dog-stands", "Banh Mi Dog Stands", "Concourse", "Sections 113, 129, 155, 416, 427"),
  bpVendor(DAI, "daikin-the-onion-station", "The Onion Station", "Concourse", "Atrium; Section 106"),
  bpVendor(DAI, "daikin-crawlache", "Crawlache", "Concourse", "Sections 113, 427"),
  bpVendor(DAI, "daikin-maple-brisket-wafflewich", "Maple Brisket Wafflewich", "Field", "Section 109"),
  bpVendor(DAI, "daikin-whataburger", "Whataburger", "Field", "Section 156"),
  bpVendor(DAI, "daikin-crust-city-pizza", "Crust City Pizza", "Concourse", "Sections 116, 153, 411, 429"),
  bpVendor(DAI, "daikin-coffee-and-cocktails", "Coffee & Cocktails", "Field", "Section 106"),
  bpVendor(DAI, "daikin-el-tiempo-cantina", "El Tiempo Cantina", "Upper", "Section 256"),
  bpVendor(DAI, "daikin-el-tiempo-margarita-bar", "El Tiempo Margarita Bar", "Field", "Sections 109, 156"),
  bpVendor(DAI, "daikin-the-butcher", "The Butcher", "Concourse", "Sections 105, 116, 152, 408"),
  bpVendor(DAI, "daikin-taqueria-arandas", "Taqueria Arandas", "Concourse", "Sections 154, 420"),
  bpVendor(DAI, "daikin-pluckers-wing-bar", "Pluckers Wing Bar", "Field", "Section 156"),
  bpVendor(DAI, "daikin-chick-fil-a", "Chick-fil-A", "Concourse", "Multiple sections", "Closed Sundays (chain policy)."),
  bpVendor(DAI, "daikin-strosrita-stands", "StrosRita Stands", "Concourse", "Sections 106, 114, 128"),
  bpVendor(DAI, "daikin-saint-arnold-bar", "Saint Arnold Bar", "Field", "Section 104"),
  bpVendor(DAI, "daikin-stros-barrel-select", "Stros Barrel Select", "Premium", "Location not listed in source", "TODO: Confirm bar / club footprint vs general concourse."),
  bpVendor(DAI, "daikin-karbach-love-street-bar", "Karbach Love Street Bar", "Field", "Section 119"),
  bpVendor(DAI, "daikin-value-stands", "Value Stands", "Concourse", "Multiple locations", "TODO: Map exact value stand sections."),
  bpVendor(DAI, "daikin-19th-hole", "19th Hole", "Outfield", "Center field"),

  bpVendor(GLF, "glf-9th-inning-rally-sombrero", "9th Inning Rally Sombrero", "Field", "Section 132"),
  bpVendor(GLF, "glf-the-pig-kahuna", "The Pig Kahuna", "Field", "Section 125"),
  bpVendor(GLF, "glf-hawwt-dawwg", "Hawwt Dawwg", "Field", "Section 105"),
  bpVendor(GLF, "glf-texas-ribeye-sandwich", "Texas Ribeye Sandwich", "Field", "Section 121"),
  bpVendor(GLF, "glf-high-steaks-nachos", "High Steaks Nachos", "Field", "Section 124"),
  bpVendor(GLF, "glf-boomstick-stands", "Boomstick Stands", "Concourse", "Texas 24-inch stands"),
  bpVendor(GLF, "glf-chicken-tender-helmet", "Chicken Tender Helmet", "Field", "Section 126"),
  bpVendor(GLF, "glf-hurtado-barbecue", "Hurtado Barbecue", "Field", "Section 141"),
  bpVendor(GLF, "glf-whataburger", "Whataburger", "Field", "Section 105"),
  bpVendor(GLF, "glf-golden-chick", "Golden Chick", "Field", "Section 128"),
  bpVendor(GLF, "glf-pluckers-wing-bar", "Pluckers Wing Bar", "Field", "Section 131"),
  bpVendor(GLF, "glf-arlington-eats", "Arlington Eats", "Field", "Section 142", "Rotating local minority-owned businesses."),
  bpVendor(GLF, "glf-dirty-sodas", "Dirty Sodas", "Field", "Section 126"),
  bpVendor(GLF, "glf-beer-bat-stands", "Beer Bat Stands", "Concourse", "Sections 110, 134, 215"),
  bpVendor(GLF, "glf-sky-porch", "Sky Porch", "Upper", "Section 201"),
  bpVendor(GLF, "glf-7-eleven-slurpees", "7-Eleven Slurpees", "Concourse", "Sections 101, 205"),
  bpVendor(GLF, "glf-teremana-bar", "Teremana Bar", "Field", "Section 134"),
  bpVendor(GLF, "glf-dollar-ice-cream-sunday-stands", "Dollar Ice Cream Sunday Stands", "Concourse", "Sections 12, 121, 213"),
  bpVendor(GLF, "glf-farmers-fridge", "Farmer’s Fridge", "Concourse", "Sections 103, 124"),
  bpVendor(GLF, "glf-texas-tamale-torta-stand", "Texas Tamale Torta Stand", "Concourse", "Location not listed in source", "TODO: Confirm stand section(s)."),
  bpVendor(GLF, "glf-major-concession-hubs", "Major Concession Hubs", "Concourse", "Various hubs", "TODO: Confirm which hubs advertise GF bun option."),

  bpVendor(TMP, "tmobile-ferry-boat-stands", "Ferry Boat Stands", "Concourse", "Multiple sections", "TODO: Map ferry boat stand sections."),
  bpVendor(TMP, "tmobile-salt-and-straw", "Salt & Straw", "Field / upper", "Sections 111, 328"),
  bpVendor(TMP, "tmobile-nakagawa-sushi", "Nakagawa Sushi", "Field", "Section 132"),
  bpVendor(TMP, "tmobile-tamari-bar", "Tamari Bar", "Field", "Section 133"),
  bpVendor(TMP, "tmobile-specialty-churros", "Specialty Churros", "Concourse", "Sections 143, 319, 333"),
  bpVendor(TMP, "tmobile-piroshky-piroshky", "Piroshky Piroshky", "Field", "Section 132"),
  bpVendor(TMP, "tmobile-el-rinconsito", "El Rinconsito", "Outfield", "The Pen"),
  bpVendor(TMP, "tmobile-rolling-smoke-bbq", "Rolling Smoke BBQ", "Upper", "Section 313"),
  bpVendor(TMP, "tmobile-moto-pizza", "MOTO Pizza", "Upper", "Section 314"),
  bpVendor(TMP, "tmobile-marination", "Marination", "Outfield / field", "The Pen; Section 119"),
  bpVendor(TMP, "tmobile-ivars", "Ivar’s", "Concourse", "Multiple sections"),
  bpVendor(TMP, "tmobile-hemplers", "Hempler’s", "Concourse", "Multiple sections"),
  bpVendor(TMP, "tmobile-ballard-pizza", "Ballard Pizza", "Outfield / field", "The Pen; Section 132"),
  bpVendor(TMP, "tmobile-way-back-crab-shack", "The Way Back Crab Shack", "Terrace", "Section 187"),
  bpVendor(TMP, "tmobile-the-pen", "The Pen", "Outfield", "Center field"),
  bpVendor(TMP, "tmobile-coca-cola-fan-deck", "Coca-Cola Fan Deck", "Upper", "Section 249"),
  bpVendor(TMP, "tmobile-secret-cocktail-door", "Secret Cocktail Door", "Field", "100 level", "TODO: Confirm exact door / bar access rules."),
  bpVendor(TMP, "tmobile-mariners-value-beer", "Mariners Value Beer", "Field / upper", "Sections 105, 128, 141, 218"),
  bpVendor(TMP, "tmobile-gluten-free-stand", "Gluten-Free Stand", "Field", "Section 132"),

  bpVendor(AMF, "amfam-fair-foods-stand", "Fair Foods Stand", "Field", "Section 125"),
  bpVendor(AMF, "amfam-third-street-market-hall-annex", "3rd Street Market Hall Annex", "Loge", "Loge level"),
  bpVendor(AMF, "amfam-bebe-zito", "Bebe Zito", "Concourse", "Location not listed in source", "TODO: Confirm stand location vs 3rd Street Market Hall Annex overlap."),
  bpVendor(AMF, "amfam-the-sweets-stand", "The Sweets Stand", "Concourse", "Location not listed in source", "TODO: Confirm section(s)."),
  bpVendor(AMF, "amfam-kompali-tacos", "Kompali Tacos", "Concourse", "Location not listed in source", "TODO: Confirm section(s)."),
  bpVendor(AMF, "amfam-anytime-arepa", "Anytime Arepa", "Concourse", "Location not listed in source", "TODO: Confirm section(s)."),
  bpVendor(AMF, "amfam-the-alley-food-truck-park", "The Alley Food Truck Park", "Loge", "Left field loge"),
  bpVendor(AMF, "amfam-k-and-ls-bbq", "K&L’s BBQ", "Loge", "The Alley Food Truck Park"),
  bpVendor(AMF, "amfam-chuchos-red-tacos", "Chuchos Red Tacos", "Loge", "The Alley Food Truck Park"),
  bpVendor(AMF, "amfam-hidden-kitchen-mke", "Hidden Kitchen MKE", "Loge", "The Alley Food Truck Park"),
  bpVendor(AMF, "amfam-leinenkugels-barrel-yard", "J. Leinenkugel’s Barrel Yard", "Outfield", "Left field"),
  bpVendor(AMF, "amfam-johnsonville-sausages", "Johnsonville Sausages", "Concourse", "Full Count stands", "TODO: Map Full Count stand sections."),
  bpVendor(AMF, "amfam-ballpark-staples", "Ballpark Staples", "Concourse", "Multiple locations", "TODO: Confirm which staples stands carry these items."),
  bpVendor(AMF, "amfam-uw-credit-union-plaza", "UW Credit Union Plaza", "Plaza", "Outdoor plaza", "Opening June 2026 per source."),
  bpVendor(AMF, "amfam-x-golf", "X-Golf", "Outfield", "Left field"),
  bpVendor(AMF, "amfam-casamigos-patio", "Casamigos Patio", "Outfield", "Right field corner"),
  bpVendor(AMF, "amfam-wisconsin-craft-stand", "Wisconsin Craft Stand", "Concourse", "Multiple locations", "TODO: Map exact craft stand locations.")
];

export const wave4BallparkFoodItems: FoodItem[] = [
  bpItem(PNC, PNCT, "pnc-cannonball", "pnc-heavy-hitter-dog", "Heavy Hitter Dog", "HOT_DOG", "Footlong hot dog with cornbread coating, mustard, pico de gallo, served in a souvenir baseball bat boat.", { location: "Section 146", sections: ["146"] }),
  bpItem(PNC, PNCT, "pnc-cannonball", "pnc-dessert-pierogi", "Dessert Pierogi", "DESSERT", "Sweet cheese-filled pierogi.", { location: "Section 146", sections: ["146"] }),
  bpItem(PNC, PNCT, "pnc-deli-dogs", "pnc-boricua-dog", "Boricua Dog", "HOT_DOG", "Puerto Rico-inspired dog with sofrito beef, kraut, mustard, cheese, ketchup, braised onions, potato sticks.", { location: "Section 135", sections: ["135"] }),
  bpItem(PNC, PNCT, "pnc-chicken-on-the-hill", "pnc-coop-puppy", "Coop Puppy", "CHICKEN", "Sweet tea-brined fried chicken sandwich with braised onions, ranch, lettuce.", { location: "Section 144", sections: ["144"] }),
  bpItem(PNC, PNCT, "pnc-chicken-on-the-hill", "pnc-nashville-hot-chicken", "Nashville Hot Chicken", "CHICKEN", "Nashville hot chicken serving.", { location: "Section 144", sections: ["144"] }),
  bpItem(PNC, PNCT, "pnc-chicken-on-the-hill", "pnc-chicken-biscuit", "Chicken Biscuit", "CHICKEN", "Fried chicken on a biscuit.", { location: "Section 144", sections: ["144"] }),
  bpItem(PNC, PNCT, "pnc-homeplate-market", "pnc-chipped-ham-fries", "Chipped Ham Fries", "SNACK", "Fries with Pittsburgh chipped ham, cheddar sauce, garlic butter.", { location: "Section 118", sections: ["118"] }),
  bpItem(PNC, PNCT, "pnc-homeplate-market", "pnc-kettle-nachos", "Kettle Nachos", "SNACK", "Kettle chips with kielbasa, onions, pico, sriracha ketchup.", { location: "Section 118", sections: ["118"] }),
  bpItem(PNC, PNCT, "pnc-homeplate-market", "pnc-cold-pierogi-salad", "Cold Pierogi Salad", "OTHER", "Pierogies in sour cream dressing with onions, garlic-ranch, cheddar, bacon.", { location: "Section 118", sections: ["118"] }),
  bpItem(PNC, PNCT, "pnc-homeplate-market", "pnc-homeplate-gf-snacks", "Gluten-Free Snacks", "GLUTEN_FREE", "Packaged and prepared GF snacks (verify prep).", { location: "Section 118", sections: ["118"], tags: [PNCT, "TODO: Confirm dedicated prep"] }),
  bpItem(PNC, PNCT, "pnc-homeplate-market", "pnc-homeplate-salad", "Salad", "VEGAN", "Salad option from market.", { location: "Section 118", sections: ["118"] }),
  bpItem(PNC, PNCT, "pnc-homeplate-market", "pnc-berry-parfait", "Berry Parfait", "DESSERT", "Berry yogurt parfait.", { location: "Section 118", sections: ["118"] }),
  bpItem(PNC, PNCT, "pnc-primanti-bros", "pnc-primanti-sandwich", "Primanti Sandwich", "SANDWICH", "Grilled meat, cheese, fries, coleslaw inside the bread.", { location: "Section 110", sections: ["110"] }),
  bpItem(PNC, PNCT, "pnc-mannys-bbq", "pnc-mannys-pulled-pork", "Pulled Pork Sandwich", "BBQ", "Pulled pork sandwich from Riverwalk stand.", { location: "Center field Riverwalk" }),
  bpItem(PNC, PNCT, "pnc-mannys-bbq", "pnc-mannys-topped-mini-pierogies", "Topped Mrs. T’s Mini Pierogies", "OTHER", "Mini pierogies with toppings.", { location: "Center field Riverwalk" }),
  bpItem(PNC, PNCT, "pnc-chickies-and-petes", "pnc-crabfries", "Crabfries", "SNACK", "Crabfries seasoned fries.", { location: "Sections 115, 132, 310", sections: ["115", "132", "310"] }),
  bpItem(PNC, PNCT, "pnc-chickies-and-petes", "pnc-chickies-cheesesteak", "Cheesesteak", "SANDWICH", "Philly-style cheesesteak.", { location: "Sections 115, 132, 310", sections: ["115", "132", "310"] }),
  bpItem(PNC, PNCT, "pnc-caliente-pizza-draft-house", "pnc-caliente-tavern-slice", "Tavern-Style Pizza Slice", "PIZZA", "Tavern-style thin slice.", { location: "Multiple sections" }),
  bpItem(PNC, PNCT, "pnc-nutella-beignets", "pnc-nutella-beignets-item", "Nutella Beignets", "DESSERT", "Nutella-filled beignets.", { location: "Sections 144, 146", sections: ["144", "146"] }),
  bpItem(PNC, PNCT, "pnc-frozen-spoon", "pnc-ice-cream-souvenir-helmet", "Ice Cream Souvenir Helmet", "DESSERT", "Soft serve in souvenir helmet.", { location: "Sections 107, 119, 144", sections: ["107", "119", "144"] }),
  bpItem(PNC, PNCT, "pnc-miller-lite-beer-bat-stands", "pnc-miller-lite-beer-bat", "Miller Lite Beer Bat", "DRINK", "Miller Lite in souvenir bat vessel.", { ...alc, beverageStyle: "Beer", location: "Multiple locations" }),
  bpItem(PNC, PNCT, "pnc-fastball-souvenir-cup-stands", "pnc-fastball-souvenir-cup-drink", "Fastball Souvenir Cup Drink", "DRINK", "Souvenir cup beverage program.", { ...alc, beverageStyle: "Beer", location: "Multiple locations", tags: [PNCT, "TODO: Confirm NA vs alcoholic cup options"] }),
  bpItem(PNC, PNCT, "pnc-fat-heads-bullpen-bar", "pnc-fat-heads-local-beer", "Fat Head’s Local Beer", "DRINK", "Fat Head’s local draft lineup.", { ...alc, beverageStyle: "Beer", location: "Center field" }),
  bpItem(PNC, PNCT, "pnc-fat-heads-bullpen-bar", "pnc-bumble-berry-beer", "Bumble Berry Beer", "DRINK", "Bumble Berry honey-blueberry ale.", { ...alc, beverageStyle: "Beer", location: "Center field" }),
  bpItem(PNC, PNCT, "pnc-fat-heads-bullpen-bar", "pnc-head-hunter-beer", "Head Hunter Beer", "DRINK", "Head Hunter IPA.", { ...alc, beverageStyle: "Beer", location: "Center field" }),
  bpItem(PNC, PNCT, "pnc-cinderlands-corner-bar", "pnc-cinderlands-craft-beer", "Cinderlands Craft Beer", "DRINK", "Cinderlands draft beer.", { ...alc, beverageStyle: "Beer", location: "Left field rotunda" }),
  bpItem(PNC, PNCT, "pnc-cinderlands-corner-bar", "pnc-cinderlands-specialty-cocktails", "Specialty Cocktails", "DRINK", "Rotating craft cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Left field rotunda" }),
  bpItem(PNC, PNCT, "pnc-miller-lite-landing", "pnc-miller-lite-landing-beer", "Miller Lite Beer", "DRINK", "Miller Lite draft and cans.", { ...alc, beverageStyle: "Beer", location: "Center field" }),
  bpItem(PNC, PNCT, "pnc-surfside-skull-bar", "pnc-surfside-iced-tea-vodka", "Surfside Iced Tea Vodka", "DRINK", "Surfside vodka iced tea cocktail.", { ...alc, beverageStyle: "Cocktail", location: "Left field lounge" }),
  bpItem(PNC, PNCT, "pnc-surfside-skull-bar", "pnc-skull-souvenir-cocktail", "Skull Souvenir Cocktail", "DRINK", "Skull souvenir vessel cocktail.", { ...alc, beverageStyle: "Cocktail", location: "Left field lounge" }),
  bpItem(PNC, PNCT, "pnc-walk-thru-brew", "pnc-walk-thru-cold-beer", "Cold Beer", "DRINK", "Grab-and-go cold beer.", { ...alc, beverageStyle: "Beer", location: "Section 130", sections: ["130"] }),
  bpItem(PNC, PNCT, "pnc-walk-thru-brew", "pnc-walk-thru-grab-snacks", "Grab-and-Go Snacks", "SNACK", "Grab-and-go snacks at walk-thru.", { location: "Section 130", sections: ["130"] }),
  bpItem(PNC, PNCT, "pnc-empanadas", "pnc-chicken-empanada", "Chicken Empanada", "SNACK", "Baked chicken empanada.", { location: "Section 136", sections: ["136"] }),
  bpItem(PNC, PNCT, "pnc-empanadas", "pnc-vegan-empanada", "Vegan Empanada", "VEGAN", "Plant-based empanada.", { location: "Section 136", sections: ["136"] }),
  bpItem(PNC, PNCT, "pnc-market-stands", "pnc-market-plant-based-burger", "Plant-Based Burger", "VEGAN", "Plant-based burger at select market stands.", { location: "Multiple locations", tags: [PNCT, "TODO: Confirm stands"] }),

  bpItem(DAI, DAIT, "daikin-brisket-donuts", "daikin-brisket-donuts-item", "Brisket Donuts", "BBQ", "Deep-fried brisket shaped like a donut with BBQ sauce and mac & cheese.", { location: "Sections 134, 409", sections: ["134", "409"] }),
  bpItem(DAI, DAIT, "daikin-banh-mi-dog-stands", "daikin-banh-mi-dog", "Banh Mi Dog", "HOT_DOG", "Footlong dog with daikon slaw, bacon, cilantro, sriracha aioli.", { location: "Sections 113, 129, 155, 416, 427", sections: ["113", "129", "155", "416", "427"] }),
  bpItem(DAI, DAIT, "daikin-the-onion-station", "daikin-h-town-hot-boomin-onion", "H-Town Hot Boomin Onion", "SNACK", "Fried onion with popcorn chicken, hot honey aioli, H-Town hot sauce.", { location: "Atrium; Section 106", sections: ["106"] }),
  bpItem(DAI, DAIT, "daikin-the-onion-station", "daikin-bbq-pork-boomin-onion", "BBQ Pork Burnt End Boomin Onion", "BBQ", "Fried onion with pork burnt ends and queso blanco.", { location: "Atrium; Section 106", sections: ["106"] }),
  bpItem(DAI, DAIT, "daikin-crawlache", "daikin-crawlache-item", "Crawlache", "HOT_DOG", "Slovacek’s pepper jack sausage on a stick wrapped in puff pastry with honey mustard.", { location: "Sections 113, 427", sections: ["113", "427"] }),
  bpItem(DAI, DAIT, "daikin-maple-brisket-wafflewich", "daikin-maple-brisket-wafflewich-item", "Maple Brisket Wafflewich", "BBQ", "Brisket, cheese sauce, pickled onions between waffles with maple syrup.", { location: "Section 109", sections: ["109"] }),
  bpItem(DAI, DAIT, "daikin-whataburger", "daikin-whataburger-burger", "Whataburger", "BURGER", "Whataburger patty burger.", { location: "Section 156", sections: ["156"] }),
  bpItem(DAI, DAIT, "daikin-whataburger", "daikin-whataburger-fries", "Fries", "SNACK", "French fries.", { location: "Section 156", sections: ["156"] }),
  bpItem(DAI, DAIT, "daikin-whataburger", "daikin-whataburger-shake", "Shake", "DESSERT", "Hand-spun shake.", { location: "Section 156", sections: ["156"] }),
  bpItem(DAI, DAIT, "daikin-crust-city-pizza", "daikin-crawford-dog-pizza", "Crawford Dog Pizza", "PIZZA", "Hot dog-themed pizza slice.", { location: "Sections 116, 153, 411, 429", sections: ["116", "153", "411", "429"] }),
  bpItem(DAI, DAIT, "daikin-crust-city-pizza", "daikin-buffalo-chicken-pizza", "Buffalo Chicken Pizza", "PIZZA", "Buffalo chicken pizza slice.", { location: "Sections 116, 153, 411, 429", sections: ["116", "153", "411", "429"] }),
  bpItem(DAI, DAIT, "daikin-coffee-and-cocktails", "daikin-vietnamese-iced-coffee", "Vietnamese Iced Coffee", "DRINK", "Vietnamese iced coffee.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Section 106", sections: ["106"] }),
  bpItem(DAI, DAIT, "daikin-coffee-and-cocktails", "daikin-wake-up-call", "Wake Up Call", "DRINK", "Carajillo with Maker’s Mark and vanilla syrup.", { ...alc, beverageStyle: "Cocktail", location: "Section 106", sections: ["106"] }),
  bpItem(DAI, DAIT, "daikin-el-tiempo-cantina", "daikin-tiempo-cantina-fajitas", "Fajitas", "TACOS", "Sizzling fajitas plate.", { location: "Section 256", sections: ["256"] }),
  bpItem(DAI, DAIT, "daikin-el-tiempo-cantina", "daikin-tiempo-cantina-frozen-margarita", "Frozen Margarita", "DRINK", "Frozen margarita.", { ...alc, beverageStyle: "Cocktail", location: "Section 256", sections: ["256"] }),
  bpItem(DAI, DAIT, "daikin-el-tiempo-margarita-bar", "daikin-tiempo-margarita-bar-frozen-margarita", "Frozen Margarita", "DRINK", "Frozen margarita.", { ...alc, beverageStyle: "Cocktail", location: "Sections 109, 156", sections: ["109", "156"] }),
  bpItem(DAI, DAIT, "daikin-the-butcher", "daikin-butcher-smoked-brisket", "Smoked Brisket", "BBQ", "Sliced smoked brisket plate.", { location: "Sections 105, 116, 152, 408", sections: ["105", "116", "152", "408"] }),
  bpItem(DAI, DAIT, "daikin-the-butcher", "daikin-butcher-loaded-baked-potato", "Loaded Baked Potato", "BBQ", "Loaded baked potato with BBQ toppings.", { location: "Sections 105, 116, 152, 408", sections: ["105", "116", "152", "408"] }),
  bpItem(DAI, DAIT, "daikin-the-butcher", "daikin-butcher-ribs", "Ribs", "BBQ", "Smoked ribs plate.", { location: "Sections 105, 116, 152, 408", sections: ["105", "116", "152", "408"] }),
  bpItem(DAI, DAIT, "daikin-taqueria-arandas", "daikin-arandas-tacos", "Tacos", "TACOS", "Street tacos.", { location: "Sections 154, 420", sections: ["154", "420"] }),
  bpItem(DAI, DAIT, "daikin-taqueria-arandas", "daikin-arandas-burrito", "Burrito", "TACOS", "Burrito.", { location: "Sections 154, 420", sections: ["154", "420"] }),
  bpItem(DAI, DAIT, "daikin-taqueria-arandas", "daikin-arandas-quesadilla", "Quesadilla", "TACOS", "Grilled quesadilla.", { location: "Sections 154, 420", sections: ["154", "420"] }),
  bpItem(DAI, DAIT, "daikin-pluckers-wing-bar", "daikin-pluckers-wings", "Wings", "CHICKEN", "Pluckers wing flavors.", { location: "Section 156", sections: ["156"] }),
  bpItem(DAI, DAIT, "daikin-chick-fil-a", "daikin-chick-fil-a-sandwich", "Chicken Sandwich", "CHICKEN", "Chick-fil-A chicken sandwich.", { location: "Multiple sections", tags: [DAIT, "Closed Sundays"] }),
  bpItem(DAI, DAIT, "daikin-strosrita-stands", "daikin-strosrita", "StrosRita", "DRINK", "Frozen margarita-style stadium drink.", { ...alc, beverageStyle: "Cocktail", location: "Sections 106, 114, 128", sections: ["106", "114", "128"] }),
  bpItem(DAI, DAIT, "daikin-saint-arnold-bar", "daikin-saint-arnold-beer", "Saint Arnold Beer", "DRINK", "Saint Arnold draft and cans.", { ...alc, beverageStyle: "Beer", location: "Section 104", sections: ["104"] }),
  bpItem(DAI, DAIT, "daikin-stros-barrel-select", "daikin-makers-mark-private-select", "Maker’s Mark Private Select", "DRINK", "Maker’s Mark private select pour.", { ...alc, beverageStyle: "Other", location: "Premium / TBD" }),
  bpItem(DAI, DAIT, "daikin-karbach-love-street-bar", "daikin-karbach-draft-beer", "Karbach Draft Beer", "DRINK", "Karbach Brewing draft lineup.", { ...alc, beverageStyle: "Beer", location: "Section 119", sections: ["119"] }),
  bpItem(DAI, DAIT, "daikin-karbach-love-street-bar", "daikin-crush-city-mule", "Crush City Mule", "DRINK", "Crush City mule cocktail.", { ...alc, beverageStyle: "Cocktail", location: "Section 119", sections: ["119"] }),
  bpItem(DAI, DAIT, "daikin-value-stands", "daikin-dollar-hot-dog-tuesday", "Dollar Hot Dog Tuesday Hot Dog", "HOT_DOG", "Tuesday promotional value dog (promo rules vary).", { location: "Multiple locations", tags: [DAIT, "TODO: Confirm Tuesday promo details"] }),
  bpItem(DAI, DAIT, "daikin-value-stands", "daikin-value-nachos", "Value Nachos", "SNACK", "Value nachos.", { location: "Multiple locations" }),
  bpItem(DAI, DAIT, "daikin-value-stands", "daikin-value-popcorn", "Value Popcorn", "SNACK", "Value popcorn.", { location: "Multiple locations" }),
  bpItem(DAI, DAIT, "daikin-value-stands", "daikin-value-soda", "Value Soda", "DRINK", "Value fountain soda.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Multiple locations" }),
  bpItem(DAI, DAIT, "daikin-19th-hole", "daikin-19th-hole-salad", "Fresh Salad", "VEGAN", "Fresh salad bowl.", { location: "Center field" }),
  bpItem(DAI, DAIT, "daikin-19th-hole", "daikin-19th-hole-wrap", "Wrap", "SANDWICH", "Wrap sandwich.", { location: "Center field" }),
  bpItem(DAI, DAIT, "daikin-19th-hole", "daikin-19th-hole-fruit-cup", "Fruit Cup", "SNACK", "Cut fruit cup.", { location: "Center field" }),

  bpItem(GLF, GLFT, "glf-9th-inning-rally-sombrero", "glf-9th-inning-rally-sombrero-item", "9th Inning Rally Sombrero", "TACOS", "26-inch fried tortilla sombrero filled with nine-layer dip and chips.", { location: "Section 132", sections: ["132"] }),
  bpItem(GLF, GLFT, "glf-the-pig-kahuna", "glf-pig-kahuna-burger", "Pig Kahuna", "BURGER", "Teriyaki pork patty with peanut butter sauce and grilled pineapple.", { location: "Section 125", sections: ["125"] }),
  bpItem(GLF, GLFT, "glf-hawwt-dawwg", "glf-hawwt-dawwg-biscuits-gravy", "Hawwt Dawwg Biscuits & Gravy", "HOT_DOG", "Deep-fried hot dog on biscuit with country gravy.", { location: "Section 105", sections: ["105"] }),
  bpItem(GLF, GLFT, "glf-texas-ribeye-sandwich", "glf-texas-ribeye-sandwich-item", "Texas Ribeye Sandwich", "SANDWICH", "Ribeye with chimichurri, tomato, arugula.", { location: "Section 121", sections: ["121"] }),
  bpItem(GLF, GLFT, "glf-high-steaks-nachos", "glf-high-steaks-nachos-item", "High Steaks Nachos", "TACOS", "Tortilla chips with queso, Nolan Ryan beef tenderloin, pico, salsa.", { location: "Section 124", sections: ["124"] }),
  bpItem(GLF, GLFT, "glf-boomstick-stands", "glf-boomstick-burrito", "Boomstick Burrito", "TACOS", "Two-foot burrito with chili, cheese, jalapeños, fries.", { location: "Texas 24-inch stands" }),
  bpItem(GLF, GLFT, "glf-boomstick-stands", "glf-24-inch-boomstick", "24-Inch Boomstick", "HOT_DOG", "Two-foot hot dog with chili, cheese, onions.", { location: "Texas 24-inch stands" }),
  bpItem(GLF, GLFT, "glf-chicken-tender-helmet", "glf-chicken-tender-helmet-item", "Chicken Tender Helmet", "CHICKEN", "Souvenir helmet with chicken tenders and fries.", { location: "Section 126", sections: ["126"] }),
  bpItem(GLF, GLFT, "glf-hurtado-barbecue", "glf-hurtado-brisket-nachos", "Brisket Nachos", "BBQ", "Loaded brisket nachos.", { location: "Section 141", sections: ["141"] }),
  bpItem(GLF, GLFT, "glf-hurtado-barbecue", "glf-hurtado-birria-tacos", "Birria Tacos", "TACOS", "Birria taco plate.", { location: "Section 141", sections: ["141"] }),
  bpItem(GLF, GLFT, "glf-hurtado-barbecue", "glf-hurtado-big-papa-brisket-potato", "Big Papa Brisket Potato", "BBQ", "Loaded baked potato with brisket.", { location: "Section 141", sections: ["141"] }),
  bpItem(GLF, GLFT, "glf-whataburger", "glf-whataburger-burger", "Whataburger", "BURGER", "Whataburger patty burger.", { location: "Section 105", sections: ["105"] }),
  bpItem(GLF, GLFT, "glf-whataburger", "glf-whataburger-fries", "Fries", "SNACK", "French fries.", { location: "Section 105", sections: ["105"] }),
  bpItem(GLF, GLFT, "glf-whataburger", "glf-whataburger-shake", "Shake", "DESSERT", "Hand-spun shake.", { location: "Section 105", sections: ["105"] }),
  bpItem(GLF, GLFT, "glf-golden-chick", "glf-golden-tenders", "Golden Tenders", "CHICKEN", "Golden Chick tenders basket.", { location: "Section 128", sections: ["128"] }),
  bpItem(GLF, GLFT, "glf-pluckers-wing-bar", "glf-pluckers-bone-in-wings", "Bone-In Wings", "CHICKEN", "Bone-in wing flavors.", { location: "Section 131", sections: ["131"] }),
  bpItem(GLF, GLFT, "glf-pluckers-wing-bar", "glf-pluckers-boneless-wings", "Boneless Wings", "CHICKEN", "Boneless wings.", { location: "Section 131", sections: ["131"] }),
  bpItem(GLF, GLFT, "glf-arlington-eats", "glf-arlington-rotating-local", "Rotating Local Item", "OTHER", "Rotating item from local minority-owned businesses (menu by date).", { location: "Section 142", sections: ["142"], tags: [GLFT, "Rotating vendor"] }),
  bpItem(GLF, GLFT, "glf-dirty-sodas", "glf-dirty-soda", "Dirty Soda", "DRINK", "Custom dirty soda build.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Section 126", sections: ["126"] }),
  bpItem(GLF, GLFT, "glf-beer-bat-stands", "glf-beer-bat", "Beer Bat", "DRINK", "Beer in souvenir bat.", { ...alc, beverageStyle: "Beer", location: "Sections 110, 134, 215", sections: ["110", "134", "215"] }),
  bpItem(GLF, GLFT, "glf-sky-porch", "glf-sky-porch-bar-drinks", "Bar Drinks", "DRINK", "Sky Porch bar cocktails and beer.", { ...alc, beverageStyle: "Cocktail", location: "Section 201", sections: ["201"] }),
  bpItem(GLF, GLFT, "glf-sky-porch", "glf-sky-porch-vegan-soft-serve", "Vegan Soft Serve", "VEGAN", "Non-dairy soft serve.", { location: "Section 201", sections: ["201"] }),
  bpItem(GLF, GLFT, "glf-7-eleven-slurpees", "glf-slurpee", "Slurpee", "DRINK", "7-Eleven Slurpee flavors.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Sections 101, 205", sections: ["101", "205"] }),
  bpItem(GLF, GLFT, "glf-teremana-bar", "glf-ranger-rita", "Ranger Rita", "DRINK", "Teremana margarita-style cocktail.", { ...alc, beverageStyle: "Cocktail", location: "Section 134", sections: ["134"] }),
  bpItem(GLF, GLFT, "glf-dollar-ice-cream-sunday-stands", "glf-kids-ice-cream-novelty", "Kids Ice Cream Novelty", "DESSERT", "Pre-packaged kids ice cream novelty.", { location: "Sections 12, 121, 213", sections: ["12", "121", "213"] }),
  bpItem(GLF, GLFT, "glf-farmers-fridge", "glf-farmers-fresh-salad", "Fresh Salad", "VEGAN", "Refrigerated grab-and-go salad.", { location: "Sections 103, 124", sections: ["103", "124"], tags: [GLFT, "Grab and go"] }),
  bpItem(GLF, GLFT, "glf-farmers-fridge", "glf-farmers-grain-bowl", "Grain Bowl", "VEGAN", "Refrigerated grain bowl.", { location: "Sections 103, 124", sections: ["103", "124"], tags: [GLFT, "Grab and go"] }),
  bpItem(GLF, GLFT, "glf-farmers-fridge", "glf-farmers-healthy-snack", "Healthy Snack", "SNACK", "Refrigerated healthy snack cup.", { location: "Sections 103, 124", sections: ["103", "124"], tags: [GLFT, "Grab and go"] }),
  bpItem(GLF, GLFT, "glf-texas-tamale-torta-stand", "glf-vegan-tamales", "Vegan Tamales", "VEGAN", "Plant-based tamales.", { location: "Concourse" }),
  bpItem(GLF, GLFT, "glf-major-concession-hubs", "glf-gf-bun-option", "Gluten-Free Bun Option", "GLUTEN_FREE", "GF bun substitute at major hubs (availability varies).", { location: "Various hubs", tags: [GLFT, "TODO: Confirm stands"] }),

  bpItem(TMP, TMPT, "tmobile-ferry-boat-stands", "tmobile-ferry-fish-chips", "Washington State Ferry Boat Fish & Chips", "SEAFOOD", "Fish and chips from ferry boat-themed stands.", { location: "Multiple sections" }),
  bpItem(TMP, TMPT, "tmobile-ferry-boat-stands", "tmobile-ferry-chicken-tenders", "Washington State Ferry Boat Chicken Tenders", "CHICKEN", "Chicken tenders from ferry boat-themed stands.", { location: "Multiple sections" }),
  bpItem(TMP, TMPT, "tmobile-salt-and-straw", "tmobile-salt-straw-tacolate", "Tacolate", "DESSERT", "Cinnamon ancho ice cream in waffle cone taco shell with chocolate and puffed quinoa.", { location: "Sections 111, 328", sections: ["111", "328"] }),
  bpItem(TMP, TMPT, "tmobile-nakagawa-sushi", "tmobile-trident-roll", "Trident Roll", "SEAFOOD", "Sushi roll with crab salad, salmon, yellowtail, avocado, cucumber.", { location: "Section 132", sections: ["132"] }),
  bpItem(TMP, TMPT, "tmobile-tamari-bar", "tmobile-curry-donuts-dip", "Curry Donuts & Dip", "OTHER", "Curry donuts with dip.", { location: "Section 133", sections: ["133"] }),
  bpItem(TMP, TMPT, "tmobile-tamari-bar", "tmobile-vegan-area-206-curry", "Vegan Area 206 Curry", "VEGAN", "Vegan curry bowl.", { location: "Section 133", sections: ["133"] }),
  bpItem(TMP, TMPT, "tmobile-tamari-bar", "tmobile-citra-hop-rice-lager", "Citra Hop Rice Lager", "DRINK", "Citra hop rice lager draft.", { ...alc, beverageStyle: "Beer", location: "Section 133", sections: ["133"] }),
  bpItem(TMP, TMPT, "tmobile-specialty-churros", "tmobile-fluffernutter-churro", "Fluffernutter Churro", "DESSERT", "Churro with marshmallow fluff and peanut butter.", { location: "Sections 143, 319, 333", sections: ["143", "319", "333"] }),
  bpItem(TMP, TMPT, "tmobile-specialty-churros", "tmobile-fruit-cereal-churro", "Fruit Cereal Churro", "DESSERT", "Churro rolled in fruit cereal.", { location: "Sections 143, 319, 333", sections: ["143", "319", "333"] }),
  bpItem(TMP, TMPT, "tmobile-specialty-churros", "tmobile-apple-pie-churro", "Apple Pie Churro", "DESSERT", "Apple pie-spiced churro.", { location: "Sections 143, 319, 333", sections: ["143", "319", "333"] }),
  bpItem(TMP, TMPT, "tmobile-piroshky-piroshky", "tmobile-smoked-salmon-pate-piroshky", "Smoked Salmon Paté Piroshky", "SEAFOOD", "Smoked salmon paté in baked piroshky.", { location: "Section 132", sections: ["132"] }),
  bpItem(TMP, TMPT, "tmobile-piroshky-piroshky", "tmobile-bacon-cheeseburger-piroshky", "Bacon Cheeseburger Piroshky", "BURGER", "Bacon cheeseburger filling in piroshky.", { location: "Section 132", sections: ["132"] }),
  bpItem(TMP, TMPT, "tmobile-piroshky-piroshky", "tmobile-jalapeno-sausage-piroshky", "Jalapeño Sausage Piroshky", "HOT_DOG", "Jalapeño sausage in piroshky shell.", { location: "Section 132", sections: ["132"] }),
  bpItem(TMP, TMPT, "tmobile-el-rinconsito", "tmobile-el-rin-birria-tacos", "Birria Tacos", "TACOS", "Birria tacos with consommé.", { location: "The Pen" }),
  bpItem(TMP, TMPT, "tmobile-el-rinconsito", "tmobile-el-rin-asada-burrito", "Asada Burrito", "TACOS", "Carne asada burrito.", { location: "The Pen" }),
  bpItem(TMP, TMPT, "tmobile-el-rinconsito", "tmobile-horchata", "Horchata", "DRINK", "Horchata agua fresca.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "The Pen" }),
  bpItem(TMP, TMPT, "tmobile-rolling-smoke-bbq", "tmobile-rib-platter", "Rib Platter", "BBQ", "BBQ rib platter.", { location: "Section 313", sections: ["313"] }),
  bpItem(TMP, TMPT, "tmobile-rolling-smoke-bbq", "tmobile-brisket-loaded-mac", "Brisket Loaded Mac & Cheese", "BBQ", "Mac and cheese topped with brisket.", { location: "Section 313", sections: ["313"] }),
  bpItem(TMP, TMPT, "tmobile-rolling-smoke-bbq", "tmobile-rolling-smoke-pulled-pork", "Pulled Pork Sandwich", "BBQ", "Pulled pork sandwich.", { location: "Section 313", sections: ["313"] }),
  bpItem(TMP, TMPT, "tmobile-moto-pizza", "tmobile-mr-pig-pizza", "Mr. Pig Pizza", "PIZZA", "Pork-topped specialty pizza.", { location: "Section 314", sections: ["314"] }),
  bpItem(TMP, TMPT, "tmobile-marination", "tmobile-kalua-pork-sliders", "Kalua Pork Sliders", "SANDWICH", "Hawaiian-style kalua pork sliders.", { location: "The Pen; Section 119", sections: ["119"] }),
  bpItem(TMP, TMPT, "tmobile-marination", "tmobile-ube-coconut-rice-krispie", "Ube Coconut Rice Krispie Treat", "DESSERT", "Ube coconut rice cereal treat.", { location: "The Pen; Section 119", sections: ["119"] }),
  bpItem(TMP, TMPT, "tmobile-ivars", "tmobile-ivars-fish-chips", "Fish & Chips", "SEAFOOD", "Ivar’s fish and chips basket.", { location: "Multiple sections" }),
  bpItem(TMP, TMPT, "tmobile-ivars", "tmobile-ivars-clam-chowder", "Clam Chowder", "SEAFOOD", "Ivar’s clam chowder cup or bowl.", { location: "Multiple sections" }),
  bpItem(TMP, TMPT, "tmobile-hemplers", "tmobile-seattle-dog", "Seattle Dog", "HOT_DOG", "Seattle-style cream cheese and grilled onion dog.", { location: "Multiple sections" }),
  bpItem(TMP, TMPT, "tmobile-ballard-pizza", "tmobile-ballard-pizza-slice", "Pizza Slice", "PIZZA", "Ballard Pizza slice.", { location: "The Pen; Section 132", sections: ["132"] }),
  bpItem(TMP, TMPT, "tmobile-ballard-pizza", "tmobile-stadium-bites", "Stadium Bites", "SNACK", "Shareable stadium bites plate.", { location: "The Pen; Section 132", sections: ["132"] }),
  bpItem(TMP, TMPT, "tmobile-way-back-crab-shack", "tmobile-dungeness-crab-sandwich", "Dungeness Crab Sandwich", "SEAFOOD", "Dungeness crab sandwich.", { location: "Section 187", sections: ["187"] }),
  bpItem(TMP, TMPT, "tmobile-the-pen", "tmobile-the-pen-bar-drinks", "Bar Drinks", "DRINK", "The Pen full bar pours.", { ...alc, beverageStyle: "Cocktail", location: "Center field" }),
  bpItem(TMP, TMPT, "tmobile-coca-cola-fan-deck", "tmobile-fan-deck-dirty-soda", "Dirty Soda", "DRINK", "Dirty soda build at Fan Deck.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Section 249", sections: ["249"] }),
  bpItem(TMP, TMPT, "tmobile-secret-cocktail-door", "tmobile-rotating-craft-cocktail", "Rotating Craft Cocktail", "DRINK", "Rotating craft cocktail menu.", { ...alc, beverageStyle: "Cocktail", location: "100 level" }),
  bpItem(TMP, TMPT, "tmobile-mariners-value-beer", "tmobile-value-beer", "Value Beer", "DRINK", "Discounted value beer pour.", { ...alc, beverageStyle: "Beer", location: "Sections 105, 128, 141, 218", sections: ["105", "128", "141", "218"] }),
  bpItem(TMP, TMPT, "tmobile-mariners-value-beer", "tmobile-corona-sunbrew-na", "Corona Sunbrew NA", "DRINK", "Corona Sunbrew non-alcoholic brew.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Sections 105, 128, 141, 218", sections: ["105", "128", "141", "218"] }),
  bpItem(TMP, TMPT, "tmobile-gluten-free-stand", "tmobile-gf-bun-option", "Gluten-Free Bun Option", "GLUTEN_FREE", "GF bun substitute.", { location: "Section 132", sections: ["132"] }),
  bpItem(TMP, TMPT, "tmobile-gluten-free-stand", "tmobile-gf-beer", "Gluten-Free Beer", "DRINK", "Gluten-reduced or GF labeled beer (brand varies).", { ...alc, beverageStyle: "Beer", location: "Section 132", sections: ["132"], tags: [TMPT, "TODO: Confirm GF beer brands on tap"] }),
  bpItem(TMP, TMPT, "tmobile-gluten-free-stand", "tmobile-gf-snacks", "Gluten-Free Snacks", "GLUTEN_FREE", "Packaged GF snacks.", { location: "Section 132", sections: ["132"] }),

  bpItem(AMF, AMFT, "amfam-fair-foods-stand", "amfam-deep-fried-kringle", "Deep-Fried Kringle", "DESSERT", "Deep-fried kringle pastry.", { location: "Section 125", sections: ["125"] }),
  bpItem(AMF, AMFT, "amfam-fair-foods-stand", "amfam-nachos-on-a-stick", "Nachos on a Stick", "SNACK", "Nachos on a stick novelty.", { location: "Section 125", sections: ["125"] }),
  bpItem(AMF, AMFT, "amfam-fair-foods-stand", "amfam-bbq-brisket-waffle", "Barbecue Brisket Waffle", "BBQ", "Brisket on waffle with BBQ.", { location: "Section 125", sections: ["125"] }),
  bpItem(AMF, AMFT, "amfam-fair-foods-stand", "amfam-specialty-cream-puff", "Specialty Cream Puff", "DESSERT", "Stadium specialty cream puff.", { location: "Section 125", sections: ["125"] }),
  bpItem(AMF, AMFT, "amfam-third-street-market-hall-annex", "amfam-annex-honey-butter-tenders", "Honey Butter Chicken Tenders", "CHICKEN", "Honey butter chicken tenders.", { location: "Loge level" }),
  bpItem(AMF, AMFT, "amfam-third-street-market-hall-annex", "amfam-annex-chicken-ice-cream", "Chicken Ice Cream", "DESSERT", "Chicken-themed novelty ice cream (vendor specialty).", { location: "Loge level" }),
  bpItem(AMF, AMFT, "amfam-third-street-market-hall-annex", "amfam-annex-dirty-soda", "Dirty Soda", "DRINK", "Dirty soda build.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Loge level" }),
  bpItem(AMF, AMFT, "amfam-third-street-market-hall-annex", "amfam-annex-dubai-strawberry-cup", "Dubai-Style Strawberry Cup", "DESSERT", "Dubai-style chocolate strawberry cup.", { location: "Loge level" }),
  bpItem(AMF, AMFT, "amfam-third-street-market-hall-annex", "amfam-annex-street-tacos", "Street Tacos", "TACOS", "Street taco platter.", { location: "Loge level" }),
  bpItem(AMF, AMFT, "amfam-third-street-market-hall-annex", "amfam-annex-arepa", "Arepa", "OTHER", "Arepa plate.", { location: "Loge level" }),
  bpItem(AMF, AMFT, "amfam-bebe-zito", "amfam-bebe-honey-butter-tenders", "Honey Butter Chicken Tenders", "CHICKEN", "Honey butter chicken tenders.", { location: "TBD", tags: [AMFT, "TODO: Stand location vs annex"] }),
  bpItem(AMF, AMFT, "amfam-bebe-zito", "amfam-bebe-chicken-ice-cream", "Chicken Ice Cream", "DESSERT", "Chicken-themed novelty ice cream.", { location: "TBD", tags: [AMFT, "TODO: Stand location vs annex"] }),
  bpItem(AMF, AMFT, "amfam-the-sweets-stand", "amfam-sweets-dirty-soda", "Dirty Soda", "DRINK", "Dirty soda build.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "TBD" }),
  bpItem(AMF, AMFT, "amfam-the-sweets-stand", "amfam-can-d-shop-candy", "Can-D Shop Candy", "DESSERT", "Pick-your-mix candy cup.", { location: "TBD" }),
  bpItem(AMF, AMFT, "amfam-the-sweets-stand", "amfam-drip-chocolate-strawberry-cup", "Drip Chocolate Strawberry Cup", "DESSERT", "Chocolate-drizzled strawberry cup.", { location: "TBD" }),
  bpItem(AMF, AMFT, "amfam-kompali-tacos", "amfam-kompali-street-tacos", "Street Tacos", "TACOS", "Kompali street tacos.", { location: "TBD" }),
  bpItem(AMF, AMFT, "amfam-anytime-arepa", "amfam-anytime-stuffed-arepa", "Stuffed Arepa", "OTHER", "Stuffed arepa.", { location: "TBD" }),
  bpItem(AMF, AMFT, "amfam-the-alley-food-truck-park", "amfam-alley-rotating-truck", "Rotating Food Truck Item", "OTHER", "Rotating food truck special (menu by date).", { location: "Left field loge", tags: [AMFT, "Rotating vendor"] }),
  bpItem(AMF, AMFT, "amfam-k-and-ls-bbq", "amfam-k-l-smoked-brisket-burger", "Smoked Brisket Burger", "BURGER", "Smoked brisket-topped burger.", { location: "The Alley Food Truck Park" }),
  bpItem(AMF, AMFT, "amfam-k-and-ls-bbq", "amfam-k-l-brisket-loaded-fries", "Brisket Loaded Fries", "BBQ", "Fries loaded with brisket and sauce.", { location: "The Alley Food Truck Park" }),
  bpItem(AMF, AMFT, "amfam-chuchos-red-tacos", "amfam-chuchos-birria-red-tacos", "Birria Red Tacos", "TACOS", "Birria red tacos with dip.", { location: "The Alley Food Truck Park" }),
  bpItem(AMF, AMFT, "amfam-hidden-kitchen-mke", "amfam-hidden-global-fusion", "Global Fusion Comfort Food", "OTHER", "Rotating global fusion plate (menu varies).", { location: "The Alley Food Truck Park", tags: [AMFT, "Rotating menu"] }),
  bpItem(AMF, AMFT, "amfam-leinenkugels-barrel-yard", "amfam-crew-brew", "Crew Brew", "DRINK", "Brewers Crew Brew draft.", { ...alc, beverageStyle: "Beer", location: "Left field" }),
  bpItem(AMF, AMFT, "amfam-leinenkugels-barrel-yard", "amfam-fried-cheese-curds", "Fried Cheese Curds", "SNACK", "Wisconsin fried cheese curds.", { location: "Left field" }),
  bpItem(AMF, AMFT, "amfam-johnsonville-sausages", "amfam-johnsonville-brat-secret-sauce", "Bratwurst with Secret Stadium Sauce", "HOT_DOG", "Johnsonville brat with Secret Stadium Sauce.", { location: "Full Count stands" }),
  bpItem(AMF, AMFT, "amfam-ballpark-staples", "amfam-sticky-maple-chicken-sandwich", "Sticky Maple Chicken Sandwich", "CHICKEN", "Sticky maple chicken sandwich.", { location: "Multiple locations" }),
  bpItem(AMF, AMFT, "amfam-ballpark-staples", "amfam-al-pastor-topped-dog", "Al Pastor Topped Dog", "HOT_DOG", "Hot dog topped al pastor style.", { location: "Multiple locations" }),
  bpItem(AMF, AMFT, "amfam-uw-credit-union-plaza", "amfam-uw-plaza-outdoor-bar-drinks", "Outdoor Bar Drinks", "DRINK", "Outdoor plaza bar cocktails and beer.", { ...alc, beverageStyle: "Cocktail", location: "Outdoor plaza", tags: [AMFT, "Opening June 2026 per source"] }),
  bpItem(AMF, AMFT, "amfam-x-golf", "amfam-x-golf-bar-drinks", "Bar Drinks", "DRINK", "X-Golf bar beer and cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Left field" }),
  bpItem(AMF, AMFT, "amfam-casamigos-patio", "amfam-casamigos-margarita", "Margarita", "DRINK", "Casamigos margarita.", { ...alc, beverageStyle: "Cocktail", location: "Right field corner" }),
  bpItem(AMF, AMFT, "amfam-casamigos-patio", "amfam-casamigos-paloma", "Paloma", "DRINK", "Casamigos paloma.", { ...alc, beverageStyle: "Cocktail", location: "Right field corner" }),
  bpItem(AMF, AMFT, "amfam-wisconsin-craft-stand", "amfam-yuengling-beer", "Yuengling Beer", "DRINK", "Yuengling draft and cans.", { ...alc, beverageStyle: "Beer", location: "Multiple locations" }),
  bpItem(AMF, AMFT, "amfam-wisconsin-craft-stand", "amfam-new-glarus-beer", "New Glarus Beer", "DRINK", "New Glarus Brewing draft and cans.", { ...alc, beverageStyle: "Beer", location: "Multiple locations" }),
  bpItem(AMF, AMFT, "amfam-wisconsin-craft-stand", "amfam-lakefront-brewery-beer", "Lakefront Brewery Beer", "DRINK", "Lakefront Brewery draft and cans.", { ...alc, beverageStyle: "Beer", location: "Multiple locations" })
];
