import { bpItem, bpVendor } from "./ballpark-menu-builders";
import type { FoodItem, Vendor } from "./sample-data";

const CF = "chase-field";
const CFT = "Chase Field";
const AA = "angel-stadium";
const AAT = "Angel Stadium";
const OP = "oracle-park";
const OPT = "Oracle Park";
const CO = "coors-field";
const COT = "Coors Field";
const NP = "nationals-park";
const NPT = "Nationals Park";
const LP = "loandepot-park";
const LPT = "loanDepot park";

const alc = {
  itemType: "Alcoholic Drink" as const,
  alcoholic: true,
  ageRestricted: true
};

/** Wave 2 MLB concessions — Chase Field, Angel Stadium, Oracle Park, Coors Field, Nationals Park, loanDepot park. */
export const wave2BallparkVendors: Vendor[] = [
  bpVendor(CF, "chase-bases-loaded", "Bases Loaded!", "Field", "Section 109"),
  bpVendor(CF, "chase-jefferson-street-deli", "Jefferson Street Deli", "Field", "Section 120"),
  bpVendor(CF, "chase-dbacks-bbq-alley", "D-backs BBQ Alley", "Field", "Section 114"),
  bpVendor(CF, "chase-churro-dog-hq", "Churro Dog HQ", "Field / upper", "Sections 129, 324"),
  bpVendor(CF, "chase-gonzos-grill", "Gonzo’s Grill", "Field", "Section 142"),
  bpVendor(CF, "chase-streets-of-new-york", "Streets of New York", "Field / upper", "Sections 113, 124, 305"),
  bpVendor(CF, "chase-chick-fil-a", "Chick-fil-A", "Field", "Section 126", "Closed Sundays."),
  bpVendor(CF, "chase-cold-stone", "Cold Stone Creamery", "Concourse", "Sections 112, 137, 310"),
  bpVendor(CF, "chase-cathys-cookies", "Cathy’s Cookies", "Field / upper", "Sections 104, 308"),
  bpVendor(CF, "chase-azona-street-tacos", "A-Zona Street Tacos", "Club", "Section 208"),
  bpVendor(CF, "chase-reyglorias-tamales", "ReyGloria’s Tamales", "Field", "Section 137"),
  bpVendor(CF, "chase-serpientes-cantina", "Serpientes Cantina", "Field", "Section 110"),
  bpVendor(CF, "chase-taqueria-los-dbacks", "Taquería Los D-backs", "Field", "Section 123"),
  bpVendor(CF, "chase-estrella-jalisco-cantina", "Estrella Jalisco Cantina", "Right field", "Upper level"),
  bpVendor(CF, "chase-four-peaks", "Four Peaks", "Field", "Section 139"),
  bpVendor(CF, "chase-big-league-drafts", "Big League Drafts", "Field", "Section 120"),
  bpVendor(CF, "chase-casamigos-bar", "Casamigos Bar", "Field", "Section 104"),
  bpVendor(CF, "chase-jack-daniels-bar", "Jack Daniel’s Bar", "Field", "Section 117"),
  bpVendor(CF, "chase-avnet-home-plate-club", "Avnet Home Plate Club", "Club", "Behind home plate"),
  bpVendor(CF, "chase-big-dawgs", "Big Dawgs", "Field / upper", "Sections 105, 324"),
  bpVendor(CF, "chase-bat-flip-burgers", "Bat Flip Burgers", "Field", "Section 118"),

  bpVendor(AA, "angels-walk-off-waffles", "Walk-Off Waffles", "Upper", "Section 232"),
  bpVendor(AA, "angels-la-caguama", "La Caguama", "Field", "Section 260"),
  bpVendor(AA, "angels-crafty-mac-mash", "Crafty Mac & Mash", "Field", "Section 237"),
  bpVendor(AA, "angels-first-base-food-court", "1st Base Food Court", "Concourse", "First base side"),
  bpVendor(AA, "angels-premium-levels", "Premium Levels", "Premium", "Suites & premium levels"),
  bpVendor(AA, "angels-pac-man-chomp-stop", "Pac-Man Chomp Stop", "Pavilion", "Right field pavilion"),
  bpVendor(AA, "angels-classic-hits", "Classic Hits", "Field", "Multiple sections"),
  bpVendor(AA, "angels-chronic-tacos", "Chronic Tacos", "Field / upper", "Sections 211, 420; 1st Base Food Court"),
  bpVendor(AA, "angels-brewery-x", "Brewery X", "Club", "Club level"),
  bpVendor(AA, "angels-crafty-dogs", "Crafty Dogs", "Concourse", "1st Base Food Court"),
  bpVendor(AA, "angels-cathys-cookies", "Cathy’s Cookies", "Concourse", "Multiple locations"),
  bpVendor(AA, "angels-pacifico-porch", "Pacifico Porch", "View", "Lower view level"),
  bpVendor(AA, "angels-truly-terrace", "Truly Terrace", "Upper", "Upper level"),
  bpVendor(AA, "angels-lexus-diamond-club", "Lexus Diamond Club", "Premium", "Behind home plate", "TODO: Rotating menu by visiting team."),
  bpVendor(AA, "angels-casa-modelo", "Casa Modelo", "Field", "Section 260"),
  bpVendor(AA, "angels-healthy-options", "Healthy Options", "Field", "Section 125"),

  bpVendor(OP, "giants-sf-selects", "SF Selects", "Plaza", "Scoreboard Plaza"),
  bpVendor(OP, "giants-say-hey-sausage", "Say Hey Sausage", "Field", "Section 125"),
  bpVendor(OP, "giants-lucky-fries", "Lucky Fries", "Field", "Section 128"),
  bpVendor(OP, "giants-999-package", "9-9-9 Package", "Concourse", "Location varies"),
  bpVendor(OP, "giants-pacific-eats", "Pacific Eats", "Field", "Section 127"),
  bpVendor(OP, "giants-crazy-crabz", "Crazy Crab’z", "Outfield", "Center field"),
  bpVendor(OP, "giants-orlandos-caribbean-bbq", "Orlando’s Caribbean BBQ", "Concourse", "Promenade 142; View 314"),
  bpVendor(OP, "giants-gils-garlic-fries", "Gil’s Garlic Fries", "Field", "Multiple sections"),
  bpVendor(OP, "giants-the-garden", "The Garden", "Outfield", "Center field"),
  bpVendor(OP, "giants-tony-gemignani-slice", "Tony Gemignani’s Slice House", "Field", "Section 129"),
  bpVendor(OP, "giants-doggie-diner-express", "Doggie Diner Express", "Field", "Section 121"),
  bpVendor(OP, "giants-mission-street-taqueria", "Mission Street Taqueria", "Field", "Section 110"),
  bpVendor(OP, "giants-the-carvery", "The Carvery", "Field", "Section 114"),
  bpVendor(OP, "giants-chick-fil-a-portables", "Chick-fil-A Portables", "Concourse", "Portable stands", "Closed Sundays."),
  bpVendor(OP, "giants-athletic-brewing", "Athletic Brewing", "Concourse", "Multiple sections"),
  bpVendor(OP, "giants-murphs-irish-pub", "Murph’s Irish Pub", "Field", "Section 112"),
  bpVendor(OP, "giants-fountain-cocktail-stands", "Fountain & Cocktail Stands", "Concourse", "Multiple"),

  bpVendor(CO, "rockies-fanfare", "Fanfare", "Field", "Section 157"),
  bpVendor(CO, "rockies-pizza-donuts", "Pizza Donuts", "Field", "Section 109"),
  bpVendor(CO, "rockies-sandlot-brewery", "SandLot Brewery", "Field", "Section 113"),
  bpVendor(CO, "rockies-dessert-stand", "Dessert Stand", "Concourse", "Location varies"),
  bpVendor(CO, "rockies-999-challenge-bundle", "9-9-9 Challenge Bundle", "Concourse", "Location varies"),
  bpVendor(CO, "rockies-biker-jims", "Biker Jim’s Gourmet Dogs", "Field / upper", "Sections 107, 331"),
  bpVendor(CO, "rockies-helton-burger", "Helton Burger", "Field", "Section 153"),
  bpVendor(CO, "rockies-birdcall", "Birdcall", "Upper", "The Rooftop"),
  bpVendor(CO, "rockies-rocky-mountain-oysters", "Rocky Mountain Oysters", "Field", "Section 144"),
  bpVendor(CO, "rockies-polidori-sausage", "Polidori Sausage", "Field / upper", "Sections 107, 149, 321"),
  bpVendor(CO, "rockies-smashburger", "Smashburger", "Upper", "Section 303; The Rooftop"),
  bpVendor(CO, "rockies-the-rooftop", "The Rooftop", "Upper", "Section 303"),
  bpVendor(CO, "rockies-mountain-ranch-bar-grille", "Mountain Ranch Bar & Grille", "Outfield", "Right field"),
  bpVendor(CO, "rockies-cookie-creamery", "Cookie & Creamery", "Field", "Section 119"),
  bpVendor(CO, "rockies-infield-greens", "Infield Greens", "Field", "Section 120"),
  bpVendor(CO, "rockies-gluten-friendly-stand", "Gluten Friendly Stand", "Field", "Section 143"),
  bpVendor(CO, "rockies-505-burrito-bowls", "505 Burrito Bowls", "Field", "Section 134"),

  bpVendor(NP, "nats-roaming-rooster", "Roaming Rooster", "Field", "Section 239"),
  bpVendor(NP, "nats-chesapeake-crab-cake", "Chesapeake Crab Cake Co.", "Field", "Section 109"),
  bpVendor(NP, "nats-capitol-slugger", "Capitol Slugger", "Field", "Section 114"),
  bpVendor(NP, "nats-fuzzies-burgers", "Fuzzies Burgers", "Field", "Section 106"),
  bpVendor(NP, "nats-eatopian-eats", "Eatopian Eats", "Field", "Section 136"),
  bpVendor(NP, "nats-bens-chili-bowl", "Ben’s Chili Bowl", "Field / upper", "Sections 110, 141, 238, 307"),
  bpVendor(NP, "nats-rocklands-bbq", "Rocklands BBQ", "Field", "Section 118"),
  bpVendor(NP, "nats-arepa-zone", "Arepa Zone", "Field / upper", "Sections 148, 304"),
  bpVendor(NP, "nats-capo-deli", "Capo Deli", "Field", "Section 136"),
  bpVendor(NP, "nats-ssongs-korean-corn-dogs", "Ssongs Korean Corn Dogs", "Field / upper", "Sections 130, 305"),
  bpVendor(NP, "nats-coneacopia", "Coneacopia", "Field", "Section 136"),
  bpVendor(NP, "nats-don-churro", "Don Churro", "Field / upper", "Sections 113, 309"),
  bpVendor(NP, "nats-capital-candy-jar", "Capital Candy Jar", "Field", "Section 139"),
  bpVendor(NP, "nats-ritas-italian-ice", "Rita’s Italian Ice", "Concourse", "Multiple sections"),
  bpVendor(NP, "nats-electric-cool-aid", "Electric Cool-Aid", "Field", "Sections 102, 143"),
  bpVendor(NP, "nats-budweiser-terrace", "Budweiser Terrace", "Upper", "Section 243"),
  bpVendor(NP, "nats-district-drafts", "District Drafts", "Concourse", "Multiple sections"),
  bpVendor(NP, "nats-ultra-loft", "ULTRA Loft", "Upper", "Section 242"),
  bpVendor(NP, "nats-silver-bullet-bar", "Silver Bullet Bar", "Field", "Section 104"),
  bpVendor(NP, "nats-melissas-field-of-greens", "Melissa’s Field of Greens", "Field", "Section 136"),
  bpVendor(NP, "nats-char-bar", "Char Bar", "Field", "Section 143", "Certified Glatt Kosher; closed Friday evenings and Saturdays."),
  bpVendor(NP, "nats-avoiding-gluten-cart", "Avoiding Gluten Cart", "Field", "Section 148"),

  bpVendor(LP, "marlins-classics-con-sazon", "Classics Con Sazon", "Field", "Section 10"),
  bpVendor(LP, "marlins-mister-softee", "Mister Softee", "Concourse", "Promenade and Vista levels"),
  bpVendor(LP, "marlins-the-change-up", "The Change Up", "Field", "Section 1"),
  bpVendor(LP, "marlins-cocktail-stands", "Cocktail Stands", "Concourse", "Multiple"),
  bpVendor(LP, "marlins-the-press-box", "The Press Box", "Field", "Section 28"),
  bpVendor(LP, "marlins-oppo-taco-goya", "Oppo Taco presented by Goya", "Field", "Section 8"),
  bpVendor(LP, "marlins-suviche", "SuViche", "Field", "Section 210"),
  bpVendor(LP, "marlins-magic-city-bbq", "Magic City BBQ", "Field", "Section 8"),
  bpVendor(LP, "marlins-beisbowl", "Beisbowl", "Field", "Section 28"),
  bpVendor(LP, "marlins-coffee-counter", "Coffee Counter", "Field", "Section 34"),
  bpVendor(LP, "marlins-familia-faves", "Familia Faves", "Field", "Section 36"),
  bpVendor(LP, "marlins-blue-moon-brewhall", "Blue Moon Brew Hall", "Field", "Section 15"),
  bpVendor(LP, "marlins-bullpen-bar-grill", "Bullpen Bar & Grill", "Outfield", "Left field corner"),
  bpVendor(LP, "marlins-budweiser-bowtie-bar", "Budweiser Bowtie Bar", "Terrace", "Skyline Terrace"),
  bpVendor(LP, "marlins-recess-sports-lounge", "Recess Sports Lounge", "Club", "Location varies"),
  bpVendor(LP, "marlins-walk-off-market", "Walk-Off Market", "Field", "Section 24"),
  bpVendor(LP, "marlins-fowl-pole", "Fowl Pole", "Field", "Section 5"),
  bpVendor(LP, "marlins-sahlens-top-dog", "Sahlen’s Top Dog", "Field", "Section 4")
];

export const wave2BallparkFoodItems: FoodItem[] = [
  bpItem(CF, CFT, "chase-bases-loaded", "chase-128oz-souvenir-nacho-bucket", "128-Oz Souvenir Nacho Bucket", "TACOS", "Massive nacho bucket with corn chips, barbacoa beef, pork carnitas, or vegetarian fajita vegetables, queso, pico, jalapeños.", { location: "Section 109", sections: ["109"] }),
  bpItem(CF, CFT, "chase-bases-loaded", "chase-64oz-souvenir-nacho-bucket", "64-Oz Souvenir Nacho Bucket", "TACOS", "Smaller souvenir nacho bucket with chips, proteins, queso, pico, jalapeños.", { location: "Section 109", sections: ["109"] }),
  bpItem(CF, CFT, "chase-jefferson-street-deli", "chase-5050-stretch", "50/50 Stretch", "SANDWICH", "18-inch baguette split between chicken parmesan and hot pastrami with kettle chips.", { location: "Section 120", sections: ["120"] }),
  bpItem(CF, CFT, "chase-jefferson-street-deli", "chase-big-bella", "Big Bella", "SANDWICH", "Herb focaccia with mortadella, mozzarella, pistachio cream, arugula.", { location: "Section 120", sections: ["120"] }),
  bpItem(CF, CFT, "chase-dbacks-bbq-alley", "chase-barbecue-brigade", "Barbecue Brigade", "BBQ", "Platter with burnt end brisket, ribs, BBQ pulled pork potato, slaw, beer-pickled onions.", { location: "Section 114", sections: ["114"] }),
  bpItem(CF, CFT, "chase-churro-dog-hq", "chase-ballgame-milkshake", "Take Me Out to the Ballgame Milkshake", "DESSERT", "Salted caramel shake with whipped cream, peanut butter sandwich cookies, Kit Kat, Cracker Jack.", { location: "Sections 129, 324", sections: ["129", "324"] }),
  bpItem(CF, CFT, "chase-churro-dog-hq", "chase-churro-dog", "Churro Dog", "DESSERT", "Cinnamon churro in a Long John donut bun with frozen yogurt, chocolate, caramel.", { location: "Sections 129, 324", sections: ["129", "324"] }),
  bpItem(CF, CFT, "chase-gonzos-grill", "chase-gonzos-fried-chicken-sandwich", "Fried Chicken Sandwich", "CHICKEN", "Premium fried chicken sandwich.", { location: "Section 142", sections: ["142"] }),
  bpItem(CF, CFT, "chase-gonzos-grill", "chase-gonzos-chicken-tenders", "Chicken Tenders", "CHICKEN", "Chicken tenders basket.", { location: "Section 142", sections: ["142"] }),
  bpItem(CF, CFT, "chase-streets-of-new-york", "chase-sony-thin-crust-pizza", "Thin-Crust Pizza", "PIZZA", "Thin-crust pizza slice or pie.", { location: "Sections 113, 124, 305", sections: ["113", "124", "305"] }),
  bpItem(CF, CFT, "chase-streets-of-new-york", "chase-sony-wings", "Wings", "CHICKEN", "Wing order.", { location: "Sections 113, 124, 305", sections: ["113", "124", "305"] }),
  bpItem(CF, CFT, "chase-chick-fil-a", "chase-cfa-chicken-sandwich", "Chicken Sandwich", "CHICKEN", "Classic chicken sandwich.", { location: "Section 126", sections: ["126"] }),
  bpItem(CF, CFT, "chase-chick-fil-a", "chase-cfa-waffle-fries", "Waffle Fries", "SNACK", "Waffle-cut fries.", { location: "Section 126", sections: ["126"] }),
  bpItem(CF, CFT, "chase-cold-stone", "chase-cold-stone-creation", "Ice Cream Creation", "DESSERT", "Mix-in ice cream creation.", { location: "Sections 112, 137, 310", sections: ["112", "137", "310"] }),
  bpItem(CF, CFT, "chase-cold-stone", "chase-cold-stone-waffle-bowl-sundae", "Waffle Bowl Sundae", "DESSERT", "Sundae in waffle bowl.", { location: "Sections 112, 137, 310", sections: ["112", "137", "310"] }),
  bpItem(CF, CFT, "chase-cathys-cookies", "chase-cathys-chocolate-chip-sleeve", "Chocolate Chip Cookie Sleeve", "DESSERT", "Warm chocolate chip cookies by the sleeve.", { location: "Sections 104, 308", sections: ["104", "308"] }),
  bpItem(CF, CFT, "chase-cathys-cookies", "chase-cathys-souvenir-bucket", "Souvenir Cookie Bucket", "DESSERT", "Cookies in souvenir bucket.", { location: "Sections 104, 308", sections: ["104", "308"] }),
  bpItem(CF, CFT, "chase-azona-street-tacos", "chase-azona-carne-asada-tacos", "Carne Asada Tacos", "TACOS", "Carne asada street tacos.", { location: "Section 208", sections: ["208"] }),
  bpItem(CF, CFT, "chase-azona-street-tacos", "chase-azona-chicken-tinga-tacos", "Chicken Tinga Tacos", "TACOS", "Chicken tinga tacos.", { location: "Section 208", sections: ["208"] }),
  bpItem(CF, CFT, "chase-azona-street-tacos", "chase-azona-carne-burrito-bowl", "Carne Asada Burrito Bowl", "TACOS", "Carne asada burrito bowl.", { location: "Section 208", sections: ["208"] }),
  bpItem(CF, CFT, "chase-azona-street-tacos", "chase-azona-tinga-burrito-bowl", "Chicken Tinga Burrito Bowl", "TACOS", "Chicken tinga burrito bowl.", { location: "Section 208", sections: ["208"] }),
  bpItem(CF, CFT, "chase-azona-street-tacos", "chase-azona-plant-powered-bowl", "Plant-Powered Burrito Bowl", "VEGAN", "Plant-based chorizo bowl with salsa verde.", { location: "Section 208", sections: ["208"] }),
  bpItem(CF, CFT, "chase-reyglorias-tamales", "chase-reyglorias-tamales", "Tamales", "TACOS", "Authentic tamales.", { location: "Section 137", sections: ["137"] }),
  bpItem(CF, CFT, "chase-reyglorias-tamales", "chase-reyglorias-elote", "Street Corn Elote", "SNACK", "Street corn elote cup.", { location: "Section 137", sections: ["137"] }),
  bpItem(CF, CFT, "chase-reyglorias-tamales", "chase-reyglorias-rice-beans", "Rice and Beans", "OTHER", "Side rice and beans.", { location: "Section 137", sections: ["137"] }),
  bpItem(CF, CFT, "chase-serpientes-cantina", "chase-serpientes-frozen-cocktails", "Frozen Cocktails", "DRINK", "Frozen cantina cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Section 110", sections: ["110"] }),
  bpItem(CF, CFT, "chase-serpientes-cantina", "chase-serpientes-tostilocos", "Tostilocos", "SNACK", "Salsa verde Tostitos topped with Mexican street snacks.", { location: "Section 110", sections: ["110"] }),
  bpItem(CF, CFT, "chase-taqueria-los-dbacks", "chase-los-dbacks-carne-street-tacos", "Carne Asada Street Tacos", "TACOS", "Carne asada on fresh flour tortillas.", { location: "Section 123", sections: ["123"] }),
  bpItem(CF, CFT, "chase-estrella-jalisco-cantina", "chase-estrella-cantina-menu", "Cantina Menu", "TACOS", "Cantina plates and snacks.", { location: "Right field upper" }),
  bpItem(CF, CFT, "chase-estrella-jalisco-cantina", "chase-estrella-beer", "Beer", "DRINK", "Draft and bottled beer.", { ...alc, beverageStyle: "Beer", location: "Right field upper" }),
  bpItem(CF, CFT, "chase-four-peaks", "chase-four-peaks-arizona-craft-beer", "Arizona Craft Beer", "DRINK", "Local Arizona craft lineup.", { ...alc, beverageStyle: "Beer", location: "Section 139", sections: ["139"] }),
  bpItem(CF, CFT, "chase-four-peaks", "chase-four-peaks-hot-honey-fries", "Hot Honey Fries", "SNACK", "Fries with hot honey.", { location: "Section 139", sections: ["139"] }),
  bpItem(CF, CFT, "chase-four-peaks", "chase-four-peaks-chimichurri-steak-quesadilla", "Chimichurri Steak Quesadilla", "TACOS", "Steak quesadilla with chimichurri.", { location: "Section 139", sections: ["139"] }),
  bpItem(CF, CFT, "chase-four-peaks", "chase-four-peaks-avoiding-gluten-dog", "Avoiding Gluten Dog", "GLUTEN_FREE", "Dedicated gluten-free hot dog option.", { location: "Section 139", sections: ["139"], tags: [CFT, "TODO: Confirm dedicated prep vs shared line"] }),
  bpItem(CF, CFT, "chase-big-league-drafts", "chase-bld-local-craft-beer", "Local Craft Beer", "DRINK", "Rotating local craft taps.", { ...alc, beverageStyle: "Beer", location: "Section 120", sections: ["120"] }),
  bpItem(CF, CFT, "chase-casamigos-bar", "chase-casamigos-craft-cocktails", "Craft Cocktails", "DRINK", "Casamigos-led cocktail menu.", { ...alc, beverageStyle: "Cocktail", location: "Section 104", sections: ["104"] }),
  bpItem(CF, CFT, "chase-jack-daniels-bar", "chase-jd-whiskey-cocktails", "Whiskey Cocktails", "DRINK", "Jack Daniel’s whiskey cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Section 117", sections: ["117"] }),
  bpItem(CF, CFT, "chase-avnet-home-plate-club", "chase-avnet-upscale-bar-menu", "Upscale Bar Menu", "OTHER", "Club-level upscale bites (menu varies).", { location: "Avnet Home Plate Club" }),
  bpItem(CF, CFT, "chase-avnet-home-plate-club", "chase-avnet-premium-cocktails", "Premium Cocktails", "DRINK", "Premium full-service bar cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Avnet Home Plate Club" }),
  bpItem(CF, CFT, "chase-big-dawgs", "chase-big-dawgs-sonoran-footlong", "Footlong Sonoran Style Dog", "HOT_DOG", "Sonoran-style footlong.", { location: "Sections 105, 324", sections: ["105", "324"] }),
  bpItem(CF, CFT, "chase-bat-flip-burgers", "chase-bat-flip-smash-burger", "Smash Burger", "BURGER", "Smashed patty burger.", { location: "Section 118", sections: ["118"] }),
  bpItem(CF, CFT, "chase-bat-flip-burgers", "chase-bat-flip-beyond-burger", "Vegan Beyond Burger", "VEGAN", "Plant-based Beyond patty.", { location: "Section 118", sections: ["118"] }),

  bpItem(AA, AAT, "angels-walk-off-waffles", "angels-dubai-chocolate-strawberry-waffle", "Dubai Chocolate Strawberry Waffle", "DESSERT", "Belgian waffle with chocolate cream, strawberries, pistachio cream, crispy phyllo.", { location: "Section 232", sections: ["232"] }),
  bpItem(AA, AAT, "angels-la-caguama", "angels-la-caguama-chicken-sandwich", "La Caguama Chicken Sandwich", "CHICKEN", "Fried chicken with beer glaze, jalapeño slaw, lime aioli.", { location: "Section 260", sections: ["260"] }),
  bpItem(AA, AAT, "angels-crafty-mac-mash", "angels-pork-chile-verde-mac", "Pork Chile Verde Mac & Cheese", "OTHER", "Mac topped with braised pork, tomatillo-chili sauce, queso fresco, pickled onions.", { location: "Section 237", sections: ["237"] }),
  bpItem(AA, AAT, "angels-first-base-food-court", "angels-jalapeno-sausage-roll", "Jalapeño Sausage Roll", "HOT_DOG", "Sausage with onion jam and cheddar wrapped in puff pastry.", { location: "1st Base Food Court" }),
  bpItem(AA, AAT, "angels-premium-levels", "angels-fried-mortadella-panini", "Fried Mortadella Panini", "SANDWICH", "Fried mortadella panini (suites & premium levels).", { location: "Suites & premium levels" }),
  bpItem(AA, AAT, "angels-pac-man-chomp-stop", "angels-pac-man-soft-serve", "Pac-Man Soft Serve", "DESSERT", "Pineapple Dole Whip in Pac-Man helmet.", { location: "Right field pavilion" }),
  bpItem(AA, AAT, "angels-pac-man-chomp-stop", "angels-ghost-themed-treats", "Ghost-Themed Treats", "DESSERT", "Flavored Rice Krispie treats and cookies.", { location: "Right field pavilion" }),
  bpItem(AA, AAT, "angels-pac-man-chomp-stop", "angels-power-pellet-popcorn", "Power Pellet Popcorn", "SNACK", "Mystery flavor candy popcorn.", { location: "Right field pavilion" }),
  bpItem(AA, AAT, "angels-classic-hits", "angels-classic-helmet-nachos", "Helmet Nachos", "TACOS", "Souvenir helmet with chips, cheese, jalapeños, sour cream, carne asada or chicken tinga.", { location: "Multiple sections" }),
  bpItem(AA, AAT, "angels-chronic-tacos", "angels-chronic-carne-burrito-bowl", "Carne Asada Burrito Bowl", "TACOS", "Build-your-own burrito bowl.", { location: "Sections 211, 420; 1st Base Food Court", sections: ["211", "420"] }),
  bpItem(AA, AAT, "angels-chronic-tacos", "angels-chronic-custom-tacos", "Custom Tacos", "TACOS", "Build-your-own tacos.", { location: "Sections 211, 420; 1st Base Food Court", sections: ["211", "420"] }),
  bpItem(AA, AAT, "angels-brewery-x", "angels-brewery-x-chicken-waffle", "Chicken & Waffle Sandwich", "CHICKEN", "Club-level chicken and waffle sandwich.", { location: "Club level" }),
  bpItem(AA, AAT, "angels-brewery-x", "angels-brewery-x-short-rib-stroganoff", "Braised Beef Short Rib Stroganoff", "OTHER", "Rich stroganoff over noodles or mash.", { location: "Club level" }),
  bpItem(AA, AAT, "angels-brewery-x", "angels-brewery-x-craft-beer", "Craft Beer", "DRINK", "Brewery X house and guest taps.", { ...alc, beverageStyle: "Beer", location: "Club level" }),
  bpItem(AA, AAT, "angels-crafty-dogs", "angels-cali-dog", "Cali Dog", "HOT_DOG", "Hot dog with carne asada, fries, pico de gallo.", { location: "1st Base Food Court" }),
  bpItem(AA, AAT, "angels-cathys-cookies", "angels-cathys-cookie-bucket", "Cookie Bucket", "DESSERT", "Warm cookies in bucket.", { location: "Multiple locations" }),
  bpItem(AA, AAT, "angels-cathys-cookies", "angels-cathys-cookie-sleeve", "Cookie Sleeve", "DESSERT", "Cookie sleeve to go.", { location: "Multiple locations" }),
  bpItem(AA, AAT, "angels-pacifico-porch", "angels-pacifico-lemon-pepper-wings", "Lemon Pepper Chicken Wings", "CHICKEN", "Lemon pepper wings.", { location: "Lower view level" }),
  bpItem(AA, AAT, "angels-pacifico-porch", "angels-pacifico-mexican-import-beer", "Mexican Import Beer", "DRINK", "Pacifico and Mexican import lineup.", { ...alc, beverageStyle: "Beer", location: "Lower view level" }),
  bpItem(AA, AAT, "angels-truly-terrace", "angels-truly-hard-seltzer", "Hard Seltzer", "DRINK", "Truly hard seltzer.", { ...alc, beverageStyle: "Seltzer", location: "Upper level" }),
  bpItem(AA, AAT, "angels-truly-terrace", "angels-truly-michelada-float", "Michelada Float", "DRINK", "Michelada float build.", { ...alc, beverageStyle: "Cocktail", location: "Upper level" }),
  bpItem(AA, AAT, "angels-lexus-diamond-club", "angels-ldc-visiting-team-menu", "Visiting Team Menu", "OTHER", "Rotating menu themed to visiting team.", { location: "Lexus Diamond Club" }),
  bpItem(AA, AAT, "angels-casa-modelo", "angels-casa-build-quesadilla", "Build-Your-Own Quesadilla", "TACOS", "Quesadilla station with toppings.", { location: "Section 260", sections: ["260"] }),
  bpItem(AA, AAT, "angels-casa-modelo", "angels-casa-build-burrito", "Build-Your-Own Burrito", "TACOS", "Burrito station with fillings.", { location: "Section 260", sections: ["260"] }),
  bpItem(AA, AAT, "angels-healthy-options", "angels-vegan-mac-buffalo-cauliflower", "Vegan Mac & Cheese Buffalo Cauliflower Bowl", "VEGAN", "Plant-based mac with Buffalo cauliflower.", { location: "Section 125", sections: ["125"] }),
  bpItem(AA, AAT, "angels-healthy-options", "angels-pink-pineapple-cup", "Pink Pineapple Cup", "SNACK", "Fresh pineapple cup.", { location: "Section 125", sections: ["125"] }),
  bpItem(AA, AAT, "angels-healthy-options", "angels-mediterranean-spring-salad", "Mediterranean Spring Salad", "VEGAN", "Mediterranean-style greens salad.", { location: "Section 125", sections: ["125"] }),

  bpItem(OP, OPT, "giants-sf-selects", "giants-peruchin-sandwich", "Peruchín Sandwich", "SANDWICH", "Jerk chicken with plantain slaw and mango salsa on Dutch Crunch.", { location: "Scoreboard Plaza" }),
  bpItem(OP, OPT, "giants-sf-selects", "giants-birria-loaded-grilled-cheese", "Birria Loaded Grilled Cheese", "SANDWICH", "Sourdough grilled in birria consommé with braised beef and dipping broth.", { location: "Scoreboard Plaza" }),
  bpItem(OP, OPT, "giants-say-hey-sausage", "giants-char-siu-dog", "Char Siu Dog", "HOT_DOG", "Footlong dog with char siu glaze, Kewpie mayo, fried onions, green onions.", { location: "Section 125", sections: ["125"] }),
  bpItem(OP, OPT, "giants-lucky-fries", "giants-lucky-fries-item", "Lucky Fries", "SNACK", "Waffle fries with braised short rib, pickled onions, orange secret sauce.", { location: "Section 128", sections: ["128"] }),
  bpItem(OP, OPT, "giants-999-package", "giants-999-hot-dogs-beer-flights", "9 Hot Dogs and 9 Beer Flights", "HOT_DOG", "Large-format package: nine hot dogs paired with nine beer flight pours.", { location: "Concourse", tags: [OPT, "Challenge / package; verify availability"] }),
  bpItem(OP, OPT, "giants-pacific-eats", "giants-pacific-bulgogi-bowl", "Bulgogi Beef Rice Bowl", "OTHER", "Bulgogi beef over rice with sides.", { location: "Section 127", sections: ["127"] }),
  bpItem(OP, OPT, "giants-pacific-eats", "giants-pacific-sriracha-chicken-bowl", "Sriracha Chicken Rice Bowl", "CHICKEN", "Sriracha-glazed chicken rice bowl.", { location: "Section 127", sections: ["127"] }),
  bpItem(OP, OPT, "giants-pacific-eats", "giants-pacific-marinated-tofu-bowl", "Marinated Tofu Rice Bowl", "VEGAN", "Marinated tofu rice bowl.", { location: "Section 127", sections: ["127"] }),
  bpItem(OP, OPT, "giants-pacific-eats", "giants-pacific-banh-mi", "Ballpark Banh Mi", "SANDWICH", "Vietnamese-style banh mi.", { location: "Section 127", sections: ["127"] }),
  bpItem(OP, OPT, "giants-crazy-crabz", "giants-dungeness-crab-sandwich", "Dungeness Crab Sandwich", "SEAFOOD", "Dungeness crab sandwich (Crazy Crab’z).", { location: "Center field" }),
  bpItem(OP, OPT, "giants-orlandos-caribbean-bbq", "giants-orlandos-cha-cha-bowl", "Cha Cha Bowl", "BBQ", "Rice, beans, jerk chicken.", { location: "Promenade 142; View 314" }),
  bpItem(OP, OPT, "giants-gils-garlic-fries", "giants-gils-garlic-fries-item", "Garlic Fries", "SNACK", "Gil’s garlic fries.", { location: "Multiple sections" }),
  bpItem(OP, OPT, "giants-gils-garlic-fries", "giants-gils-garlic-fries-helmet", "Garlic Fries Helmet", "SNACK", "Garlic fries in souvenir helmet.", { location: "Multiple sections" }),
  bpItem(OP, OPT, "giants-the-garden", "giants-garden-kale-smoothie", "Kale Smoothie", "DRINK", "Green kale smoothie.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Center field" }),
  bpItem(OP, OPT, "giants-the-garden", "giants-garden-roasted-veg-flatbread", "Roasted Vegetable Flatbread", "VEGAN", "Roasted vegetable flatbread.", { location: "Center field" }),
  bpItem(OP, OPT, "giants-tony-gemignani-slice", "giants-tony-thin-crust-slice", "Thin-Crust Pizza Slice", "PIZZA", "Tony Gemignani thin-crust slice.", { location: "Section 129", sections: ["129"] }),
  bpItem(OP, OPT, "giants-doggie-diner-express", "giants-sheboygan-brat", "Sheboygan Bratwurst", "HOT_DOG", "Sheboygan-style brat.", { location: "Section 121", sections: ["121"] }),
  bpItem(OP, OPT, "giants-doggie-diner-express", "giants-doggie-tenders", "Chicken Tenders", "CHICKEN", "Chicken tenders basket.", { location: "Section 121", sections: ["121"] }),
  bpItem(OP, OPT, "giants-mission-street-taqueria", "giants-mission-burrito", "Mission Burrito", "TACOS", "Mission-style burrito.", { location: "Section 110", sections: ["110"] }),
  bpItem(OP, OPT, "giants-mission-street-taqueria", "giants-mission-helmet-nachos", "Helmet Nachos", "TACOS", "Helmet nachos with toppings.", { location: "Section 110", sections: ["110"] }),
  bpItem(OP, OPT, "giants-the-carvery", "giants-carvery-turkey-sandwich", "Turkey Sandwich", "SANDWICH", "Carved turkey sandwich.", { location: "Section 114", sections: ["114"] }),
  bpItem(OP, OPT, "giants-the-carvery", "giants-carvery-brisket-sandwich", "Brisket Sandwich", "BBQ", "Sliced brisket sandwich.", { location: "Section 114", sections: ["114"] }),
  bpItem(OP, OPT, "giants-chick-fil-a-portables", "giants-cfa-portable-sandwich", "Chicken Sandwich", "CHICKEN", "Chick-fil-A portable chicken sandwich.", { location: "Portable stands" }),
  bpItem(OP, OPT, "giants-athletic-brewing", "giants-athletic-run-wild", "Run Wild IPA Non-Alcoholic Beer", "DRINK", "Athletic Brewing NA IPA.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Multiple sections" }),
  bpItem(OP, OPT, "giants-murphs-irish-pub", "giants-murphs-irish-coffee", "Irish Coffee", "DRINK", "Hot Irish coffee.", { ...alc, beverageStyle: "Cocktail", location: "Section 112", sections: ["112"] }),
  bpItem(OP, OPT, "giants-fountain-cocktail-stands", "giants-mini-cooler-cup-drink", "Mini Cooler Cup Drink", "DRINK", "Frozen or fountain drink in mini cooler souvenir cup.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Multiple" }),

  bpItem(CO, COT, "rockies-fanfare", "rockies-glizzilla", "Glizzilla", "HOT_DOG", "Massive two-foot-long hot dog on a custom baguette.", { location: "Section 157", sections: ["157"] }),
  bpItem(CO, COT, "rockies-pizza-donuts", "rockies-pizza-donuts-item", "Pizza Donuts", "PIZZA", "Glazed donuts griddled with garlic butter, marinara, mozzarella, pepperoni, pesto.", { location: "Section 109", sections: ["109"] }),
  bpItem(CO, COT, "rockies-sandlot-brewery", "rockies-sandlot-taco-momalona", "Taco Momalona", "TACOS", "Smoked brisket, pork belly, cheese, cabbage, BBQ sauce, Flamin’ Hot Cheetos.", { location: "Section 113", sections: ["113"] }),
  bpItem(CO, COT, "rockies-sandlot-brewery", "rockies-sandlot-craft-beer", "Craft Beer", "DRINK", "SandLot Brewery drafts.", { ...alc, beverageStyle: "Beer", location: "Section 113", sections: ["113"] }),
  bpItem(CO, COT, "rockies-sandlot-brewery", "rockies-sandlot-premium-bbq", "Premium BBQ", "BBQ", "SandLot BBQ plates and specials.", { location: "Section 113", sections: ["113"] }),
  bpItem(CO, COT, "rockies-dessert-stand", "rockies-dubai-cinnamon-roll", "Dubai Cinnamon Roll", "DESSERT", "Cinnamon roll with chocolate, ice cream, pistachio, kataifi.", { location: "Concourse" }),
  bpItem(CO, COT, "rockies-999-challenge-bundle", "rockies-999-mini-dogs-beer", "9 Mini Hot Dogs and 9 Beer Flights", "HOT_DOG", "Challenge bundle with mini dogs and beer flights.", { location: "Concourse", tags: [COT, "TODO: Confirm stand location / seasonality"] }),
  bpItem(CO, COT, "rockies-biker-jims", "rockies-biker-elk-jalapeno-cheddar", "Elk Jalapeño Cheddar Sausage", "HOT_DOG", "Elk sausage with jalapeño cheddar.", { location: "Sections 107, 331", sections: ["107", "331"] }),
  bpItem(CO, COT, "rockies-biker-jims", "rockies-biker-jackalope", "Jackalope Sausage", "HOT_DOG", "Jackalope sausage on bun.", { location: "Sections 107, 331", sections: ["107", "331"] }),
  bpItem(CO, COT, "rockies-biker-jims", "rockies-biker-bacon-wrapped-cheddar", "Bacon-Wrapped Cheddar Dog", "HOT_DOG", "Bacon-wrapped cheddar dog.", { location: "Sections 107, 331", sections: ["107", "331"] }),
  bpItem(CO, COT, "rockies-helton-burger", "rockies-helton-burger-item", "Helton Burger", "BURGER", "Named Rockies burger.", { location: "Section 153", sections: ["153"] }),
  bpItem(CO, COT, "rockies-helton-burger", "rockies-helton-hand-scooped-shake", "Hand-Scooped Shake", "DESSERT", "Hand-scooped milkshake.", { location: "Section 153", sections: ["153"] }),
  bpItem(CO, COT, "rockies-birdcall", "rockies-birdcall-chicken-sandwich", "Chicken Sandwich", "CHICKEN", "Birdcall crispy chicken sandwich.", { location: "The Rooftop" }),
  bpItem(CO, COT, "rockies-birdcall", "rockies-birdcall-nuggets", "Chicken Nuggets", "CHICKEN", "Crispy nuggets.", { location: "The Rooftop" }),
  bpItem(CO, COT, "rockies-birdcall", "rockies-birdcall-loaded-tots", "Loaded Tater Tots", "SNACK", "Loaded tots.", { location: "The Rooftop" }),
  bpItem(CO, COT, "rockies-rocky-mountain-oysters", "rockies-rmo-plate", "Rocky Mountain Oysters", "OTHER", "Regional fried specialty.", { location: "Section 144", sections: ["144"] }),
  bpItem(CO, COT, "rockies-polidori-sausage", "rockies-polidori-hatch-green-chile", "Hatch Green Chile Sausage", "HOT_DOG", "Hatch green chile sausage.", { location: "Sections 107, 149, 321", sections: ["107", "149", "321"] }),
  bpItem(CO, COT, "rockies-polidori-sausage", "rockies-polidori-jalapeno-cheddar", "Jalapeño Cheddar Sausage", "HOT_DOG", "Jalapeño cheddar sausage.", { location: "Sections 107, 149, 321", sections: ["107", "149", "321"] }),
  bpItem(CO, COT, "rockies-smashburger", "rockies-smash-double-classic", "Double Classic Smash", "BURGER", "Double classic smashburger.", { location: "Section 303; The Rooftop", sections: ["303"] }),
  bpItem(CO, COT, "rockies-smashburger", "rockies-smash-tots", "Smash Tots", "SNACK", "Smash-style seasoned tots.", { location: "Section 303; The Rooftop", sections: ["303"] }),
  bpItem(CO, COT, "rockies-the-rooftop", "rockies-rooftop-silver-bullet-drinks", "Silver Bullet Bar Drinks", "DRINK", "Coors Light and rooftop bar drinks.", { ...alc, beverageStyle: "Beer", location: "Section 303", sections: ["303"] }),
  bpItem(CO, COT, "rockies-mountain-ranch-bar-grille", "rockies-mountain-ranch-ayce-buffet", "All-You-Can-Eat Buffet", "OTHER", "Right-field all-you-can-eat buffet (ticketed areas; verify access).", { location: "Right field", tags: [COT, "TODO: Confirm ticket / section access rules"] }),
  bpItem(CO, COT, "rockies-cookie-creamery", "rockies-boozy-ice-cream", "Boozy Ice Cream", "DESSERT", "Spirits-infused ice cream.", { ...alc, beverageStyle: "Cocktail", location: "Section 119", sections: ["119"] }),
  bpItem(CO, COT, "rockies-infield-greens", "rockies-infield-build-salad", "Build-Your-Own Salad", "VEGAN", "Custom greens bowl.", { location: "Section 120", sections: ["120"] }),
  bpItem(CO, COT, "rockies-gluten-friendly-stand", "rockies-gf-hot-dog", "Gluten-Free Hot Dog", "GLUTEN_FREE", "GF bun hot dog.", { location: "Section 143", sections: ["143"] }),
  bpItem(CO, COT, "rockies-gluten-friendly-stand", "rockies-gf-burger", "Gluten-Free Burger", "GLUTEN_FREE", "GF bun burger.", { location: "Section 143", sections: ["143"] }),
  bpItem(CO, COT, "rockies-gluten-friendly-stand", "rockies-gf-chicken-sandwich", "Gluten-Free Chicken Sandwich", "GLUTEN_FREE", "GF chicken sandwich.", { location: "Section 143", sections: ["143"] }),
  bpItem(CO, COT, "rockies-gluten-friendly-stand", "rockies-gf-beer", "Gluten-Free Beer", "DRINK", "GF beer options.", { ...alc, beverageStyle: "Beer", location: "Section 143", sections: ["143"] }),
  bpItem(CO, COT, "rockies-gluten-friendly-stand", "rockies-gf-hard-cider", "Hard Cider", "DRINK", "Hard cider on tap or can.", { ...alc, beverageStyle: "Other", location: "Section 143", sections: ["143"] }),
  bpItem(CO, COT, "rockies-505-burrito-bowls", "rockies-505-veg-burrito-bowl", "Vegetarian Burrito Bowl", "VEGAN", "Vegetarian burrito bowl build.", { location: "Section 134", sections: ["134"] }),

  bpItem(NP, NPT, "nats-roaming-rooster", "nats-dc-monument-chicken-tower", "DC Monument Chicken Tower", "CHICKEN", "Massive fried chicken sandwich with bacon and chipotle ranch.", { location: "Section 239", sections: ["239"] }),
  bpItem(NP, NPT, "nats-roaming-rooster", "nats-roaming-fried-chicken-sandwich", "Fried Chicken Sandwich", "CHICKEN", "Roaming Rooster fried chicken sandwich.", { location: "Section 239", sections: ["239"] }),
  bpItem(NP, NPT, "nats-chesapeake-crab-cake", "nats-crab-mac-cheese-dog", "Crab Mac & Cheese Dog", "HOT_DOG", "Hot dog with mac & cheese, Maryland crab, Old Bay.", { location: "Section 109", sections: ["109"] }),
  bpItem(NP, NPT, "nats-capitol-slugger", "nats-capitol-slugger-dog", "Capitol Slugger", "HOT_DOG", "Half-smoke with beef chili, jalapeños, onions, beer cheese.", { location: "Section 114", sections: ["114"] }),
  bpItem(NP, NPT, "nats-fuzzies-burgers", "nats-fuzzy-smash-burger", "Fuzzy Smash Burger", "BURGER", "Fuzzies smash-style burger.", { location: "Section 106", sections: ["106"] }),
  bpItem(NP, NPT, "nats-eatopian-eats", "nats-ethiopian-vegan-nachos", "Ethiopian Vegan Nachos", "VEGAN", "Berbere-spiced vegan nacho build.", { location: "Section 136", sections: ["136"] }),
  bpItem(NP, NPT, "nats-bens-chili-bowl", "nats-bens-original-half-smoke", "Original Chili Half-Smoke", "HOT_DOG", "Ben’s half-smoke with chili.", { location: "Sections 110, 141, 238, 307", sections: ["110", "141", "238", "307"] }),
  bpItem(NP, NPT, "nats-rocklands-bbq", "nats-rocklands-texas-brisket", "Texas Brisket Sandwich", "BBQ", "Texas-style brisket sandwich.", { location: "Section 118", sections: ["118"] }),
  bpItem(NP, NPT, "nats-rocklands-bbq", "nats-rocklands-jalapeno-cornbread", "Jalapeño Cornbread", "SNACK", "Jalapeño cornbread side.", { location: "Section 118", sections: ["118"] }),
  bpItem(NP, NPT, "nats-arepa-zone", "nats-arepa-pabellon", "Pabellon Arepa", "GLUTEN_FREE", "Shredded beef, beans, sweet plantain in arepa (naturally corn-based shell; verify prep).", { location: "Sections 148, 304", sections: ["148", "304"] }),
  bpItem(NP, NPT, "nats-capo-deli", "nats-capo-special", "Capo Special", "SANDWICH", "Capo Deli signature hoagie.", { location: "Section 136", sections: ["136"] }),
  bpItem(NP, NPT, "nats-capo-deli", "nats-fauci-pouchy-cocktail", "Fauci Pouchy Cocktail", "DRINK", "Named cocktail pouch (menu varies).", { ...alc, beverageStyle: "Cocktail", location: "Section 136", sections: ["136"] }),
  bpItem(NP, NPT, "nats-ssongs-korean-corn-dogs", "nats-ssongs-korean-corn-dog", "Korean Corn Dog", "HOT_DOG", "Crispy potato or rice-flour K-dog.", { location: "Sections 130, 305", sections: ["130", "305"] }),
  bpItem(NP, NPT, "nats-coneacopia", "nats-nats-red-waffle-cone", "Nats Red Waffle Cone", "DESSERT", "Red velvet-style waffle cone with ice cream.", { location: "Section 136", sections: ["136"] }),
  bpItem(NP, NPT, "nats-don-churro", "nats-don-churro-filled", "Filled Churros", "DESSERT", "Hot filled churros.", { location: "Sections 113, 309", sections: ["113", "309"] }),
  bpItem(NP, NPT, "nats-don-churro", "nats-don-churro-dugout-dozen", "Dugout Dozen Churros", "DESSERT", "Twelve-count churro box.", { location: "Sections 113, 309", sections: ["113", "309"] }),
  bpItem(NP, NPT, "nats-capital-candy-jar", "nats-chocolate-oreos", "Chocolate-Covered Oreos", "DESSERT", "Hand-dipped chocolate Oreos.", { location: "Section 139", sections: ["139"] }),
  bpItem(NP, NPT, "nats-capital-candy-jar", "nats-giant-lollipops", "Giant Lollipops", "DESSERT", "Oversized lollipops.", { location: "Section 139", sections: ["139"] }),
  bpItem(NP, NPT, "nats-ritas-italian-ice", "nats-ritas-italian-ice-item", "Italian Ice", "DESSERT", "Rita’s Italian ice / gelati.", { location: "Multiple sections" }),
  bpItem(NP, NPT, "nats-electric-cool-aid", "nats-electric-frozen-gin-tonic", "Frozen Gin & Tonic", "DRINK", "Frozen G&T.", { ...alc, beverageStyle: "Cocktail", location: "Sections 102, 143", sections: ["102", "143"] }),
  bpItem(NP, NPT, "nats-electric-cool-aid", "nats-electric-frozen-cocktails", "Frozen Cocktails", "DRINK", "Rotating frozen cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Sections 102, 143", sections: ["102", "143"] }),
  bpItem(NP, NPT, "nats-budweiser-terrace", "nats-bud-terrace-beer", "Beer", "DRINK", "Budweiser Terrace draft and cans.", { ...alc, beverageStyle: "Beer", location: "Section 243", sections: ["243"] }),
  bpItem(NP, NPT, "nats-district-drafts", "nats-district-local-craft-beer", "Local Craft Beer", "DRINK", "DC-area craft beer taps.", { ...alc, beverageStyle: "Beer", location: "Multiple sections" }),
  bpItem(NP, NPT, "nats-ultra-loft", "nats-ultra-upscale-snacks", "Upscale Snacks", "SNACK", "ULTRA Loft premium snacks.", { location: "Section 242", sections: ["242"] }),
  bpItem(NP, NPT, "nats-ultra-loft", "nats-ultra-beer", "Beer", "DRINK", "ULTRA Loft beer selection.", { ...alc, beverageStyle: "Beer", location: "Section 242", sections: ["242"] }),
  bpItem(NP, NPT, "nats-silver-bullet-bar", "nats-silver-bullet-cocktails", "Cocktails", "DRINK", "Silver Bullet Bar cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Section 104", sections: ["104"] }),
  bpItem(NP, NPT, "nats-melissas-field-of-greens", "nats-melissas-fresh-salad", "Fresh Salad", "VEGAN", "Fresh produce salads.", { location: "Section 136", sections: ["136"] }),
  bpItem(NP, NPT, "nats-melissas-field-of-greens", "nats-melissas-plant-protein-bowl", "Plant-Based Protein Bowl", "VEGAN", "Plant protein grain bowl.", { location: "Section 136", sections: ["136"] }),
  bpItem(NP, NPT, "nats-char-bar", "nats-char-kosher-hot-dog", "Kosher Hot Dog", "HOT_DOG", "Glatt kosher hot dog.", { location: "Section 143", sections: ["143"] }),
  bpItem(NP, NPT, "nats-char-bar", "nats-char-kosher-burger", "Kosher Burger", "BURGER", "Glatt kosher burger.", { location: "Section 143", sections: ["143"] }),
  bpItem(NP, NPT, "nats-char-bar", "nats-char-pastrami-sandwich", "Pastrami Sandwich", "SANDWICH", "Kosher pastrami sandwich.", { location: "Section 143", sections: ["143"] }),
  bpItem(NP, NPT, "nats-avoiding-gluten-cart", "nats-avoiding-gluten-bun", "Gluten-Free Bun Option", "GLUTEN_FREE", "GF bun add-on for compatible items.", { location: "Section 148", sections: ["148"] }),
  bpItem(NP, NPT, "nats-avoiding-gluten-cart", "nats-avoiding-gluten-snacks", "Gluten-Free Snacks", "GLUTEN_FREE", "Packaged GF snacks.", { location: "Section 148", sections: ["148"] }),
  bpItem(NP, NPT, "nats-avoiding-gluten-cart", "nats-avoiding-gluten-cider", "Hard Cider", "DRINK", "Hard cider.", { ...alc, beverageStyle: "Other", location: "Section 148", sections: ["148"] }),

  bpItem(LP, LPT, "marlins-classics-con-sazon", "marlins-the-machete", "The Machete", "TACOS", "Two-foot tortilla with mozzarella, Oaxaca cheese, carne asada, guajillo sauce, salsa verde.", { location: "Section 10", sections: ["10"] }),
  bpItem(LP, LPT, "marlins-mister-softee", "marlins-mister-softee-cone", "Soft Serve Ice Cream", "DESSERT", "Mister Softee soft serve cone or cup.", { location: "Promenade and Vista levels" }),
  bpItem(LP, LPT, "marlins-the-change-up", "marlins-change-up-sushi-sake", "Sushi Sake Roll", "SEAFOOD", "Rotating sushi item at The Change Up.", { location: "Section 1", sections: ["1"], tags: [LPT, "Rotating menu"] }),
  bpItem(LP, LPT, "marlins-the-change-up", "marlins-change-up-mac-bowl", "House of Mac Bowl", "OTHER", "Mac-and-cheese bowl concept.", { location: "Section 1", sections: ["1"], tags: [LPT, "Rotating menu"] }),
  bpItem(LP, LPT, "marlins-the-change-up", "marlins-change-up-taco-rico", "Taco Rico Taco", "TACOS", "Taco Rico taco build.", { location: "Section 1", sections: ["1"], tags: [LPT, "Rotating menu"] }),
  bpItem(LP, LPT, "marlins-the-change-up", "marlins-change-up-central-park", "Central Park Food Station Item", "OTHER", "Themed station item (menu rotates).", { location: "Section 1", sections: ["1"], tags: [LPT, "TODO: Map exact dish name when menu published"] }),
  bpItem(LP, LPT, "marlins-the-change-up", "marlins-change-up-berry-farm", "Berry Farm Dessert", "DESSERT", "Berry-forward dessert cup or shortcake.", { location: "Section 1", sections: ["1"], tags: [LPT, "Rotating menu"] }),
  bpItem(LP, LPT, "marlins-cocktail-stands", "marlins-cafecito-martini", "Cafecito Martini", "DRINK", "Cuban coffee-inspired martini.", { ...alc, beverageStyle: "Cocktail", location: "Multiple" }),
  bpItem(LP, LPT, "marlins-cocktail-stands", "marlins-marlins-mule", "Marlins Mule", "DRINK", "Miami-style mule.", { ...alc, beverageStyle: "Cocktail", location: "Multiple" }),
  bpItem(LP, LPT, "marlins-the-press-box", "marlins-press-box-cuban", "Cuban Sandwich", "SANDWICH", "Pressed Cuban sandwich.", { location: "Section 28", sections: ["28"] }),
  bpItem(LP, LPT, "marlins-the-press-box", "marlins-305-value-menu-item", "305 Value Menu Item", "OTHER", "Rotating value menu plate from Press Box window.", { location: "Section 28", sections: ["28"], tags: [LPT, "Value menu"] }),
  bpItem(LP, LPT, "marlins-oppo-taco-goya", "marlins-oppo-chilaquiles-nachos", "Chilaquiles Nachos", "TACOS", "Chilaquiles-style nachos (Goya).", { location: "Section 8", sections: ["8"] }),
  bpItem(LP, LPT, "marlins-oppo-taco-goya", "marlins-oppo-quesadilla", "Quesadilla", "TACOS", "Build-your-own quesadilla.", { location: "Section 8", sections: ["8"] }),
  bpItem(LP, LPT, "marlins-oppo-taco-goya", "marlins-oppo-street-tacos", "Street Tacos", "TACOS", "Street-style tacos.", { location: "Section 8", sections: ["8"] }),
  bpItem(LP, LPT, "marlins-suviche", "marlins-suviche-sushi-roll", "Sushi Roll", "SEAFOOD", "SuViche sushi roll selection.", { location: "Section 210", sections: ["210"] }),
  bpItem(LP, LPT, "marlins-suviche", "marlins-suviche-ceviche", "Ceviche", "SEAFOOD", "Chilled ceviche cup or plate.", { location: "Section 210", sections: ["210"] }),
  bpItem(LP, LPT, "marlins-magic-city-bbq", "marlins-magic-hickory-pork-nachos", "Hickory Slow-Smoked Pork Nachos", "BBQ", "Pulled pork nachos.", { location: "Section 8", sections: ["8"] }),
  bpItem(LP, LPT, "marlins-magic-city-bbq", "marlins-magic-shredded-pork-sandwich", "Shredded Pork Sandwich", "BBQ", "Shredded pork sandwich.", { location: "Section 8", sections: ["8"] }),
  bpItem(LP, LPT, "marlins-beisbowl", "marlins-beisbowl-chicken-rice", "Chicken Rice Bowl", "OTHER", "Chicken rice bowl.", { location: "Section 28", sections: ["28"] }),
  bpItem(LP, LPT, "marlins-beisbowl", "marlins-beisbowl-steak-rice", "Steak Rice Bowl", "OTHER", "Steak rice bowl.", { location: "Section 28", sections: ["28"] }),
  bpItem(LP, LPT, "marlins-beisbowl", "marlins-beisbowl-tofu-rice", "Tofu Rice Bowl", "VEGAN", "Marinated tofu rice bowl.", { location: "Section 28", sections: ["28"] }),
  bpItem(LP, LPT, "marlins-coffee-counter", "marlins-cafecito", "Cafecito", "DRINK", "Cuban cafecito shot or cup.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Section 34", sections: ["34"] }),
  bpItem(LP, LPT, "marlins-coffee-counter", "marlins-colada", "Colada", "DRINK", "Cuban colada for sharing.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Section 34", sections: ["34"] }),
  bpItem(LP, LPT, "marlins-coffee-counter", "marlins-croquette", "Croquette", "SNACK", "Cuban-style croquettes.", { location: "Section 34", sections: ["34"] }),
  bpItem(LP, LPT, "marlins-coffee-counter", "marlins-empanada", "Empanada", "SNACK", "Baked or fried empanadas.", { location: "Section 34", sections: ["34"] }),
  bpItem(LP, LPT, "marlins-familia-faves", "marlins-305-value-hot-dog", "305 Value Hot Dog", "HOT_DOG", "Value hot dog.", { location: "Section 36", sections: ["36"] }),
  bpItem(LP, LPT, "marlins-familia-faves", "marlins-305-value-popcorn", "305 Value Popcorn", "SNACK", "Value popcorn.", { location: "Section 36", sections: ["36"] }),
  bpItem(LP, LPT, "marlins-familia-faves", "marlins-305-value-water", "305 Value Water", "DRINK", "Bottled water.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Section 36", sections: ["36"] }),
  bpItem(LP, LPT, "marlins-familia-faves", "marlins-305-value-pretzel", "305 Value Pretzel", "SNACK", "Value pretzel.", { location: "Section 36", sections: ["36"] }),
  bpItem(LP, LPT, "marlins-familia-faves", "marlins-305-value-draft-beer", "305 Value Draft Beer", "DRINK", "Value draft pour.", { ...alc, beverageStyle: "Beer", location: "Section 36", sections: ["36"] }),
  bpItem(LP, LPT, "marlins-familia-faves", "marlins-305-value-nachos", "305 Value Nachos", "SNACK", "Value nachos.", { location: "Section 36", sections: ["36"] }),
  bpItem(LP, LPT, "marlins-familia-faves", "marlins-305-value-cheeseburger", "305 Value Cheeseburger", "BURGER", "Value cheeseburger.", { location: "Section 36", sections: ["36"] }),
  bpItem(LP, LPT, "marlins-blue-moon-brewhall", "marlins-bmh-draft-beer", "Draft Beer", "DRINK", "Blue Moon Brew Hall drafts.", { ...alc, beverageStyle: "Beer", location: "Section 15", sections: ["15"] }),
  bpItem(LP, LPT, "marlins-blue-moon-brewhall", "marlins-bmh-local-craft-cans", "Local Craft Cans", "DRINK", "Local craft cans.", { ...alc, beverageStyle: "Beer", location: "Section 15", sections: ["15"] }),
  bpItem(LP, LPT, "marlins-bullpen-bar-grill", "marlins-bullpen-wings", "Wings", "CHICKEN", "Bullpen wings basket.", { location: "Left field corner" }),
  bpItem(LP, LPT, "marlins-bullpen-bar-grill", "marlins-bullpen-sliders", "Sliders", "BURGER", "Slider trio.", { location: "Left field corner" }),
  bpItem(LP, LPT, "marlins-bullpen-bar-grill", "marlins-bullpen-specialty-cocktails", "Specialty Cocktails", "DRINK", "Bullpen specialty cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Left field corner" }),
  bpItem(LP, LPT, "marlins-budweiser-bowtie-bar", "marlins-bowtie-beer", "Beer", "DRINK", "Bowtie bar draft and bottles.", { ...alc, beverageStyle: "Beer", location: "Skyline Terrace" }),
  bpItem(LP, LPT, "marlins-recess-sports-lounge", "marlins-recess-nachos", "Recess Nachos", "SNACK", "Loaded lounge nachos.", { location: "Recess Sports Lounge" }),
  bpItem(LP, LPT, "marlins-recess-sports-lounge", "marlins-recess-premium-spirits", "Premium Spirits", "DRINK", "Premium spirits pours.", { ...alc, beverageStyle: "Cocktail", location: "Recess Sports Lounge" }),
  bpItem(LP, LPT, "marlins-walk-off-market", "marlins-walk-off-cold-beer", "Cold Beer", "DRINK", "Grab-and-go cold beer.", { ...alc, beverageStyle: "Beer", location: "Section 24", sections: ["24"] }),
  bpItem(LP, LPT, "marlins-walk-off-market", "marlins-walk-off-flatbread", "Flatbread Pizza", "PIZZA", "Walk-Off Market flatbread pizza.", { location: "Section 24", sections: ["24"] }),
  bpItem(LP, LPT, "marlins-fowl-pole", "marlins-fowl-hot-chicken-sandwich", "Hot Chicken Sandwich", "CHICKEN", "Nashville-style hot chicken sandwich.", { location: "Section 5", sections: ["5"] }),
  bpItem(LP, LPT, "marlins-fowl-pole", "marlins-fowl-tenders", "Chicken Tenders", "CHICKEN", "Crispy tenders.", { location: "Section 5", sections: ["5"] }),
  bpItem(LP, LPT, "marlins-sahlens-top-dog", "marlins-sahlens-hot-dog", "Sahlen’s Hot Dog", "HOT_DOG", "Sahlen’s frank on bun.", { location: "Section 4", sections: ["4"] })
];
