import { bpItem, bpVendor } from "./ballpark-menu-builders";
import type { FoodItem, Vendor } from "./sample-data";

const W = "wrigley-field";
const WT = "Wrigley Field";
const F = "fenway-park";
const FT = "Fenway Park";
const D = "dodger-stadium";
const DT = "Dodger Stadium";
const P = "petco-park";
const PT = "Petco Park";
const C = "citizens-bank-park";
const CT = "Citizens Bank Park";

const alc = {
  itemType: "Alcoholic Drink" as const,
  alcoholic: true,
  ageRestricted: true
};

export const expansionBallparkVendors: Vendor[] = [
  bpVendor(W, "wrigley-double-diamond-waffle-fries", "Double Diamond Waffle Fries", "Field", "Section 126"),
  bpVendor(W, "wrigley-waveland-grill", "Waveland Grill", "Bleachers", "Bleachers"),
  bpVendor(W, "wrigley-tostada-stack", "Tostada Stack", "Field", "Section 105"),
  bpVendor(W, "wrigley-bao-wow-dog", "Bao Wow Dog", "Field", "Section 112"),
  bpVendor(W, "wrigley-milkshake-stand", "Milkshake Stand", "Concourse", "Location varies"),
  bpVendor(W, "wrigley-small-cheval", "Small Cheval", "Upper bleachers", "Section 514"),
  bpVendor(W, "wrigley-home-run-inn", "Home Run Inn Pizza", "Field", "Multiple sections"),
  bpVendor(W, "wrigley-clark-street-grill", "Clark Street Grill", "Field", "Section 112"),
  bpVendor(W, "wrigley-addison-street-grill", "Addison Street Grill", "Field", "Section 126"),
  bpVendor(W, "wrigley-chicago-dogs", "Chicago Dogs", "Field", "Sections 108, 115, 119"),
  bpVendor(W, "wrigley-budweiser-build-a-bar", "Budweiser Build-a-Bar", "Bleachers", "Lower bleachers"),
  bpVendor(W, "wrigley-wintrust-bar", "Wintrust Bar", "Concourse", "Left field concourse"),
  bpVendor(W, "wrigley-nutrl-patio", "Nutrl Patio", "Field", "Section 228"),
  bpVendor(W, "wrigley-sheffield-market", "Sheffield Market", "Field", "Section 134"),
  bpVendor(W, "wrigley-hattie-bs", "Hattie B’s Hot Chicken", "Gallagher Way", "Gallagher Way"),
  bpVendor(W, "wrigley-brickhouse-tavern", "Budweiser Brickhouse Tavern", "Gallagher Way", "Gallagher Way"),
  bpVendor(W, "wrigley-happy-camper", "Happy Camper", "Street", "Clark Street"),
  bpVendor(W, "wrigley-craft-map-portables", "Craft Map Portables", "Field", "Sections 118, 224, 314"),

  bpVendor(F, "fenway-lobstah-poutine", "Lobstah Poutine", "Field", "Section 110"),
  bpVendor(F, "fenway-specialty-dogs", "Specialty Dogs", "Concourse", "Multiple"),
  bpVendor(F, "fenway-spicy-cabot-grilled-cheese", "Spicy Cabot Grilled Cheese", "Field", "Section 108"),
  bpVendor(F, "fenway-green-monster-fries", "Green Monster Fries", "Concourse", "Big concourse"),
  bpVendor(F, "fenway-truly-terrace", "Truly Terrace", "Upper deck", "Upper right field"),
  bpVendor(F, "fenway-plant-based-stand", "Plant-Based Stand", "Concourse", "Multiple"),
  bpVendor(F, "fenway-lukes-lobster", "Luke’s Lobster", "Concourse", "Big concourse"),
  bpVendor(F, "fenway-regina-pizzeria", "Regina Pizzeria", "Field", "Multiple sections"),
  bpVendor(F, "fenway-savenors", "Savenor’s Butcher Shop", "Concourse", "Multiple"),
  bpVendor(F, "fenway-tasty-burger", "Tasty Burger", "Gate", "Near Gate C"),
  bpVendor(F, "fenway-north-end-cannoli", "North End Cannoli", "Field", "Section 114"),
  bpVendor(F, "fenway-bleacher-bar", "Bleacher Bar", "Bleachers", "Under Green Monster"),
  bpVendor(F, "fenway-royal-rooters", "Royal Rooter’s Club", "Club", "Club level"),
  bpVendor(F, "fenway-walk-thru-bru", "Walk-Thru Bru", "Concourse", "Big concourse"),
  bpVendor(F, "fenway-kayem", "Kayem", "Concourse", "Multiple"),
  bpVendor(F, "fenway-sausage-guy", "Sausage Guy", "Street", "Lansdowne Street"),
  bpVendor(F, "fenway-dels-lemonade", "Del’s Frozen Lemonade", "Field", "100 level carts"),

  bpVendor(D, "dodgers-grand-slam-burgers", "Grand Slam Burgers", "Reserve", "Reserve 12"),
  bpVendor(D, "dodgers-fan-fare-r4", "Fan Fare", "Reserve", "Reserve 4"),
  bpVendor(D, "dodgers-fan-fare-r31", "Fan Fare", "Reserve", "Reserve 31"),
  bpVendor(D, "dodgers-dh-hospitality", "DH Hospitality", "Field", "Field 8"),
  bpVendor(D, "dodgers-taco-stand", "Taco Stand", "Concourse", "Multiple"),
  bpVendor(D, "dodgers-habit-burger", "The Habit Burger & Grill", "Plaza", "Centerfield Plaza"),
  bpVendor(D, "dodgers-kings-hawaiian", "King’s Hawaiian", "Reserve", "Reserve 32"),
  bpVendor(D, "dodgers-la-taqueria", "LA Taqueria", "Loge / reserve", "Loge 106; Reserve 17"),
  bpVendor(D, "dodgers-think-blue-bbq", "Think Blue BBQ & Grill", "Outfield", "Left centerfield"),
  bpVendor(D, "dodgers-dueling-dogs", "Dueling Dogs", "Outfield", "Left centerfield"),
  bpVendor(D, "dodgers-dodger-dog-stands", "Dodger Dog Stands", "Concourse", "Multiple"),
  bpVendor(D, "dodgers-elysian-park-grill", "Elysian Park Grill", "Field / top deck", "Field 2; Top Deck 4"),
  bpVendor(D, "dodgers-corn-stand", "Corn Stand", "Concourse", "Multiple"),
  bpVendor(D, "dodgers-sweet-spot", "The Sweet Spot", "Field / loge", "Field 46; Loge 136"),
  bpVendor(D, "dodgers-dole-whip", "Dole Whip Stand", "Top deck", "Top Deck 4"),
  bpVendor(D, "dodgers-coffee-stand", "Coffee Stand", "Concourse", "Multiple"),
  bpVendor(D, "dodgers-margarita-stand", "Margarita Stand", "Concourse", "Multiple"),
  bpVendor(D, "dodgers-gold-glove-bar", "Gold Glove Bar", "Plaza", "Centerfield Plaza"),
  bpVendor(D, "dodgers-hornitos-cantina", "Hornitos Cantina", "Outfield", "Right centerfield"),
  bpVendor(D, "dodgers-think-blue-craft-beer", "Think Blue Craft Beer Bar", "Loge", "Loge 165"),

  bpVendor(P, "petco-coco-ichibanya", "Coco Ichibanya", "Mercado", "Mercado; Section 104"),
  bpVendor(P, "petco-pop-pie-co", "Pop Pie Co.", "Power Alley", "Section 129"),
  bpVendor(P, "petco-shortstop", "The Shortstop", "Field", "Section 100"),
  bpVendor(P, "petco-padre-pretzels", "Padre Pretzels", "Field", "Section 206"),
  bpVendor(P, "petco-seaside-market", "Seaside Market", "Field", "Section 105"),
  bpVendor(P, "petco-hodads", "Hodad’s", "Field", "Sections 104, 131, 230, 300"),
  bpVendor(P, "petco-puesto", "Puesto", "Field", "Sections 119, 120, 204"),
  bpVendor(P, "petco-carnitas-snack-shack", "Carnitas’ Snack Shack", "Field", "Sections 130, 319"),
  bpVendor(P, "petco-board-brew", "Board & Brew", "Field", "Section 211"),
  bpVendor(P, "petco-gaglione-brothers", "Gaglione Brothers", "Field", "Section 124"),
  bpVendor(P, "petco-deckmans-draft", "Deckman’s at the Draft", "Garden", "Garden level"),
  bpVendor(P, "petco-blue-water-seafood", "Blue Water Seafood", "Field", "Section 227"),
  bpVendor(P, "petco-blue-shield-club", "Blue Shield Club", "Field", "Section 108"),
  bpVendor(P, "petco-ans-gelato", "An’s Athletic Field Services", "Mercado", "Mercado"),
  bpVendor(P, "petco-mini-donut", "Mini Donut Company", "Field", "Section 107"),
  bpVendor(P, "petco-mostra-coffee", "Mostra Coffee", "Mercado", "Mercado"),
  bpVendor(P, "petco-teaspoon", "Teaspoon", "Plaza", "Gallagher Square"),
  bpVendor(P, "petco-stone-brewing", "Stone Brewing", "Field", "Section 309"),
  bpVendor(P, "petco-394-bar", "The .394 Bar", "Field", "Section 217"),
  bpVendor(P, "petco-diamond-room", "The Diamond Room", "District", "Ballpark District"),

  bpVendor(C, "phillies-campos", "Campo’s", "Alley", "Ashburn Alley"),
  bpVendor(C, "phillies-coca-cola-corner", "Coca-Cola Corner", "Concourse", "Multiple"),
  bpVendor(C, "phillies-wilts-berries", "Wilt’s Chocolate Smothered Berries", "Field", "Section 111"),
  bpVendor(C, "phillies-999-challenge", "9-9-9 Challenge Stand", "Field", "Section 128"),
  bpVendor(C, "phillies-chickies-petes", "Chickie’s & Pete’s", "Field / alley", "Ashburn Alley; Sections 126, 139, 208, 319"),
  bpVendor(C, "phillies-manco-pizza", "Manco & Manco Pizza", "Field / alley", "Ashburn Alley; Sections 110, 137, 204"),
  bpVendor(C, "phillies-federal-donuts", "Federal Donuts & Chicken", "Field", "Section 140"),
  bpVendor(C, "phillies-tony-lukes", "Tony Luke’s", "Alley", "Ashburn Alley"),
  bpVendor(C, "phillies-bulls-bbq", "Bull’s BBQ", "Plaza", "Left field plaza"),
  bpVendor(C, "phillies-freddys", "Freddy’s Frozen Custard & Steakburgers", "Field", "Section 126"),
  bpVendor(C, "phillies-1883-burger", "1883 Burger Co.", "Field", "Sections 109, 207, 323"),
  bpVendor(C, "phillies-hatfield-grills", "Hatfield Grills", "Concourse", "Multiple"),
  bpVendor(C, "phillies-pass-stow", "Pass and Stow", "Gate", "Third base gate"),
  bpVendor(C, "phillies-cocktail-stands", "Cocktail Stands", "Concourse", "Multiple"),
  bpVendor(C, "phillies-casamigos-bar", "Casamigos Bar", "Field", "Section 113"),
  bpVendor(C, "phillies-miller-lite-liberty", "Miller Lite Liberty Landing", "Upper deck", "Upper left field"),
  bpVendor(C, "phillies-greens-grains", "Greens & Grains", "Field", "Section 125"),
  bpVendor(C, "phillies-schar-stand", "Schär Gluten-Free Stand", "Field", "Section 122"),
  bpVendor(C, "phillies-kosher-grill", "Kosher Grill", "Field", "Section 124")
];

export const expansionBallparkFoodItems: FoodItem[] = [
  bpItem(W, WT, "wrigley-double-diamond-waffle-fries", "wrigley-double-diamond-fries", "Double Diamond waffle fries", "SNACK", "Waffle fries with braised beef short rib, fontina, bacon, mushrooms, fried onions.", { location: "Section 126", sections: ["126"] }),
  bpItem(W, WT, "wrigley-waveland-grill", "wrigley-chicken-churros", "Chicken & churros", "CHICKEN", "Fried chicken thighs with churros and ancho syrup.", { location: "Bleachers" }),
  bpItem(W, WT, "wrigley-tostada-stack", "wrigley-tostada-stack-item", "Tostada stack", "TACOS", "Tostadas with green chili beef, beans, queso fresco, pico, fried egg.", { location: "Section 105", sections: ["105"] }),
  bpItem(W, WT, "wrigley-bao-wow-dog", "wrigley-bao-wow-dog-item", "Bao Wow dog", "HOT_DOG", "Vienna Beef dog on bao bun with mustard slaw and tempura peppers.", { location: "Section 112", sections: ["112"] }),
  bpItem(W, WT, "wrigley-milkshake-stand", "wrigley-ballgame-milkshake", "Take Me Out to the Ballgame milkshake", "DESSERT", "Milkshake with caramel corn, mini churro, chocolate pretzel.", { location: "Concourse" }),
  bpItem(W, WT, "wrigley-small-cheval", "wrigley-small-cheval-double", "Double cheeseburger", "BURGER", "Small Cheval double cheeseburger.", { location: "Section 514", sections: ["514"] }),
  bpItem(W, WT, "wrigley-small-cheval", "wrigley-small-cheval-fries", "Fries", "SNACK", "Side fries.", { location: "Section 514", sections: ["514"] }),
  bpItem(W, WT, "wrigley-home-run-inn", "wrigley-hri-tavern-slice", "Tavern style pizza slice", "PIZZA", "Thin tavern-cut slice.", { location: "Multiple sections" }),
  bpItem(W, WT, "wrigley-clark-street-grill", "wrigley-clark-garlic-parm-fries", "Garlic parmesan steak fries", "GLUTEN_FREE", "Steak fries (GF menu item; verify prep).", { location: "Section 112", sections: ["112"], tags: [WT, "TODO: Confirm dedicated GF fryer"] }),
  bpItem(W, WT, "wrigley-clark-street-grill", "wrigley-clark-gf-burger", "Gluten-free burger", "GLUTEN_FREE", "GF burger build.", { location: "Section 112", sections: ["112"] }),
  bpItem(W, WT, "wrigley-clark-street-grill", "wrigley-clark-tenders", "Chicken tender basket", "CHICKEN", "Tenders basket.", { location: "Section 112", sections: ["112"] }),
  bpItem(W, WT, "wrigley-addison-street-grill", "wrigley-addison-big-w", "Big W burger", "BURGER", "Signature burger.", { location: "Section 126", sections: ["126"] }),
  bpItem(W, WT, "wrigley-addison-street-grill", "wrigley-addison-bison-dog", "Bison dog", "HOT_DOG", "Bison hot dog.", { location: "Section 126", sections: ["126"] }),
  bpItem(W, WT, "wrigley-chicago-dogs", "wrigley-chicago-style-dog", "Chicago style hot dog", "HOT_DOG", "Dragged through the garden style.", { location: "Sections 108, 115, 119", sections: ["108", "115", "119"] }),
  bpItem(W, WT, "wrigley-budweiser-build-a-bar", "wrigley-beer-bat", "Beer bat", "DRINK", "Beer served in souvenir bat vessel.", { ...alc, beverageStyle: "Beer", location: "Lower bleachers" }),
  bpItem(W, WT, "wrigley-wintrust-bar", "wrigley-wintrust-cocktails", "Premium cocktails", "DRINK", "Cocktail menu.", { ...alc, beverageStyle: "Cocktail", location: "Left field concourse" }),
  bpItem(W, WT, "wrigley-nutrl-patio", "wrigley-nutrl-seltzer", "Hard seltzer", "DRINK", "Hard seltzer lineup.", { ...alc, beverageStyle: "Seltzer", location: "Section 228", sections: ["228"] }),
  bpItem(W, WT, "wrigley-nutrl-patio", "wrigley-nutrl-vodka-soda", "Vodka soda", "DRINK", "Vodka soda build.", { ...alc, beverageStyle: "Cocktail", location: "Section 228", sections: ["228"] }),
  bpItem(W, WT, "wrigley-sheffield-market", "wrigley-sheffield-grab-go", "Grab-and-go snacks", "SNACK", "Market snacks.", { location: "Section 134", sections: ["134"] }),
  bpItem(W, WT, "wrigley-sheffield-market", "wrigley-sheffield-beer", "Beer", "DRINK", "Draft and cans.", { ...alc, beverageStyle: "Beer", location: "Section 134", sections: ["134"] }),
  bpItem(W, WT, "wrigley-hattie-bs", "wrigley-hattie-nashville-hot", "Nashville hot chicken", "CHICKEN", "Hattie B’s hot chicken.", { location: "Gallagher Way" }),
  bpItem(W, WT, "wrigley-brickhouse-tavern", "wrigley-brickhouse-tavern-food", "Tavern food", "OTHER", "Pub plates (menu varies).", { location: "Gallagher Way" }),
  bpItem(W, WT, "wrigley-brickhouse-tavern", "wrigley-brickhouse-beer", "Beer", "DRINK", "Draft beer.", { ...alc, beverageStyle: "Beer", location: "Gallagher Way" }),
  bpItem(W, WT, "wrigley-happy-camper", "wrigley-happy-camper-pizza", "Pizza", "PIZZA", "Happy Camper pizza.", { location: "Clark Street" }),
  bpItem(W, WT, "wrigley-happy-camper", "wrigley-happy-camper-cocktails", "Cocktails", "DRINK", "Craft cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Clark Street" }),
  bpItem(W, WT, "wrigley-craft-map-portables", "wrigley-goose-island-beer", "Goose Island beer", "DRINK", "Local draft / cans.", { ...alc, beverageStyle: "Beer", location: "Sections 118, 224, 314", sections: ["118", "224", "314"] }),
  bpItem(W, WT, "wrigley-craft-map-portables", "wrigley-half-acre-beer", "Half Acre beer", "DRINK", "Local draft / cans.", { ...alc, beverageStyle: "Beer", location: "Sections 118, 224, 314", sections: ["118", "224", "314"] }),
  bpItem(W, WT, "wrigley-craft-map-portables", "wrigley-revolution-beer", "Revolution Brewing beer", "DRINK", "Local draft / cans.", { ...alc, beverageStyle: "Beer", location: "Sections 118, 224, 314", sections: ["118", "224", "314"] }),

  bpItem(F, FT, "fenway-lobstah-poutine", "fenway-lobstah-poutine-item", "Lobstah poutine", "SEAFOOD", "Fries with lobster, chowder, bacon.", { location: "Section 110", sections: ["110"] }),
  bpItem(F, FT, "fenway-specialty-dogs", "fenway-surf-turf-dog", "Surf & turf dog", "HOT_DOG", "Kobe beef dog with lobster and bacon.", { location: "Concourse" }),
  bpItem(F, FT, "fenway-specialty-dogs", "fenway-boston-dog", "Boston dog", "HOT_DOG", "Specialty dog build.", { location: "Concourse" }),
  bpItem(F, FT, "fenway-specialty-dogs", "fenway-pitmaster-dog", "Pitmaster dog", "HOT_DOG", "BBQ-style dog.", { location: "Concourse" }),
  bpItem(F, FT, "fenway-specialty-dogs", "fenway-reuben-dog", "Reuben dog", "HOT_DOG", "Reuben toppings on a dog.", { location: "Concourse" }),
  bpItem(F, FT, "fenway-specialty-dogs", "fenway-pizza-dog", "Pizza dog", "HOT_DOG", "Pizza-topped dog.", { location: "Concourse" }),
  bpItem(F, FT, "fenway-spicy-cabot-grilled-cheese", "fenway-spicy-cabot-grilled-cheese-item", "Spicy Cabot grilled cheese", "SANDWICH", "Grilled cheese with spicy Cabot cheese.", { location: "Section 108", sections: ["108"] }),
  bpItem(F, FT, "fenway-green-monster-fries", "fenway-green-monster-fries-item", "Green Monster fries", "SNACK", "Loaded fries from Big Concourse stand.", { location: "Big concourse" }),
  bpItem(F, FT, "fenway-truly-terrace", "fenway-guinness-beef-stew", "Guinness beef stew", "OTHER", "Hearty stew cup.", { location: "Upper right field" }),
  bpItem(F, FT, "fenway-truly-terrace", "fenway-truly-seltzer", "Truly hard seltzer", "DRINK", "Hard seltzer.", { ...alc, beverageStyle: "Seltzer", location: "Upper right field" }),
  bpItem(F, FT, "fenway-truly-terrace", "fenway-angry-orchard-slushy", "Angry Orchard watermelon slushy", "DRINK", "Slushy cocktail.", { ...alc, beverageStyle: "Cocktail", location: "Upper right field" }),
  bpItem(F, FT, "fenway-plant-based-stand", "fenway-jackfruit-burger", "Jackfruit burger", "VEGAN", "Plant-based patty.", { location: "Concourse" }),
  bpItem(F, FT, "fenway-lukes-lobster", "fenway-lukes-lobster-roll", "Lobster roll", "SEAFOOD", "Maine-style roll.", { location: "Big concourse" }),
  bpItem(F, FT, "fenway-regina-pizzeria", "fenway-regina-cheese-slice", "Cheese pizza slice", "PIZZA", "Cheese slice.", { location: "Multiple sections" }),
  bpItem(F, FT, "fenway-regina-pizzeria", "fenway-regina-pepperoni-slice", "Pepperoni pizza slice", "PIZZA", "Pepperoni slice.", { location: "Multiple sections" }),
  bpItem(F, FT, "fenway-savenors", "fenway-savenors-burger", "Premium burger", "BURGER", "Butcher shop burger.", { location: "Concourse" }),
  bpItem(F, FT, "fenway-savenors", "fenway-savenors-sandwich", "Specialty sandwich", "SANDWICH", "Rotating sandwich.", { location: "Concourse" }),
  bpItem(F, FT, "fenway-tasty-burger", "fenway-big-tasty-burger", "Big Tasty burger", "BURGER", "Tasty Burger flagship.", { location: "Near Gate C" }),
  bpItem(F, FT, "fenway-tasty-burger", "fenway-shaft-shake", "Shaft shake", "DESSERT", "Thick shake.", { location: "Near Gate C" }),
  bpItem(F, FT, "fenway-north-end-cannoli", "fenway-north-end-cannoli-item", "Cannoli", "DESSERT", "North End style cannoli.", { location: "Section 114", sections: ["114"] }),
  bpItem(F, FT, "fenway-bleacher-bar", "fenway-bleacher-bar-beer", "Beer", "DRINK", "Draft and bottles.", { ...alc, beverageStyle: "Beer", location: "Under Green Monster" }),
  bpItem(F, FT, "fenway-bleacher-bar", "fenway-bleacher-bar-cocktails", "Cocktails", "DRINK", "Classic cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Under Green Monster" }),
  bpItem(F, FT, "fenway-royal-rooters", "fenway-royal-rooters-buffet", "Premium buffet", "OTHER", "Club buffet service.", { location: "Club" }),
  bpItem(F, FT, "fenway-walk-thru-bru", "fenway-cake-in-a-can", "Cake in a can", "DESSERT", "Novelty canned dessert.", { location: "Big concourse" }),
  bpItem(F, FT, "fenway-walk-thru-bru", "fenway-walk-thru-beer", "Beer", "DRINK", "Quick beer window.", { ...alc, beverageStyle: "Beer", location: "Big concourse" }),
  bpItem(F, FT, "fenway-kayem", "fenway-kayem-frank", "Fenway Frank", "HOT_DOG", "Classic Fenway Frank.", { location: "Concourse" }),
  bpItem(F, FT, "fenway-sausage-guy", "fenway-sausage-peppers-onions", "Sausage peppers and onions sandwich", "SANDWICH", "Lansdowne classic.", { location: "Lansdowne Street" }),
  bpItem(F, FT, "fenway-dels-lemonade", "fenway-dels-frozen-lemonade", "Frozen lemonade", "DRINK", "Del’s frozen lemonade cup.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "100 level carts" }),

  bpItem(D, DT, "dodgers-grand-slam-burgers", "dodgers-lunch-box-burger", "Lunch Box burger", "BURGER", "Burger with peanut butter, jelly, bacon, pepper jack.", { location: "Reserve 12" }),
  bpItem(D, DT, "dodgers-fan-fare-r4", "dodgers-chow-mein-burrito", "Chow mein burrito", "TACOS", "Fan fusion burrito.", { location: "Reserve 4" }),
  bpItem(D, DT, "dodgers-fan-fare-r31", "dodgers-fried-chicken-bucket", "Fried chicken bucket", "CHICKEN", "Shareable bucket.", { location: "Reserve 31" }),
  bpItem(D, DT, "dodgers-dh-hospitality", "dodgers-loco-moco-bowl", "Loco moco bowl", "OTHER", "Hawaiian-style bowl.", { location: "Field 8" }),
  bpItem(D, DT, "dodgers-taco-stand", "dodgers-cochinita-tacos", "Cochinita pibil bone marrow tacos", "TACOS", "Slow-cooked pork tacos.", { location: "Concourse" }),
  bpItem(D, DT, "dodgers-habit-burger", "dodgers-habit-charburger", "Charburger", "BURGER", "Char-grilled burger.", { location: "Centerfield Plaza" }),
  bpItem(D, DT, "dodgers-habit-burger", "dodgers-santa-barbara-sandwich", "Santa Barbara sandwich", "SANDWICH", "Cold sandwich favorite.", { location: "Centerfield Plaza" }),
  bpItem(D, DT, "dodgers-kings-hawaiian", "dodgers-kh-char-siu-fries", "Char siu pork loaded fries", "SNACK", "Sweet-savory loaded fries.", { location: "Reserve 32" }),
  bpItem(D, DT, "dodgers-kings-hawaiian", "dodgers-kh-wing-platter", "Korean wing platter", "CHICKEN", "Wing platter.", { location: "Reserve 32" }),
  bpItem(D, DT, "dodgers-kings-hawaiian", "dodgers-kh-garlic-fry-helmet", "Garlic fry helmet", "SNACK", "Garlic fries in souvenir helmet.", { location: "Reserve 32" }),
  bpItem(D, DT, "dodgers-la-taqueria", "dodgers-carne-asada-nacho-helmet", "Carne asada nacho helmet", "TACOS", "Loaded nacho helmet.", { location: "Loge 106; Reserve 17", sections: ["106", "17"] }),
  bpItem(D, DT, "dodgers-la-taqueria", "dodgers-potato-taquitos", "Potato taquitos", "TACOS", "Crispy potato taquitos.", { location: "Loge 106; Reserve 17", sections: ["106", "17"] }),
  bpItem(D, DT, "dodgers-think-blue-bbq", "dodgers-bbq-brisket-nachos", "BBQ brisket nachos", "BBQ", "Smoked brisket over nachos.", { location: "Left centerfield" }),
  bpItem(D, DT, "dodgers-think-blue-bbq", "dodgers-smoked-wings", "Smoked wings", "CHICKEN", "BBQ smoked wings.", { location: "Left centerfield" }),
  bpItem(D, DT, "dodgers-dueling-dogs", "dodgers-specialty-hot-dogs", "Specialty hot dogs", "HOT_DOG", "Rotating loaded dogs.", { location: "Left centerfield" }),
  bpItem(D, DT, "dodgers-dodger-dog-stands", "dodgers-dodger-dog", "Dodger Dog", "HOT_DOG", "Foot-long park classic.", { location: "Multiple" }),
  bpItem(D, DT, "dodgers-elysian-park-grill", "dodgers-elysian-garlic-fry-helmet", "Garlic fry helmet", "SNACK", "Garlic fries in helmet (Field / Top Deck).", { location: "Field 2; Top Deck 4" }),
  bpItem(D, DT, "dodgers-corn-stand", "dodgers-cheeto-lote", "Cheeto-lote", "SNACK", "Elote-style cup with Cheetos.", { location: "Concourse" }),
  bpItem(D, DT, "dodgers-sweet-spot", "dodgers-churro-sundae-helmet", "Churro sundae helmet", "DESSERT", "Churro sundae in helmet.", { location: "Field 46; Loge 136" }),
  bpItem(D, DT, "dodgers-dole-whip", "dodgers-pineapple-dole-whip", "Pineapple Dole Whip", "DESSERT", "Classic pineapple whip.", { location: "Top Deck 4" }),
  bpItem(D, DT, "dodgers-dole-whip", "dodgers-boozy-dole-whip", "Boozy Dole Whip", "DRINK", "Spiked pineapple whip.", { ...alc, beverageStyle: "Cocktail", location: "Top Deck 4" }),
  bpItem(D, DT, "dodgers-coffee-stand", "dodgers-cookies-cream-cold-brew", "Cookies & cream cold brew", "DRINK", "Sweet cold brew.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Concourse" }),
  bpItem(D, DT, "dodgers-margarita-stand", "dodgers-spicy-watermelon-margarita", "Spicy watermelon habanero margarita", "DRINK", "Frozen-style margarita.", { ...alc, beverageStyle: "Cocktail", location: "Concourse" }),
  bpItem(D, DT, "dodgers-gold-glove-bar", "dodgers-gold-glove-beer", "Beer", "DRINK", "Draft lineup.", { ...alc, beverageStyle: "Beer", location: "Centerfield Plaza" }),
  bpItem(D, DT, "dodgers-gold-glove-bar", "dodgers-gold-glove-cocktails", "Cocktails", "DRINK", "Full bar cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Centerfield Plaza" }),
  bpItem(D, DT, "dodgers-hornitos-cantina", "dodgers-hornitos-tequila-cocktails", "Tequila cocktails", "DRINK", "Cantina cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Right centerfield" }),
  bpItem(D, DT, "dodgers-hornitos-cantina", "dodgers-hornitos-tacos", "Tacos", "TACOS", "Cantina taco plates.", { location: "Right centerfield" }),
  bpItem(D, DT, "dodgers-think-blue-craft-beer", "dodgers-golden-road-beer", "Golden Road beer", "DRINK", "Local craft draft.", { ...alc, beverageStyle: "Beer", location: "Loge 165", sections: ["165"] }),
  bpItem(D, DT, "dodgers-think-blue-craft-beer", "dodgers-805-beer", "805 beer", "DRINK", "Draft 805.", { ...alc, beverageStyle: "Beer", location: "Loge 165", sections: ["165"] }),

  bpItem(P, PT, "petco-coco-ichibanya", "petco-curry-rice", "Curry rice", "OTHER", "Japanese curry plate.", { location: "Mercado; Section 104", sections: ["104"] }),
  bpItem(P, PT, "petco-coco-ichibanya", "petco-curry-bun", "Curry bun", "SNACK", "Baked curry bun.", { location: "Mercado; Section 104", sections: ["104"] }),
  bpItem(P, PT, "petco-coco-ichibanya", "petco-keema-cheese-fries", "Keema cheese fries", "SNACK", "Curry keema over fries.", { location: "Mercado; Section 104", sections: ["104"] }),
  bpItem(P, PT, "petco-coco-ichibanya", "petco-garlic-naan", "Garlic naan", "OTHER", "Garlic naan side.", { location: "Mercado; Section 104", sections: ["104"] }),
  bpItem(P, PT, "petco-pop-pie-co", "petco-chicken-pot-pie", "Classic chicken pot pie", "CHICKEN", "Baked pot pie.", { location: "Power Alley; Section 129", sections: ["129"] }),
  bpItem(P, PT, "petco-pop-pie-co", "petco-green-hog-pie", "Green hog & cheese pie", "SANDWICH", "Savory hand pie.", { location: "Power Alley; Section 129", sections: ["129"] }),
  bpItem(P, PT, "petco-shortstop", "petco-shortstop-sandwich", "Shortstop sandwich", "SANDWICH", "Named club sandwich.", { location: "Section 100", sections: ["100"] }),
  bpItem(P, PT, "petco-shortstop", "petco-short-rib-chili-dog", "Short rib chili cheese dog", "HOT_DOG", "Loaded dog.", { location: "Section 100", sections: ["100"] }),
  bpItem(P, PT, "petco-padre-pretzels", "petco-buffalo-pretzel", "Buffalo pretzel", "SNACK", "Spicy pretzel twist.", { location: "Section 206", sections: ["206"] }),
  bpItem(P, PT, "petco-padre-pretzels", "petco-honey-mustard-pretzel", "Honey mustard pretzel", "SNACK", "Sweet mustard pretzel.", { location: "Section 206", sections: ["206"] }),
  bpItem(P, PT, "petco-padre-pretzels", "petco-smores-pretzel", "S’mores pretzel", "DESSERT", "Chocolate-marshmallow pretzel.", { location: "Section 206", sections: ["206"] }),
  bpItem(P, PT, "petco-seaside-market", "petco-cardiff-crack-trip-tip", "Cardiff Crack tri-tip", "BBQ", "Famous tri-tip cut.", { location: "Section 105", sections: ["105"] }),
  bpItem(P, PT, "petco-seaside-market", "petco-tri-tip-nachos", "Tri-tip nachos", "BBQ", "Loaded tri-tip nachos.", { location: "Section 105", sections: ["105"] }),
  bpItem(P, PT, "petco-hodads", "petco-hodads-bacon-cheeseburger", "Bacon cheeseburger", "BURGER", "Hodad’s classic.", { location: "Sections 104, 131, 230, 300", sections: ["104", "131", "230", "300"] }),
  bpItem(P, PT, "petco-puesto", "petco-puesto-al-pastor", "Chicken al pastor taco", "TACOS", "Al pastor on corn tortilla.", { location: "Sections 119, 120, 204", sections: ["119", "120", "204"] }),
  bpItem(P, PT, "petco-puesto", "petco-puesto-crispy-cheese-taco", "Crispy melted cheese taco", "TACOS", "Cheese-crusted taco.", { location: "Sections 119, 120, 204", sections: ["119", "120", "204"] }),
  bpItem(P, PT, "petco-carnitas-snack-shack", "petco-triple-threat-sandwich", "Triple threat sandwich", "SANDWICH", "Loaded sandwich.", { location: "Sections 130, 319", sections: ["130", "319"] }),
  bpItem(P, PT, "petco-carnitas-snack-shack", "petco-loaded-carnitas-tots", "Loaded carnitas tots", "SNACK", "Totchos with carnitas.", { location: "Sections 130, 319", sections: ["130", "319"] }),
  bpItem(P, PT, "petco-board-brew", "petco-turkado-sandwich", "Turkado sandwich", "SANDWICH", "Turkey-avocado club.", { location: "Section 211", sections: ["211"] }),
  bpItem(P, PT, "petco-gaglione-brothers", "petco-gaglione-cheesesteak", "Cheesesteak", "SANDWICH", "Philly-style steak.", { location: "Section 124", sections: ["124"] }),
  bpItem(P, PT, "petco-gaglione-brothers", "petco-gaglione-garlic-fries", "Garlic fries", "SNACK", "Garlic parmesan fries.", { location: "Section 124", sections: ["124"] }),
  bpItem(P, PT, "petco-deckmans-draft", "petco-deckmans-fish-taco", "Market fish taco", "SEAFOOD", "Catch of the day taco.", { location: "Garden level" }),
  bpItem(P, PT, "petco-deckmans-draft", "petco-deckmans-shrimp-ceviche", "Shrimp ceviche", "SEAFOOD", "Chilled ceviche cup.", { location: "Garden level" }),
  bpItem(P, PT, "petco-blue-water-seafood", "petco-bwf-fish-tacos", "Fish tacos", "SEAFOOD", "Grilled or fried fish tacos.", { location: "Section 227", sections: ["227"] }),
  bpItem(P, PT, "petco-blue-water-seafood", "petco-bwf-fish-sandwich", "Fish sandwich", "SEAFOOD", "Crispy fish sandwich.", { location: "Section 227", sections: ["227"] }),
  bpItem(P, PT, "petco-blue-shield-club", "petco-blue-shield-steak-sandwich", "Steak sandwich", "SANDWICH", "Club-level steak sandwich.", { location: "Section 108", sections: ["108"] }),
  bpItem(P, PT, "petco-blue-shield-club", "petco-blue-shield-portobello-taco", "Smoked portobello taco", "VEGAN", "Plant-forward taco.", { location: "Section 108", sections: ["108"] }),
  bpItem(P, PT, "petco-ans-gelato", "petco-ans-vanilla-gelato", "Vanilla bean gelato", "DESSERT", "Cup or cone.", { location: "Mercado" }),
  bpItem(P, PT, "petco-ans-gelato", "petco-ans-chocolate-gelato", "Dark chocolate gelato", "DESSERT", "Cup or cone.", { location: "Mercado" }),
  bpItem(P, PT, "petco-mini-donut", "petco-mini-donut-glazed", "Glazed mini donuts", "DESSERT", "Warm mini donuts.", { location: "Section 107", sections: ["107"] }),
  bpItem(P, PT, "petco-mini-donut", "petco-mini-donut-cinnamon", "Cinnamon sugar mini donuts", "DESSERT", "Dusted minis.", { location: "Section 107", sections: ["107"] }),
  bpItem(P, PT, "petco-mostra-coffee", "petco-mostra-cold-brew", "Cold brew coffee", "DRINK", "Mostra cold brew.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Mercado" }),
  bpItem(P, PT, "petco-mostra-coffee", "petco-mostra-espresso", "Espresso", "DRINK", "Espresso shot or drink.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Mercado" }),
  bpItem(P, PT, "petco-teaspoon", "petco-teaspoon-thai-tea-boba", "Thai tea boba", "DRINK", "Thai tea with pearls.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Gallagher Square" }),
  bpItem(P, PT, "petco-teaspoon", "petco-teaspoon-mango-boba", "Mango on Fire boba", "DRINK", "Spicy-mango boba drink.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Gallagher Square" }),
  bpItem(P, PT, "petco-stone-brewing", "petco-stone-craft-beer", "Craft beer", "DRINK", "Stone and guest taps.", { ...alc, beverageStyle: "Beer", location: "Section 309", sections: ["309"] }),
  bpItem(P, PT, "petco-394-bar", "petco-394-pale-ale", ".394 pale ale", "DRINK", "Tony Gwynn tribute ale.", { ...alc, beverageStyle: "Beer", location: "Section 217", sections: ["217"] }),
  bpItem(P, PT, "petco-diamond-room", "petco-dirtiest-martini", "Dirtiest martini", "DRINK", "Olive-heavy martini.", { ...alc, beverageStyle: "Cocktail", location: "Ballpark District" }),

  bpItem(C, CT, "phillies-campos", "phillies-campos-sweeper-cheesesteak", "The Sweeper cheesesteak", "SANDWICH", "Campo’s steak sandwich.", { location: "Ashburn Alley" }),
  bpItem(C, CT, "phillies-coca-cola-corner", "phillies-sanchez-sliders", "Sánchez sliders", "CHICKEN", "Chicken sliders (named special).", { location: "Concourse" }),
  bpItem(C, CT, "phillies-coca-cola-corner", "phillies-schwarbomb-sundae", "Schwarbomb sundae", "DESSERT", "Ice cream sundae special.", { location: "Concourse" }),
  bpItem(C, CT, "phillies-wilts-berries", "phillies-chocolate-strawberries", "Chocolate covered strawberries", "DESSERT", "Fresh berries dipped to order.", { location: "Section 111", sections: ["111"] }),
  bpItem(C, CT, "phillies-999-challenge", "phillies-999-mini-dogs", "9 mini hot dogs", "HOT_DOG", "Challenge tray of nine dogs.", { location: "Section 128", sections: ["128"] }),
  bpItem(C, CT, "phillies-999-challenge", "phillies-999-beer-flight", "Beer flight", "DRINK", "Sample flight.", { ...alc, beverageStyle: "Beer", location: "Section 128", sections: ["128"] }),
  bpItem(C, CT, "phillies-chickies-petes", "phillies-crabfries", "Crabfries", "SNACK", "Crab-seasoned fries (Chickie’s & Pete’s).", { location: "Ashburn Alley; multiple sections", sections: ["126", "139", "208", "319"] }),
  bpItem(C, CT, "phillies-manco-pizza", "phillies-manco-boardwalk-slice", "Boardwalk pizza slice", "PIZZA", "Manco boardwalk-style slice.", { location: "Ashburn Alley; multiple sections", sections: ["110", "137", "204"] }),
  bpItem(C, CT, "phillies-federal-donuts", "phillies-federal-chicken-sandwich", "Chicken sandwich", "CHICKEN", "Federal fried chicken sandwich.", { location: "Section 140", sections: ["140"] }),
  bpItem(C, CT, "phillies-federal-donuts", "phillies-federal-donuts", "Fresh donuts", "DESSERT", "Hot fresh donuts.", { location: "Section 140", sections: ["140"] }),
  bpItem(C, CT, "phillies-tony-lukes", "phillies-tony-lukes-cheesesteak", "Cheesesteak", "SANDWICH", "Tony Luke’s steak.", { location: "Ashburn Alley" }),
  bpItem(C, CT, "phillies-tony-lukes", "phillies-tony-lukes-roast-pork", "Roast pork sandwich", "SANDWICH", "Broccoli rabe and sharp prov optional.", { location: "Ashburn Alley" }),
  bpItem(C, CT, "phillies-bulls-bbq", "phillies-bulls-bbq-sampler", "BBQ sampler platter", "BBQ", "Greg Luzinski smokehouse platter.", { location: "Left field plaza" }),
  bpItem(C, CT, "phillies-freddys", "phillies-freddys-steakburger", "Steakburger", "BURGER", "Thin-patty steakburger.", { location: "Section 126", sections: ["126"] }),
  bpItem(C, CT, "phillies-freddys", "phillies-freddys-custard", "Frozen custard", "DESSERT", "Concrete or cone.", { location: "Section 126", sections: ["126"] }),
  bpItem(C, CT, "phillies-1883-burger", "phillies-1883-smash-burger", "Smash burger", "BURGER", "Smashed patty burger.", { location: "Sections 109, 207, 323", sections: ["109", "207", "323"] }),
  bpItem(C, CT, "phillies-hatfield-grills", "phillies-hatfield-footlong-dog", "Footlong dog", "HOT_DOG", "Hatfield footlong (source listed “Phootlong”; verify signage).", { location: "Concourse", tags: [CT, "TODO: Verify Hatfield dog name on printed menu"] }),
  bpItem(C, CT, "phillies-pass-stow", "phillies-pass-stow-draft", "Local draft beer", "DRINK", "Rotating local drafts.", { ...alc, beverageStyle: "Beer", location: "Third base gate" }),
  bpItem(C, CT, "phillies-pass-stow", "phillies-pass-stow-pizza", "Pizza", "PIZZA", "Pass and Stow pizza slice.", { location: "Third base gate" }),
  bpItem(C, CT, "phillies-cocktail-stands", "phillies-red-october-punch", "Red October punch carafe", "DRINK", "Large-format punch.", { ...alc, beverageStyle: "Cocktail", location: "Concourse" }),
  bpItem(C, CT, "phillies-casamigos-bar", "phillies-casamigos-margaritas", "Margaritas", "DRINK", "Casamigos margarita menu.", { ...alc, beverageStyle: "Cocktail", location: "Section 113", sections: ["113"] }),
  bpItem(C, CT, "phillies-casamigos-bar", "phillies-casamigos-tequila-cocktails", "Tequila cocktails", "DRINK", "Premium tequila drinks.", { ...alc, beverageStyle: "Cocktail", location: "Section 113", sections: ["113"] }),
  bpItem(C, CT, "phillies-miller-lite-liberty", "phillies-miller-lite-beer", "Miller Lite beer", "DRINK", "Macro draft and cans.", { ...alc, beverageStyle: "Beer", location: "Upper left field" }),
  bpItem(C, CT, "phillies-greens-grains", "phillies-vegan-gyro", "Vegan gyro", "VEGAN", "Plant-based gyro wrap.", { location: "Section 125", sections: ["125"] }),
  bpItem(C, CT, "phillies-greens-grains", "phillies-buffalo-chkn-hoagie", "Buffalo chk’n hoagie", "VEGAN", "Plant-based buffalo hoagie.", { location: "Section 125", sections: ["125"] }),
  bpItem(C, CT, "phillies-greens-grains", "phillies-black-bean-burger", "Black bean burger", "VEGAN", "Veggie patty burger.", { location: "Section 125", sections: ["125"] }),
  bpItem(C, CT, "phillies-schar-stand", "phillies-schar-gf-cheesesteak", "Gluten-free cheesesteak", "GLUTEN_FREE", "Schär GF roll cheesesteak.", { location: "Section 122", sections: ["122"] }),
  bpItem(C, CT, "phillies-schar-stand", "phillies-schar-gf-hot-dog", "Gluten-free hot dog", "GLUTEN_FREE", "GF bun dog.", { location: "Section 122", sections: ["122"] }),
  bpItem(C, CT, "phillies-schar-stand", "phillies-schar-gf-brownie", "Gluten-free brownie", "GLUTEN_FREE", "Packaged GF brownie.", { location: "Section 122", sections: ["122"] }),
  bpItem(C, CT, "phillies-kosher-grill", "phillies-kosher-hot-dog", "Kosher hot dog", "HOT_DOG", "Kosher dog on bun.", { location: "Section 124", sections: ["124"] }),
  bpItem(C, CT, "phillies-kosher-grill", "phillies-knish", "Knish", "OTHER", "Potato knish.", { location: "Section 124", sections: ["124"] }),
  bpItem(C, CT, "phillies-kosher-grill", "phillies-kosher-brisket-sandwich", "Pulled brisket sandwich", "BBQ", "Smoked brisket sandwich.", { location: "Section 124", sections: ["124"] })
];
