import { bpItem, bpVendor } from "./ballpark-menu-builders";
import type { FoodItem, Vendor } from "./sample-data";

const KC = "kauffman-stadium";
const KCT = "Kauffman Stadium";
const CF = "citi-field";
const CFT = "Citi Field";
const NYY = "yankee-stadium";
const NYYT = "Yankee Stadium";
const GABP = "great-american-ball-park";
const GABPT = "Great American Ball Park";
const PROG = "progressive-field";
const PROGT = "Progressive Field";
const RC = "rogers-centre";
const RCT = "Rogers Centre";

const alc = {
  itemType: "Alcoholic Drink" as const,
  alcoholic: true,
  ageRestricted: true
};

/** Wave 6 MLB concessions — Kauffman, Citi Field, Yankee Stadium, GABP, Progressive Field, Rogers Centre. */
export const wave6BallparkVendors: Vendor[] = [
  bpVendor(KC, "kauff-hot-dog-wellington", "Hot Dog Wellington", "Upper", "Section 230"),
  bpVendor(KC, "kauff-korean-pork-cutlet", "Korean Pork Cutlet", "Upper", "Section 214"),
  bpVendor(KC, "kauff-big-cat-court", "Big Cat Court", "Concourse", "Big Cat Court"),
  bpVendor(KC, "kauff-smores-quesadilla", "S’mores Quesadilla", "Field", "Section 104"),
  bpVendor(KC, "kauff-tiramisu-helmet", "Tiramisu Helmet", "Upper", "Section 221"),
  bpVendor(KC, "kauff-hawaiian-bros", "Hawaiian Bros", "Club", "UMB Diamond Club"),
  bpVendor(KC, "kauff-italian-sausage-co", "Italian Sausage Co.", "Upper", "Section 234"),
  bpVendor(KC, "kauff-kcq", "KCQ", "Upper", "Section 216", "Local Craft BBQ hub rotates KC pitmasters monthly."),
  bpVendor(KC, "kauff-chickie-petes", "Chickie & Pete’s", "Upper", "Section 216"),
  bpVendor(KC, "kauff-andys-frozen-custard", "Andy’s Frozen Custard", "Upper", "Section 221"),
  bpVendor(KC, "kauff-9-9-9-challenge", "9-9-9 Challenge", "Upper", "Section 247"),
  bpVendor(KC, "kauff-double-dip-hoagies", "Double Dip Hoagies", "Upper", "Section 247"),
  bpVendor(KC, "kauff-beer-bat-cooler-cup-stands", "Beer Bat and Cooler Cup Stands", "Concourse", "Multiple locations", "TODO: Map exact stand sections."),
  bpVendor(KC, "kauff-rivals-sports-bar", "Rivals Sports Bar", "Outfield", "Right field"),
  bpVendor(KC, "kauff-quiktrip-fountain-deck", "QuikTrip Fountain Deck", "Outfield", "Right field", "TODO: Confirm AYCE / beverage package access and rules."),
  bpVendor(KC, "kauff-miller-lite-fountain-bar", "Miller Lite Fountain Bar", "Outfield", "Left-center field"),
  bpVendor(KC, "kauff-blue-moon-taproom", "Blue Moon Taproom", "Upper deck", "On top of Rivals Sports Bar"),
  bpVendor(KC, "kauff-dirty-sodas", "Dirty Sodas", "Concourse", "Various locations"),
  bpVendor(KC, "kauff-value-menu-stands", "Value Menu Stands", "Field / upper", "Sections 120, 135, 201, 213"),
  bpVendor(KC, "kauff-plant-based-kiosks", "Plant-Based Kiosks", "Upper", "200 level"),
  bpVendor(KC, "kauff-brew-and-view", "Brew & View", "Upper", "Section 401"),

  bpVendor(CF, "citi-adam-richman-burger-hof", "Adam Richman’s Burger Hall of Fame", "Field", "Section 105"),
  bpVendor(CF, "citi-the-queensboro", "The Queensboro", "Market", "Taste of Queens"),
  bpVendor(CF, "citi-pig-beach-bbq", "Pig Beach BBQ", "Field", "Section 135"),
  bpVendor(CF, "citi-seoul-bird", "Seoul Bird", "Market", "Metro Market"),
  bpVendor(CF, "citi-metropolitan-fry-factory", "Metropolitan Fry Factory", "Concourse", "Location not listed in source", "TODO: Confirm fry factory stand sections."),
  bpVendor(CF, "citi-pat-lafrieda", "Pat LaFrieda Meat Purveyors", "Field", "Section 139"),
  bpVendor(CF, "citi-legacy-catering-mookie-wilson", "Legacy Catering by Mookie Wilson", "Market", "Taste of the City"),
  bpVendor(CF, "citi-chef-kwame-patty-palace", "Chef Kwame’s Patty Palace", "Upper", "Section 415"),
  bpVendor(CF, "citi-amazin-deli", "Amazin’ Deli", "Field / upper", "Sections 131, 414"),
  bpVendor(CF, "citi-fuku", "Fuku", "Field", "Section 130"),
  bpVendor(CF, "citi-shake-shack", "Shake Shack", "Market", "Taste of the City"),
  bpVendor(CF, "citi-hildebrandts-ice-cream", "Hildebrandt’s Ice Cream", "Concourse", "Multiple locations"),
  bpVendor(CF, "citi-chop-house", "Chop House", "Concourse", "Location not listed in source", "TODO: Confirm Chop House dessert stand footprint."),
  bpVendor(CF, "citi-cookie-crumz", "Cookie Crumz", "Field / upper", "Sections 119, 336"),
  bpVendor(CF, "citi-dole-whip", "Dole Whip", "Concourse", "Multiple sections"),
  bpVendor(CF, "citi-9-9-9-challenge", "9-9-9 Challenge", "Field", "Section 128"),
  bpVendor(CF, "citi-bases-loaded-lemonade", "Bases Loaded Lemonade", "Field / upper", "Sections 114, 416"),
  bpVendor(CF, "citi-boozy-buckets", "Boozy Buckets", "Field / upper", "Sections 114, 416"),
  bpVendor(CF, "citi-willets-point-brewery", "Willets Point Brewery", "Field", "Section 110"),
  bpVendor(CF, "citi-milagro-tequila-porch", "Milagro Tequila Porch", "Outfield", "Location not listed in source", "TODO: Confirm porch section / access."),
  bpVendor(CF, "citi-vegan-city", "Vegan City", "Field", "Section 105"),
  bpVendor(CF, "citi-prime-kosher-sports", "Prime Kosher Sports", "Field", "Section 114", "Certified Glatt Kosher; closed Friday evenings and Saturdays."),
  bpVendor(CF, "citi-gluten-friendly", "Gluten-Friendly", "Field / upper", "Sections 105, 416"),

  bpVendor(NYY, "yanks-legends-global", "Legends Global", "Field", "Section 127"),
  bpVendor(NYY, "yanks-kings-hawaiian", "King’s Hawaiian", "Field", "Section 115"),
  bpVendor(NYY, "yanks-lobels", "Lobel’s", "Field", "Section 134"),
  bpVendor(NYY, "yanks-christian-petroni-parm", "Christian Petroni’s Parm to Table", "Field", "Section 125"),
  bpVendor(NYY, "yanks-streetbird", "Streetbird", "Field", "Section 112"),
  bpVendor(NYY, "yanks-mister-softee", "Mister Softee", "Concourse", "Multiple locations"),
  bpVendor(NYY, "yanks-brooklyn-dumpling-shop", "Brooklyn Dumpling Shop", "Field", "Section 123"),
  bpVendor(NYY, "yanks-fuku", "Fuku", "Field / upper", "Sections 213, 321"),
  bpVendor(NYY, "yanks-nuchas-empanadas", "Nuchas Empanadas", "Field / upper", "Sections 107, 305"),
  bpVendor(NYY, "yanks-the-99-burger", "The 99 Burger", "Upper", "Section 223"),
  bpVendor(NYY, "yanks-magnolia-bakery", "Magnolia Bakery", "Concourse", "Sections 106, 223, 311"),
  bpVendor(NYY, "yanks-treathouse", "Treathouse", "Field", "Section 106"),
  bpVendor(NYY, "yanks-stadium-bars", "Stadium Bars", "Concourse", "Multiple bars"),
  bpVendor(NYY, "yanks-aspen-vodka-party-deck", "Aspen Vodka Party Deck", "Upper", "Section 328"),
  bpVendor(NYY, "yanks-stella-artois-landing", "Stella Artois Landing", "Upper", "Section 232"),
  bpVendor(NYY, "yanks-michelob-ultra-clubhouse", "Michelob ULTRA Clubhouse", "Upper", "Section 207"),
  bpVendor(NYY, "yanks-diamond-deal", "Diamond Deal", "Field / upper", "Sections 105, 311"),
  bpVendor(NYY, "yanks-pinstripe-power-pack", "Pinstripe Power Pack", "Concourse", "Participating locations", "Kids bundle; TODO: Map exact stands."),

  bpVendor(GABP, "reds-fan-zone-food-hub", "Fan Zone Food Hub", "Field", "Section 130"),
  bpVendor(GABP, "reds-gliers-goetta", "Glier’s Goetta", "Field / upper", "Sections 129, 416"),
  bpVendor(GABP, "reds-scouts-club", "Scouts Club", "Premium", "Scouts Club; Section 412", "TODO: Verify Scouts Club ticket access."),
  bpVendor(GABP, "reds-los-rojos-taco-cart", "Los Rojos Taco Cart", "Field", "Section 128"),
  bpVendor(GABP, "reds-hemplers", "Hempler’s", "Field", "Section 109"),
  bpVendor(GABP, "reds-skyline-chili", "Skyline Chili", "Concourse", "Sections 103, 116, 130, 518, 535"),
  bpVendor(GABP, "reds-larosas-pizzeria", "LaRosa’s Family Pizzeria", "Concourse", "Multiple sections"),
  bpVendor(GABP, "reds-mr-reds-smokehouse", "Mr. Red’s Smokehouse", "Field", "Section 138"),
  bpVendor(GABP, "reds-graeters-ice-cream", "Graeter’s Ice Cream", "Field / upper", "Sections 119, 534"),
  bpVendor(GABP, "reds-mr-reds-smokehouse-desserts", "Mr. Red’s Smokehouse Desserts", "Field", "Section 139"),
  bpVendor(GABP, "reds-rosies-ice-cream", "Rosie’s Ice Cream", "Field / upper", "Sections 132, 413"),
  bpVendor(GABP, "reds-reds-brewery-district", "Reds Brewery District", "Field", "Section 118"),
  bpVendor(GABP, "reds-handlebar", "Handlebar", "Concourse", "Location not listed in source", "TODO: Confirm Handlebar stand location."),
  bpVendor(GABP, "reds-the-bootlegger", "The Bootlegger", "Field", "Section 131"),
  bpVendor(GABP, "reds-moerlein-lager-house", "Moerlein Lager House", "Upper", "Section 515"),
  bpVendor(GABP, "reds-toms-watch-bar", "Tom’s Watch Bar", "District", "The Banks"),

  bpVendor(PROG, "guards-fry-box", "Fry Box", "Field", "Section 119"),
  bpVendor(PROG, "guards-5-star", "5 Star", "Field", "Section 150"),
  bpVendor(PROG, "guards-steak-stand", "STEAK", "Field", "Section 159"),
  bpVendor(PROG, "guards-beer-hall-terrace-club", "Beer Hall & Terrace Club", "Premium", "Beer hall / terrace club", "TODO: Verify ticket access for specialty dogs."),
  bpVendor(PROG, "guards-sauce-the-city", "Sauce the City", "Concourse", "The Landing Section 164; Guardians Grill Section 559"),
  bpVendor(PROG, "guards-melt-bar-grilled", "Melt Bar & Grilled", "Field", "Section 107"),
  bpVendor(PROG, "guards-barrio", "Barrio", "Field", "Section 109"),
  bpVendor(PROG, "guards-fat-heads-brewery", "Fat Head’s Brewery", "Concourse", "The Landing; Section 164"),
  bpVendor(PROG, "guards-dantes-inferno", "Dante’s Inferno", "Field", "Section 109"),
  bpVendor(PROG, "guards-slymans-tavern", "Slyman’s Tavern", "Field", "Section 109"),
  bpVendor(PROG, "guards-ohio-city-burrito", "Ohio City Burrito", "Field", "Section 159"),
  bpVendor(PROG, "guards-happy-dog", "Happy Dog", "Field", "Section 159"),
  bpVendor(PROG, "guards-cleveland-sausages", "Cleveland Sausages", "Concourse", "100 and 500 levels"),
  bpVendor(PROG, "guards-corner-bar", "The Corner Bar", "Outfield", "Right field"),
  bpVendor(PROG, "guards-fat-heads-brew-deck", "Fat Head’s Brew Deck", "Upper", "Brew deck", "TODO: Confirm brew deck level / gate."),
  bpVendor(PROG, "guards-arcade-marketplace", "Arcade Marketplace", "Field", "Section 138"),
  bpVendor(PROG, "guards-the-landing", "The Landing", "Concourse", "Sections 162–164"),
  bpVendor(PROG, "guards-la-cave-du-vin", "La Cave du Vin", "Field", "Section 138"),
  bpVendor(PROG, "guards-gluten-free-stand", "Gluten-Free Stand", "Field", "Section 171"),
  bpVendor(PROG, "guards-aladdins-eatery", "Aladdin’s Eatery", "Field", "Section 154"),
  bpVendor(PROG, "guards-garden-greens", "Garden Greens", "Concourse", "Various marketplaces", "TODO: List marketplaces carrying Garden Greens."),

  bpVendor(RC, "rc-sec-103-dessert-stand", "Section 103 Dessert Stand", "Field", "Section 103"),
  bpVendor(RC, "rc-big-slugger-stands", "Big Slugger Stands", "Concourse", "Multiple locations"),
  bpVendor(RC, "rc-schneiders-porch", "Schneider’s Porch", "Concourse", "Location not listed in source", "TODO: Confirm Schneider’s Porch section."),
  bpVendor(RC, "rc-ace-dog", "Ace Dog", "Field", "Section 125"),
  bpVendor(RC, "rc-crispy-calamari", "Crispy Calamari", "Upper", "Section 220"),
  bpVendor(RC, "rc-the-catch-bar", "The Catch Bar", "Concourse", "Location not listed in source", "TODO: Map Catch Bar location."),
  bpVendor(RC, "rc-park-social", "Park Social", "Concourse", "Location not listed in source", "TODO: Confirm Park Social footprint."),
  bpVendor(RC, "rc-the-stop", "The Stop", "Concourse", "Location not listed in source", "TODO: Confirm The Stop location."),
  bpVendor(RC, "rc-randys-patties", "Randy’s Patties", "Concourse", "Multiple locations", "TODO: Map Randy’s kiosk sections."),
  bpVendor(RC, "rc-viande-fumee-poutine", "Viande Fumée Poutine", "Concourse", "Location not listed in source", "TODO: Confirm poutine stand section."),
  bpVendor(RC, "rc-meatball-panini", "Meatball Panini", "Field", "Section 128"),
  bpVendor(RC, "rc-stadium-bars", "Stadium Bars", "Concourse", "Multiple bars"),
  bpVendor(RC, "rc-rogers-terrace", "Rogers Terrace", "Upper", "200 level"),
  bpVendor(RC, "rc-heinz-club-328", "Heinz Club 328", "Premium", "Club 328", "TODO: Verify club access for temporary vs full-season layout."),
  bpVendor(RC, "rc-halal-kiosks", "Halal Kiosks", "Concourse", "Multiple locations", "TODO: Map halal kiosk sections."),
  bpVendor(RC, "rc-gluten-free-main-concessions", "Gluten-Free Main Concessions", "Concourse", "Main concourse hubs", "TODO: Confirm which hubs offer GF bun and dedicated fryer.")
];

export const wave6BallparkFoodItems: FoodItem[] = [
  bpItem(KC, KCT, "kauff-hot-dog-wellington", "kauff-hot-dog-wellington-item", "Hot Dog Wellington", "HOT_DOG", "Jumbo all-beef frank with mushroom duxelles wrapped in puff pastry, served with red wine jus.", { location: "Section 230", sections: ["230"] }),
  bpItem(KC, KCT, "kauff-korean-pork-cutlet", "kauff-korean-pork-cutlet-sandwich", "Korean Pork Cutlet Sandwich", "SANDWICH", "Breaded pork cutlet with Asian slaw, pickled cucumbers, Korean chili aioli.", { location: "Section 214", sections: ["214"] }),
  bpItem(KC, KCT, "kauff-big-cat-court", "kauff-beef-short-rib-corn-dog", "Beef Short Rib Corn Dog", "BBQ", "Hand-dipped corn dog with braised short rib and beer cheese fondue.", { location: "Big Cat Court" }),
  bpItem(KC, KCT, "kauff-smores-quesadilla", "kauff-smores-quesadilla-item", "S’mores Quesadilla", "DESSERT", "Griddled quesadilla with marshmallow, graham cracker, chocolate, powdered sugar.", { location: "Section 104", sections: ["104"] }),
  bpItem(KC, KCT, "kauff-tiramisu-helmet", "kauff-tiramisu-helmet-item", "Tiramisu Helmet", "DESSERT", "Royals helmet with coffee-soaked ladyfingers, mascarpone cream, cocoa.", { location: "Section 221", sections: ["221"] }),
  bpItem(KC, KCT, "kauff-hawaiian-bros", "kauff-huli-huli-chicken-plate", "Huli Huli Chicken Plate Lunch", "CHICKEN", "Hawaiian Bros plate lunch with huli huli chicken.", { location: "UMB Diamond Club" }),
  bpItem(KC, KCT, "kauff-hawaiian-bros", "kauff-luau-pork-plate", "Luau Pork Plate Lunch", "BBQ", "Hawaiian Bros plate lunch with luau pork.", { location: "UMB Diamond Club" }),
  bpItem(KC, KCT, "kauff-italian-sausage-co", "kauff-italian-sausage-sandwich", "Italian Sausage Sandwich", "SANDWICH", "Sausage sandwich with peppers, onions, red sauce.", { location: "Section 234", sections: ["234"] }),
  bpItem(KC, KCT, "kauff-kcq", "kauff-kcq-brisket-mac", "Brisket Topped Mac & Cheese", "BBQ", "Mac and cheese topped with brisket (pitmaster rotation monthly).", { location: "Section 216", sections: ["216"], tags: [KCT, "Rotating pitmaster"] }),
  bpItem(KC, KCT, "kauff-chickie-petes", "kauff-chickie-crabfries", "Crabfries", "SNACK", "Chickie & Pete’s crabfries.", { location: "Section 216", sections: ["216"] }),
  bpItem(KC, KCT, "kauff-andys-frozen-custard", "kauff-royals-concrete", "Royals Concrete", "DESSERT", "Andy’s concrete with Royals tie-in.", { location: "Section 221", sections: ["221"] }),
  bpItem(KC, KCT, "kauff-9-9-9-challenge", "kauff-9-mini-dogs-9-beer-flights", "9 Mini Hot Dogs and 9 Beer Flights", "HOT_DOG", "Challenge bundle: nine mini dogs and nine beer tastings.", { location: "Section 247", sections: ["247"], tags: [KCT, "Challenge bundle"] }),
  bpItem(KC, KCT, "kauff-double-dip-hoagies", "kauff-double-dip-french-dip", "French Dip", "SANDWICH", "French dip hoagie with au jus.", { location: "Section 247", sections: ["247"] }),
  bpItem(KC, KCT, "kauff-double-dip-hoagies", "kauff-double-dip-italian-beef", "Italian Beef", "SANDWICH", "Italian beef hoagie.", { location: "Section 247", sections: ["247"] }),
  bpItem(KC, KCT, "kauff-beer-bat-cooler-cup-stands", "kauff-beer-bat", "Beer Bat", "DRINK", "Beer served in souvenir bat.", { ...alc, beverageStyle: "Beer", location: "Multiple locations" }),
  bpItem(KC, KCT, "kauff-beer-bat-cooler-cup-stands", "kauff-cooler-cup-drink", "Cooler Cup Drink", "DRINK", "Souvenir cooler cup beverage program.", { ...alc, beverageStyle: "Beer", location: "Multiple locations", tags: [KCT, "TODO: Confirm cup program (draft vs mixed)"] }),
  bpItem(KC, KCT, "kauff-rivals-sports-bar", "kauff-blue-hell-cocktail", "Blue Hell Cocktail", "DRINK", "Rivals signature cocktail.", { ...alc, beverageStyle: "Cocktail", location: "Right field" }),
  bpItem(KC, KCT, "kauff-rivals-sports-bar", "kauff-rivals-craft-cocktails", "Craft Cocktails", "DRINK", "Craft cocktail menu at Rivals.", { ...alc, beverageStyle: "Cocktail", location: "Right field" }),
  bpItem(KC, KCT, "kauff-quiktrip-fountain-deck", "kauff-quiktrip-ayce-package", "All-You-Can-Eat Package", "OTHER", "QuikTrip Fountain Deck AYCE ticket package (rules vary).", { location: "Right field", tags: [KCT, "TODO: Confirm ticket / section for AYCE"] }),
  bpItem(KC, KCT, "kauff-quiktrip-fountain-deck", "kauff-quiktrip-beverage-package", "Beverage Package", "DRINK", "Fountain Deck beverage-inclusive package (inclusions vary by ticket).", { ...alc, beverageStyle: "Other", location: "Right field", tags: [KCT, "TODO: Confirm NA vs alcoholic inclusions by package"] }),
  bpItem(KC, KCT, "kauff-miller-lite-fountain-bar", "kauff-miller-lite-beer", "Miller Lite Beer", "DRINK", "Miller Lite draft and cans.", { ...alc, beverageStyle: "Beer", location: "Left-center field" }),
  bpItem(KC, KCT, "kauff-blue-moon-taproom", "kauff-blue-moon-draft", "Blue Moon Draft", "DRINK", "Blue Moon Belgian White on draft.", { ...alc, beverageStyle: "Beer", location: "On top of Rivals" }),
  bpItem(KC, KCT, "kauff-blue-moon-taproom", "kauff-seasonal-seltzer", "Seasonal Seltzer", "DRINK", "Rotating hard seltzer.", { ...alc, beverageStyle: "Seltzer", location: "On top of Rivals" }),
  bpItem(KC, KCT, "kauff-dirty-sodas", "kauff-dirty-soda", "Dirty Soda", "DRINK", "Custom dirty soda build.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Various locations" }),
  bpItem(KC, KCT, "kauff-value-menu-stands", "kauff-value-hot-dog", "Value Hot Dog", "HOT_DOG", "Value hot dog.", { location: "Sections 120, 135, 201, 213", sections: ["120", "135", "201", "213"] }),
  bpItem(KC, KCT, "kauff-value-menu-stands", "kauff-value-popcorn", "Value Popcorn", "SNACK", "Value popcorn.", { location: "Sections 120, 135, 201, 213", sections: ["120", "135", "201", "213"] }),
  bpItem(KC, KCT, "kauff-value-menu-stands", "kauff-value-nachos", "Value Nachos", "SNACK", "Value nachos.", { location: "Sections 120, 135, 201, 213", sections: ["120", "135", "201", "213"] }),
  bpItem(KC, KCT, "kauff-value-menu-stands", "kauff-value-soft-pretzel", "Value Soft Pretzel", "SNACK", "Value soft pretzel.", { location: "Sections 120, 135, 201, 213", sections: ["120", "135", "201", "213"] }),
  bpItem(KC, KCT, "kauff-plant-based-kiosks", "kauff-vegan-sausage", "Vegan Sausage", "VEGAN", "Plant-based sausage.", { location: "200 level" }),
  bpItem(KC, KCT, "kauff-plant-based-kiosks", "kauff-buffalo-cauliflower", "Buffalo Cauliflower", "VEGAN", "Buffalo-style cauliflower bites.", { location: "200 level" }),
  bpItem(KC, KCT, "kauff-brew-and-view", "kauff-brew-view-domestic-beer", "Domestic Beer", "DRINK", "Domestic draft and cans at Brew & View.", { ...alc, beverageStyle: "Beer", location: "Section 401", sections: ["401"] }),

  bpItem(CF, CFT, "citi-adam-richman-burger-hof", "citi-the-caprese", "The Caprese", "BURGER", "Pat LaFrieda patty with tomatoes, mozzarella, basil aioli, garlic butter on ciabatta.", { location: "Section 105", sections: ["105"] }),
  bpItem(CF, CFT, "citi-adam-richman-burger-hof", "citi-adams-classic", "Adam’s Classic", "BURGER", "Pat LaFrieda patty with secret sauce on Martin’s potato roll.", { location: "Section 105", sections: ["105"] }),
  bpItem(CF, CFT, "citi-the-queensboro", "citi-kimchi-reuben", "Kimchi Reuben", "SANDWICH", "Corned beef with kimchi fennel, Swiss, cabbage-apple slaw on rye.", { location: "Taste of Queens" }),
  bpItem(CF, CFT, "citi-pig-beach-bbq", "citi-loaded-cornbread", "Loaded Cornbread", "BBQ", "Cornbread with cheese sauce, BBQ sauce, pulled pork.", { location: "Section 135", sections: ["135"] }),
  bpItem(CF, CFT, "citi-seoul-bird", "citi-ny-bulgogi-cheesesteak-spring-rolls", "NY Bulgogi Cheesesteak Spring Rolls", "SANDWICH", "Bulgogi, kimchi, cheddar, gochujang-sriracha mayo in spring roll format.", { location: "Metro Market" }),
  bpItem(CF, CFT, "citi-metropolitan-fry-factory", "citi-strawberry-short-stop-dip", "Strawberry Short-stop Dip", "DESSERT", "Cheesecake dipped in strawberry chocolate and shortcake crunch.", { location: "Concourse" }),
  bpItem(CF, CFT, "citi-pat-lafrieda", "citi-filet-mignon-steak-sandwich", "Filet Mignon Steak Sandwich", "SANDWICH", "Filet mignon steak sandwich.", { location: "Section 139", sections: ["139"] }),
  bpItem(CF, CFT, "citi-legacy-catering-mookie-wilson", "citi-smoked-pulled-chicken-sliders", "Smoked Pulled Chicken Sliders", "CHICKEN", "Smoked pulled chicken sliders.", { location: "Taste of the City" }),
  bpItem(CF, CFT, "citi-chef-kwame-patty-palace", "citi-ny-chopped-cheese-patty", "NY Chopped Cheese Patty", "SANDWICH", "Jamaican patty-style chopped cheese.", { location: "Section 415", sections: ["415"] }),
  bpItem(CF, CFT, "citi-chef-kwame-patty-palace", "citi-curry-chicken-patty", "Curry Chicken Patty", "CHICKEN", "Curry chicken patty.", { location: "Section 415", sections: ["415"] }),
  bpItem(CF, CFT, "citi-chef-kwame-patty-palace", "citi-jerk-mushroom-patty", "Jerk Mushroom Patty", "VEGAN", "Jerk-spiced mushroom patty.", { location: "Section 415", sections: ["415"] }),
  bpItem(CF, CFT, "citi-amazin-deli", "citi-chopped-italian-sausage", "Chopped Italian Sausage", "SANDWICH", "Chopped Italian sausage sandwich.", { location: "Sections 131, 414", sections: ["131", "414"] }),
  bpItem(CF, CFT, "citi-amazin-deli", "citi-bacon-egg-cheese", "Bacon Egg and Cheese", "SANDWICH", "Breakfast-style bacon, egg, and cheese.", { location: "Sections 131, 414", sections: ["131", "414"] }),
  bpItem(CF, CFT, "citi-fuku", "citi-fuku-spicy-chicken-sandwich", "Spicy Fried Chicken Sandwich", "CHICKEN", "Fuku spicy fried chicken sandwich.", { location: "Section 130", sections: ["130"] }),
  bpItem(CF, CFT, "citi-shake-shack", "citi-shackburger", "ShackBurger", "BURGER", "Shake Shack cheeseburger.", { location: "Taste of the City" }),
  bpItem(CF, CFT, "citi-shake-shack", "citi-shroom-burger", "Shroom Burger", "VEGAN", "Crispy portobello mushroom burger.", { location: "Taste of the City" }),
  bpItem(CF, CFT, "citi-hildebrandts-ice-cream", "citi-blue-orange-skies", "Blue & Orange Skies Ice Cream", "DESSERT", "Mets-themed ice cream flavor.", { location: "Multiple locations" }),
  bpItem(CF, CFT, "citi-chop-house", "citi-big-apple-pie-cheesecake", "Big Apple Pie Cheesecake", "DESSERT", "Apple pie cheesecake slice.", { location: "Concourse" }),
  bpItem(CF, CFT, "citi-cookie-crumz", "citi-fun-met-i-cookie", "Fun Met I Cookie", "DESSERT", "Stadium cookie novelty.", { location: "Sections 119, 336", sections: ["119", "336"] }),
  bpItem(CF, CFT, "citi-dole-whip", "citi-dole-whip-item", "Dole Whip", "DESSERT", "Dole Whip soft serve.", { location: "Multiple sections" }),
  bpItem(CF, CFT, "citi-9-9-9-challenge", "citi-9-hot-dogs-9-beers-challenge", "9 Hot Dogs and 9 Beers Challenge", "HOT_DOG", "Challenge bundle: nine hot dogs and nine beers.", { location: "Section 128", sections: ["128"], tags: [CFT, "Challenge bundle"] }),
  bpItem(CF, CFT, "citi-bases-loaded-lemonade", "citi-hard-lemonade", "Hard Lemonade", "DRINK", "Spiked lemonade.", { ...alc, beverageStyle: "Cocktail", location: "Sections 114, 416", sections: ["114", "416"] }),
  bpItem(CF, CFT, "citi-boozy-buckets", "citi-extra-innings-iced-tea-bucket", "Extra Innings Iced Tea Bucket", "DRINK", "Large-format boozy iced tea bucket.", { ...alc, beverageStyle: "Cocktail", location: "Sections 114, 416", sections: ["114", "416"] }),
  bpItem(CF, CFT, "citi-willets-point-brewery", "citi-shea-bridge-amber", "Shea Bridge Amber", "DRINK", "Willets Point house amber.", { ...alc, beverageStyle: "Beer", location: "Section 110", sections: ["110"] }),
  bpItem(CF, CFT, "citi-willets-point-brewery", "citi-local-queens-beer", "Local Queens Beer", "DRINK", "Rotating Queens brewery tap.", { ...alc, beverageStyle: "Beer", location: "Section 110", sections: ["110"] }),
  bpItem(CF, CFT, "citi-milagro-tequila-porch", "citi-milagro-tequila-cocktails", "Tequila Cocktails", "DRINK", "Milagro tequila cocktails.", { ...alc, beverageStyle: "Cocktail", location: "Outfield porch" }),
  bpItem(CF, CFT, "citi-vegan-city", "citi-vegan-hot-dog", "Vegan Hot Dog", "VEGAN", "Plant-based hot dog.", { location: "Section 105", sections: ["105"] }),
  bpItem(CF, CFT, "citi-vegan-city", "citi-vegan-burger", "Vegan Burger", "VEGAN", "Plant-based burger.", { location: "Section 105", sections: ["105"] }),
  bpItem(CF, CFT, "citi-vegan-city", "citi-vegan-nacho-helmet", "Vegan Nacho Helmet", "VEGAN", "Plant-based nachos in souvenir helmet.", { location: "Section 105", sections: ["105"] }),
  bpItem(CF, CFT, "citi-prime-kosher-sports", "citi-kosher-hot-dog", "Kosher Hot Dog", "HOT_DOG", "Glatt kosher beef hot dog.", { location: "Section 114", sections: ["114"] }),
  bpItem(CF, CFT, "citi-prime-kosher-sports", "citi-kosher-knish", "Knish", "OTHER", "Kosher knish.", { location: "Section 114", sections: ["114"] }),
  bpItem(CF, CFT, "citi-prime-kosher-sports", "citi-kosher-burger", "Kosher Burger", "BURGER", "Glatt kosher burger.", { location: "Section 114", sections: ["114"] }),
  bpItem(CF, CFT, "citi-gluten-friendly", "citi-gf-bun-option", "Gluten-Free Bun Option", "GLUTEN_FREE", "GF bun substitute where offered.", { location: "Sections 105, 416", sections: ["105", "416"] }),
  bpItem(CF, CFT, "citi-gluten-friendly", "citi-gf-snacks", "Gluten-Free Snacks", "GLUTEN_FREE", "Packaged GF snacks.", { location: "Sections 105, 416", sections: ["105", "416"] }),
  bpItem(CF, CFT, "citi-gluten-friendly", "citi-dedicated-fryer-fries", "Dedicated Fryer Fries", "GLUTEN_FREE", "Fries from dedicated fryer (verify at stand).", { location: "Sections 105, 416", sections: ["105", "416"], tags: [CFT, "TODO: Confirm fryer hours"] }),

  bpItem(NYY, NYYT, "yanks-legends-global", "yanks-mvp-burger", "MVP Burger", "BURGER", "Two Wagyu patties with cheese, onions, onion rings, tomato-bacon jam.", { location: "Section 127", sections: ["127"] }),
  bpItem(NYY, NYYT, "yanks-kings-hawaiian", "yanks-angry-lobster-roll", "Angry Lobster Roll", "SEAFOOD", "Lobster roll on King’s Hawaiian roll.", { location: "Section 115", sections: ["115"] }),
  bpItem(NYY, NYYT, "yanks-lobels", "yanks-lobels-pastrami-fries", "Pastrami Fries", "SNACK", "Pastrami-topped fries.", { location: "Section 134", sections: ["134"] }),
  bpItem(NYY, NYYT, "yanks-lobels", "yanks-usda-prime-steak-sandwich", "USDA Prime Steak Sandwich", "SANDWICH", "Lobel’s USDA Prime steak sandwich.", { location: "Section 134", sections: ["134"] }),
  bpItem(NYY, NYYT, "yanks-christian-petroni-parm", "yanks-mozzarella-en-carrozza", "Mozzarella en Carrozza", "SANDWICH", "Fried mozzarella sandwich.", { location: "Section 125", sections: ["125"] }),
  bpItem(NYY, NYYT, "yanks-christian-petroni-parm", "yanks-pasta-alla-vodka-bowl", "Pasta alla Vodka Bowl", "OTHER", "Pasta alla vodka bowl.", { location: "Section 125", sections: ["125"] }),
  bpItem(NYY, NYYT, "yanks-christian-petroni-parm", "yanks-arrabbiata-pasta-bowl", "Arrabbiata Pasta Bowl", "OTHER", "Spicy arrabbiata pasta bowl.", { location: "Section 125", sections: ["125"] }),
  bpItem(NYY, NYYT, "yanks-streetbird", "yanks-sticky-que-chicken-sandwich", "Sticky Que Chicken Sandwich", "CHICKEN", "Marcus Samuelsson sticky glazed chicken sandwich.", { location: "Section 112", sections: ["112"] }),
  bpItem(NYY, NYYT, "yanks-mister-softee", "yanks-mini-dessert-chicken-bucket", "Mini Dessert Chicken Bucket", "DESSERT", "Mister Softee novelty dessert bucket.", { location: "Multiple locations" }),
  bpItem(NYY, NYYT, "yanks-mister-softee", "yanks-apple-pie-nachos", "Apple Pie Nachos", "DESSERT", "Deconstructed apple pie “nachos.”", { location: "Multiple locations" }),
  bpItem(NYY, NYYT, "yanks-brooklyn-dumpling-shop", "yanks-bacon-cheeseburger-dumplings", "Bacon Cheeseburger Dumplings", "BURGER", "Crispy dumplings with bacon cheeseburger filling.", { location: "Section 123", sections: ["123"] }),
  bpItem(NYY, NYYT, "yanks-brooklyn-dumpling-shop", "yanks-mac-cheese-dumplings", "Mac & Cheese Dumplings", "OTHER", "Mac and cheese stuffed dumplings.", { location: "Section 123", sections: ["123"] }),
  bpItem(NYY, NYYT, "yanks-brooklyn-dumpling-shop", "yanks-apple-pie-dumplings", "Apple Pie Dumplings", "DESSERT", "Apple pie dessert dumplings.", { location: "Section 123", sections: ["123"] }),
  bpItem(NYY, NYYT, "yanks-fuku", "yanks-fuku-loaded-waffle-fries", "Loaded Waffle Fries", "CHICKEN", "Fuku loaded waffle fries with chicken toppings.", { location: "Sections 213, 321", sections: ["213", "321"] }),
  bpItem(NYY, NYYT, "yanks-nuchas-empanadas", "yanks-nuchas-italian-sausage-empanada", "Italian Sausage & Peppers Empanada", "SNACK", "Baked empanada with sausage and peppers.", { location: "Sections 107, 305", sections: ["107", "305"] }),
  bpItem(NYY, NYYT, "yanks-the-99-burger", "yanks-99-burger", "99 Burger", "BURGER", "Aaron Judge tie-in specialty burger.", { location: "Section 223", sections: ["223"] }),
  bpItem(NYY, NYYT, "yanks-magnolia-bakery", "yanks-magnolia-banana-pudding", "Banana Pudding", "DESSERT", "Magnolia banana pudding cup.", { location: "Sections 106, 223, 311", sections: ["106", "223", "311"] }),
  bpItem(NYY, NYYT, "yanks-magnolia-bakery", "yanks-magnolia-brownie", "Brownie", "DESSERT", "Fudge brownie.", { location: "Sections 106, 223, 311", sections: ["106", "223", "311"] }),
  bpItem(NYY, NYYT, "yanks-magnolia-bakery", "yanks-magnolia-blondie", "Blondie", "DESSERT", "Blondie bar.", { location: "Sections 106, 223, 311", sections: ["106", "223", "311"] }),
  bpItem(NYY, NYYT, "yanks-treathouse", "yanks-yankees-crispy-rice-treat", "Yankees Crispy Rice Treat", "DESSERT", "Branded crispy rice treat.", { location: "Section 106", sections: ["106"] }),
  bpItem(NYY, NYYT, "yanks-stadium-bars", "yanks-wind-up-watermelon-margarita", "The Wind Up Watermelon Margarita", "DRINK", "Stadium bar watermelon margarita.", { ...alc, beverageStyle: "Cocktail", location: "Multiple bars" }),
  bpItem(NYY, NYYT, "yanks-stadium-bars", "yanks-heater-margarita", "The Heater Margarita", "DRINK", "Spicy stadium margarita.", { ...alc, beverageStyle: "Cocktail", location: "Multiple bars" }),
  bpItem(NYY, NYYT, "yanks-stadium-bars", "yanks-new-york-legendary-ale", "New York Legendary Ale", "DRINK", "House Yankees-branded ale.", { ...alc, beverageStyle: "Beer", location: "Multiple bars" }),
  bpItem(NYY, NYYT, "yanks-aspen-vodka-party-deck", "yanks-aspen-espresso-martini", "Aspen Espresso Martini", "DRINK", "Aspen Vodka espresso martini.", { ...alc, beverageStyle: "Cocktail", location: "Section 328", sections: ["328"] }),
  bpItem(NYY, NYYT, "yanks-stella-artois-landing", "yanks-stella-landing-beer", "Beer", "DRINK", "Draft and packaged beer at Stella landing.", { ...alc, beverageStyle: "Beer", location: "Section 232", sections: ["232"] }),
  bpItem(NYY, NYYT, "yanks-michelob-ultra-clubhouse", "yanks-michelob-ultra-club-beer", "Beer", "DRINK", "Draft beer at Michelob ULTRA Clubhouse.", { ...alc, beverageStyle: "Beer", location: "Section 207", sections: ["207"] }),
  bpItem(NYY, NYYT, "yanks-diamond-deal", "yanks-diamond-deal-tender-tray", "Diamond Deal Chicken Tender Tray", "CHICKEN", "Shareable tender tray special.", { location: "Sections 105, 311", sections: ["105", "311"] }),
  bpItem(NYY, NYYT, "yanks-pinstripe-power-pack", "yanks-kids-hot-dog-bundle", "Kids Hot Dog Bundle", "HOT_DOG", "Kids hot dog bundle (participating stands).", { location: "Multiple locations", tags: [NYYT, "Kids value"] }),

  bpItem(GABP, GABPT, "reds-fan-zone-food-hub", "reds-queen-city-crunch-burger", "Queen City Crunch Burger", "BURGER", "Smash burger with pimento cheese, pickles, Grippo’s BBQ chips.", { location: "Section 130", sections: ["130"] }),
  bpItem(GABP, GABPT, "reds-gliers-goetta", "reds-glt-sliders", "G.L.T. Sliders", "SANDWICH", "Goetta, lettuce, tomato sliders.", { location: "Sections 129, 416", sections: ["129", "416"] }),
  bpItem(GABP, GABPT, "reds-gliers-goetta", "reds-goetta-nachos", "Goetta Nachos", "SNACK", "Nachos topped with goetta crumbles.", { location: "Sections 129, 416", sections: ["129", "416"] }),
  bpItem(GABP, GABPT, "reds-scouts-club", "reds-scouts-stadium-burnt-ends", "Stadium Burnt Ends", "BBQ", "Smoked burnt ends plate.", { location: "Scouts Club; Section 412", sections: ["412"] }),
  bpItem(GABP, GABPT, "reds-scouts-club", "reds-scouts-big-red-machine-burger", "Big Red Machine Burger", "BURGER", "Scouts Club signature burger.", { location: "Scouts Club; Section 412", sections: ["412"] }),
  bpItem(GABP, GABPT, "reds-scouts-club", "reds-scouts-mac-cheese-dog", "Mac and Cheese Dog", "HOT_DOG", "Hot dog topped with mac and cheese.", { location: "Scouts Club; Section 412", sections: ["412"] }),
  bpItem(GABP, GABPT, "reds-scouts-club", "reds-scouts-bulgogi-egg-rolls", "Bulgogi Beef Egg Rolls", "SNACK", "Bulgogi-stuffed egg rolls.", { location: "Scouts Club; Section 412", sections: ["412"] }),
  bpItem(GABP, GABPT, "reds-los-rojos-taco-cart", "reds-tofuego-tacos", "Tofuego Tacos", "VEGAN", "Tofu “tofuego” street tacos.", { location: "Section 128", sections: ["128"] }),
  bpItem(GABP, GABPT, "reds-hemplers", "reds-jalapeno-cheddar-cajun-bowl", "Jalapeño Cheddar Cajun Bowl", "HOT_DOG", "Sausage bowl with jalapeño cheddar Cajun toppings.", { location: "Section 109", sections: ["109"] }),
  bpItem(GABP, GABPT, "reds-skyline-chili", "reds-skyline-cheese-coney", "Cheese Coney", "HOT_DOG", "Skyline cheese coney.", { location: "Sections 103, 116, 130, 518, 535", sections: ["103", "116", "130", "518", "535"] }),
  bpItem(GABP, GABPT, "reds-skyline-chili", "reds-skyline-3-way", "3-Way Chili", "OTHER", "Spaghetti, chili, shredded cheese.", { location: "Sections 103, 116, 130, 518, 535", sections: ["103", "116", "130", "518", "535"] }),
  bpItem(GABP, GABPT, "reds-larosas-pizzeria", "reds-larosas-pizza-slice", "LaRosa’s Pizza Slice", "PIZZA", "LaRosa’s pizza by the slice.", { location: "Multiple sections" }),
  bpItem(GABP, GABPT, "reds-mr-reds-smokehouse", "reds-smoked-brisket-street-corn-bowl", "Smoked Brisket Street Corn Bowl", "BBQ", "Brisket over street corn bowl.", { location: "Section 138", sections: ["138"] }),
  bpItem(GABP, GABPT, "reds-graeters-ice-cream", "reds-reds-waffle-bowl", "Reds Waffle Bowl", "DESSERT", "Ice cream in mini waffle bowl.", { location: "Sections 119, 534", sections: ["119", "534"] }),
  bpItem(GABP, GABPT, "reds-graeters-ice-cream", "reds-black-raspberry-chip", "Black Raspberry Chocolate Chip Ice Cream", "DESSERT", "Graeter’s black raspberry chip scoop.", { location: "Sections 119, 534", sections: ["119", "534"] }),
  bpItem(GABP, GABPT, "reds-mr-reds-smokehouse-desserts", "reds-double-play-donut-parfait", "Double Play Donut Parfait", "DESSERT", "Layered donut parfait dessert.", { location: "Section 139", sections: ["139"] }),
  bpItem(GABP, GABPT, "reds-rosies-ice-cream", "reds-baby-ruth-brownie-sundae", "Baby Ruth Brownie Sundae", "DESSERT", "Brownie sundae with Baby Ruth pieces.", { location: "Sections 132, 413", sections: ["132", "413"] }),
  bpItem(GABP, GABPT, "reds-reds-brewery-district", "reds-braxton-ballpark-beer-district", "Braxton Ballpark Beer", "DRINK", "Braxton Ballpark exclusive draft.", { ...alc, beverageStyle: "Beer", location: "Section 118", sections: ["118"] }),
  bpItem(GABP, GABPT, "reds-handlebar", "reds-handlebar-braxton-ballpark-beer", "Braxton Ballpark Beer", "DRINK", "Braxton Ballpark beer at Handlebar.", { ...alc, beverageStyle: "Beer", location: "Concourse" }),
  bpItem(GABP, GABPT, "reds-the-bootlegger", "reds-bootlegger-makers-cocktail", "Maker’s Mark Bourbon Cocktail", "DRINK", "Maker’s Mark cocktail.", { ...alc, beverageStyle: "Cocktail", location: "Section 131", sections: ["131"] }),
  bpItem(GABP, GABPT, "reds-the-bootlegger", "reds-bootlegger-craft-beer", "Craft Beer", "DRINK", "Rotating craft taps.", { ...alc, beverageStyle: "Beer", location: "Section 131", sections: ["131"] }),
  bpItem(GABP, GABPT, "reds-moerlein-lager-house", "reds-hudy-14k", "Hudy 14K Beer", "DRINK", "Hudy Delight / Hudy 14K lager.", { ...alc, beverageStyle: "Beer", location: "Section 515", sections: ["515"] }),
  bpItem(GABP, GABPT, "reds-moerlein-lager-house", "reds-seasonal-radler", "Seasonal Radler", "DRINK", "Seasonal radler shandy.", { ...alc, beverageStyle: "Beer", location: "Section 515", sections: ["515"] }),
  bpItem(GABP, GABPT, "reds-toms-watch-bar", "reds-toms-sports-bar-food", "Sports Bar Food", "OTHER", "Game-day bar menu (items vary).", { location: "The Banks" }),
  bpItem(GABP, GABPT, "reds-toms-watch-bar", "reds-toms-bar-drinks", "Bar Drinks", "DRINK", "Full bar cocktails, wine, and beer.", { ...alc, beverageStyle: "Cocktail", location: "The Banks" }),

  bpItem(PROG, PROGT, "guards-fry-box", "guards-spicy-thai-fries", "Spicy Thai Fries", "SNACK", "Fries with chili pulled pork, carrots, cucumber, green onion, sambal mayo.", { location: "Section 119", sections: ["119"] }),
  bpItem(PROG, PROGT, "guards-5-star", "guards-the-jackhammer", "The Jackhammer", "HOT_DOG", "Pepperjack sausage with Pickle de Gallo on hot dog roll.", { location: "Section 150", sections: ["150"] }),
  bpItem(PROG, PROGT, "guards-steak-stand", "guards-tallow-popcorn", "Tallow Popcorn", "SNACK", "Beef tallow popcorn.", { location: "Section 159", sections: ["159"] }),
  bpItem(PROG, PROGT, "guards-steak-stand", "guards-steak-sandwich", "Steak Sandwich", "SANDWICH", "STEAK stand steak sandwich.", { location: "Section 159", sections: ["159"] }),
  bpItem(PROG, PROGT, "guards-steak-stand", "guards-carnival-crab-cakes", "Carnival Crab Cakes", "SEAFOOD", "Crab cake sliders or plate.", { location: "Section 159", sections: ["159"] }),
  bpItem(PROG, PROGT, "guards-beer-hall-terrace-club", "guards-aladdins-med-dog", "Aladdin’s Med Dog", "HOT_DOG", "Kafta dog with tomato-cucumber salata, hummus, hot sauce.", { location: "Beer Hall & Terrace Club" }),
  bpItem(PROG, PROGT, "guards-sauce-the-city", "guards-sauce-spicy-chicken", "Sauce the City Spicy Chicken", "CHICKEN", "Spicy chicken sandwich or tenders (menu varies).", { location: "The Landing Section 164; Guardians Grill Section 559", sections: ["164", "559"] }),
  bpItem(PROG, PROGT, "guards-melt-bar-grilled", "guards-kindergarten-grilled-cheese", "Kindergarten Grilled Cheese", "SANDWICH", "Melt Bar classic grilled cheese.", { location: "Section 107", sections: ["107"] }),
  bpItem(PROG, PROGT, "guards-melt-bar-grilled", "guards-melt-pierogi-sandwich", "Melt Pierogi Sandwich", "SANDWICH", "Pierogi-stuffed grilled sandwich.", { location: "Section 107", sections: ["107"] }),
  bpItem(PROG, PROGT, "guards-barrio", "guards-barrio-custom-tacos", "Custom Tacos", "TACOS", "Build-your-own taco plate.", { location: "Section 109", sections: ["109"] }),
  bpItem(PROG, PROGT, "guards-barrio", "guards-barrio-margarita", "Margarita", "DRINK", "Barrio margarita.", { ...alc, beverageStyle: "Cocktail", location: "Section 109", sections: ["109"] }),
  bpItem(PROG, PROGT, "guards-fat-heads-brewery", "guards-southside-slopes-sandwich", "Southside Slopes Sandwich", "SANDWICH", "Fat Head’s Pittsburgh-style sandwich.", { location: "The Landing; Section 164", sections: ["164"] }),
  bpItem(PROG, PROGT, "guards-fat-heads-brewery", "guards-head-hunter-ipa", "Head Hunter IPA", "DRINK", "Fat Head’s Head Hunter IPA.", { ...alc, beverageStyle: "Beer", location: "The Landing; Section 164", sections: ["164"] }),
  bpItem(PROG, PROGT, "guards-dantes-inferno", "guards-dantes-craft-pizza", "Craft Pizza", "PIZZA", "Dante’s Inferno craft pizza slice or pie.", { location: "Section 109", sections: ["109"] }),
  bpItem(PROG, PROGT, "guards-slymans-tavern", "guards-slymans-corned-beef", "Corned Beef Sandwich", "SANDWICH", "Slyman’s thick-cut corned beef on rye.", { location: "Section 109", sections: ["109"] }),
  bpItem(PROG, PROGT, "guards-ohio-city-burrito", "guards-ocb-burrito", "Burrito", "TACOS", "Ohio City burrito.", { location: "Section 159", sections: ["159"] }),
  bpItem(PROG, PROGT, "guards-ohio-city-burrito", "guards-silver-bullet-burrito", "Silver Bullet Burrito", "TACOS", "Loaded Silver Bullet burrito.", { location: "Section 159", sections: ["159"] }),
  bpItem(PROG, PROGT, "guards-happy-dog", "guards-slider-dog", "Slider Dog", "HOT_DOG", "Happy Dog slider-style dog build.", { location: "Section 159", sections: ["159"] }),
  bpItem(PROG, PROGT, "guards-cleveland-sausages", "guards-cle-bratwurst", "Bratwurst", "HOT_DOG", "Grilled bratwurst.", { location: "100 and 500 levels" }),
  bpItem(PROG, PROGT, "guards-cleveland-sausages", "guards-cle-italian-sausage", "Italian Sausage", "HOT_DOG", "Italian sausage with peppers.", { location: "100 and 500 levels" }),
  bpItem(PROG, PROGT, "guards-corner-bar", "guards-corner-draft-beer", "Draft Beer", "DRINK", "Corner Bar draft selection.", { ...alc, beverageStyle: "Beer", location: "Right field" }),
  bpItem(PROG, PROGT, "guards-fat-heads-brew-deck", "guards-brew-deck-beer-market", "Beer Market", "DRINK", "Self-serve / market-style beer wall (format varies).", { ...alc, beverageStyle: "Beer", location: "Brew deck", tags: [PROGT, "TODO: Confirm brew deck format"] }),
  bpItem(PROG, PROGT, "guards-arcade-marketplace", "guards-arcade-grab-snacks", "Grab-and-Go Snacks", "SNACK", "Pre-packaged snacks.", { location: "Section 138", sections: ["138"], tags: [PROGT, "Grab and go"] }),
  bpItem(PROG, PROGT, "guards-arcade-marketplace", "guards-arcade-grab-drinks", "Grab-and-Go Drinks", "DRINK", "Cold bottled and canned drinks.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Section 138", sections: ["138"], tags: [PROGT, "Grab and go"] }),
  bpItem(PROG, PROGT, "guards-the-landing", "guards-landing-marketplace-food", "Marketplace Food", "OTHER", "Rotating marketplace plates (vendors vary).", { location: "Sections 162–164", sections: ["162", "163", "164"] }),
  bpItem(PROG, PROGT, "guards-the-landing", "guards-landing-beer", "Beer", "DRINK", "Draft beer at The Landing.", { ...alc, beverageStyle: "Beer", location: "Sections 162–164", sections: ["162", "163", "164"] }),
  bpItem(PROG, PROGT, "guards-la-cave-du-vin", "guards-la-cave-wine", "Wine", "DRINK", "Wine by the glass or bottle.", { ...alc, beverageStyle: "Wine", location: "Section 138", sections: ["138"] }),
  bpItem(PROG, PROGT, "guards-gluten-free-stand", "guards-gf-beef-patty-melt", "Beef Patty Melt", "GLUTEN_FREE", "GF bun patty melt.", { location: "Section 171", sections: ["171"] }),
  bpItem(PROG, PROGT, "guards-gluten-free-stand", "guards-gf-hot-dog", "Gluten-Free Hot Dog", "GLUTEN_FREE", "GF hot dog build.", { location: "Section 171", sections: ["171"] }),
  bpItem(PROG, PROGT, "guards-gluten-free-stand", "guards-gf-fruit-cup", "Fruit Cup", "SNACK", "Fresh fruit cup.", { location: "Section 171", sections: ["171"] }),
  bpItem(PROG, PROGT, "guards-aladdins-eatery", "guards-aladdins-hummus-wrap", "Hummus Wrap", "VEGAN", "Hummus and veggie wrap.", { location: "Section 154", sections: ["154"] }),
  bpItem(PROG, PROGT, "guards-aladdins-eatery", "guards-aladdins-falafel", "Falafel", "VEGAN", "Falafel plate or wrap.", { location: "Section 154", sections: ["154"] }),
  bpItem(PROG, PROGT, "guards-garden-greens", "guards-garden-fresh-salad", "Fresh Salad", "VEGAN", "Grab-and-go salad.", { location: "Various marketplaces" }),
  bpItem(PROG, PROGT, "guards-garden-greens", "guards-garden-grain-bowl", "Grain Bowl", "VEGAN", "Grain bowl with veggies.", { location: "Various marketplaces" }),

  bpItem(RC, RCT, "rc-sec-103-dessert-stand", "rc-uncrustable-french-toast", "Uncrustable French Toast", "DESSERT", "Stadium French toast novelty.", { location: "Section 103", sections: ["103"] }),
  bpItem(RC, RCT, "rc-sec-103-dessert-stand", "rc-rocky-mountain-sundae", "Rocky Mountain Sundae", "DESSERT", "Loaded ice cream sundae.", { location: "Section 103", sections: ["103"] }),
  bpItem(RC, RCT, "rc-big-slugger-stands", "rc-big-slugger-burger", "Big Slugger", "BURGER", "Oversized Big Slugger burger.", { location: "Multiple locations" }),
  bpItem(RC, RCT, "rc-schneiders-porch", "rc-al-pastor-dog", "Al Pastor Dog", "HOT_DOG", "Al pastor–style topped dog.", { location: "Schneider’s Porch" }),
  bpItem(RC, RCT, "rc-schneiders-porch", "rc-hot-maple-bacon-dog", "Hot Maple & Bacon Hot Dog", "HOT_DOG", "Maple and bacon topped dog.", { location: "Schneider’s Porch" }),
  bpItem(RC, RCT, "rc-ace-dog", "rc-ace-dog-item", "Ace Dog", "HOT_DOG", "Signature Ace Dog build.", { location: "Section 125", sections: ["125"] }),
  bpItem(RC, RCT, "rc-crispy-calamari", "rc-crispy-calamari-item", "Crispy Calamari", "SEAFOOD", "Fried calamari basket.", { location: "Section 220", sections: ["220"] }),
  bpItem(RC, RCT, "rc-the-catch-bar", "rc-catch-garlic-knots", "Garlic Knots", "SNACK", "Garlic knots side.", { location: "The Catch Bar" }),
  bpItem(RC, RCT, "rc-the-catch-bar", "rc-catch-ontario-craft-beer", "Ontario Craft Beer", "DRINK", "Ontario craft draft lineup.", { ...alc, beverageStyle: "Beer", location: "The Catch Bar" }),
  bpItem(RC, RCT, "rc-park-social", "rc-park-social-milkshake-month", "Milkshake of the Month", "DESSERT", "Rotating milkshake flavor.", { location: "Park Social" }),
  bpItem(RC, RCT, "rc-park-social", "rc-loonie-dogs", "Loonie Dogs", "HOT_DOG", "Promotional value hot dogs when offered.", { location: "Park Social", tags: [RCT, "Value promo", "TODO: Confirm promo nights"] }),
  bpItem(RC, RCT, "rc-the-stop", "rc-stop-stuffed-jamaican-patties", "Stuffed Jamaican Patties", "SNACK", "Stuffed patties (fillings vary).", { location: "The Stop" }),
  bpItem(RC, RCT, "rc-the-stop", "rc-stop-beef-shawarma-bowl", "Beef Shawarma Bowl", "OTHER", "Beef shawarma rice bowl.", { location: "The Stop" }),
  bpItem(RC, RCT, "rc-the-stop", "rc-stop-poke-bowl", "Poke Bowl", "SEAFOOD", "Poke bowl build.", { location: "The Stop" }),
  bpItem(RC, RCT, "rc-randys-patties", "rc-randys-beef-patty", "Beef Jamaican Patty", "SNACK", "Beef Jamaican patty.", { location: "Multiple locations" }),
  bpItem(RC, RCT, "rc-randys-patties", "rc-randys-chicken-patty", "Chicken Jamaican Patty", "CHICKEN", "Chicken Jamaican patty.", { location: "Multiple locations" }),
  bpItem(RC, RCT, "rc-randys-patties", "rc-randys-veggie-patty", "Veggie Jamaican Patty", "VEGAN", "Vegetable Jamaican patty.", { location: "Multiple locations" }),
  bpItem(RC, RCT, "rc-viande-fumee-poutine", "rc-montreal-smoked-meat-poutine", "Montreal Smoked Meat Poutine", "OTHER", "Smoked meat over fries and cheese curds with gravy.", { location: "Concourse" }),
  bpItem(RC, RCT, "rc-meatball-panini", "rc-meatball-panini-item", "Meatball Panini", "SANDWICH", "Pressed meatball panini.", { location: "Section 128", sections: ["128"] }),
  bpItem(RC, RCT, "rc-stadium-bars", "rc-line-drive-lemonade", "Line Drive Lemonade", "DRINK", "Spiked lemonade cocktail.", { ...alc, beverageStyle: "Cocktail", location: "Multiple bars" }),
  bpItem(RC, RCT, "rc-stadium-bars", "rc-grand-slam-margarita", "Grand Slam Margarita", "DRINK", "Stadium margarita.", { ...alc, beverageStyle: "Cocktail", location: "Multiple bars" }),
  bpItem(RC, RCT, "rc-stadium-bars", "rc-low-and-away-mocktail", "Low and Away Mocktail", "DRINK", "Non-alcoholic mocktail.", { itemType: "Non-Alcoholic Drink", beverageStyle: "Non-Alcoholic", location: "Multiple bars" }),
  bpItem(RC, RCT, "rc-rogers-terrace", "rc-terrace-charcuterie", "Charcuterie Board", "OTHER", "Charcuterie board (club / ticketed).", { location: "200 level", tags: [RCT, "TODO: Verify terrace access"] }),
  bpItem(RC, RCT, "rc-rogers-terrace", "rc-terrace-antipasto", "Antipasto", "OTHER", "Antipasto platter.", { location: "200 level", tags: [RCT, "TODO: Verify terrace access"] }),
  bpItem(RC, RCT, "rc-rogers-terrace", "rc-terrace-ice-cream-bar", "Ice Cream Bar", "DESSERT", "Ice cream bar selections.", { location: "200 level" }),
  bpItem(RC, RCT, "rc-heinz-club-328", "rc-heinz-steak-mushroom-bowl", "Steak and Mushroom Bowl", "VEGAN", "Plant-based steak and mushroom bowl (menu as listed).", { location: "Club 328" }),
  bpItem(RC, RCT, "rc-halal-kiosks", "rc-halal-hot-dog", "Halal Hot Dog", "HOT_DOG", "Halal-certified beef hot dog.", { location: "Multiple locations" }),
  bpItem(RC, RCT, "rc-halal-kiosks", "rc-halal-chicken", "Halal Chicken", "CHICKEN", "Halal chicken tenders or sandwich (format varies).", { location: "Multiple locations", tags: [RCT, "TODO: Confirm menu format by kiosk"] }),
  bpItem(RC, RCT, "rc-gluten-free-main-concessions", "rc-gf-bun-option", "Gluten-Free Bun Option", "GLUTEN_FREE", "GF bun substitute at main concession hubs.", { location: "Main concourse" }),
  bpItem(RC, RCT, "rc-gluten-free-main-concessions", "rc-gf-dedicated-fryer-fries", "Dedicated Fryer Fries", "GLUTEN_FREE", "Fries from dedicated GF fryer where offered.", { location: "Main concourse", tags: [RCT, "TODO: Confirm stands with dedicated fryer"] })
];
